// Generate the finite-domain ROM using the installed HLS implementation itself.
// No host libm approximation and no change to the FP16 exponent contract.
#include <ap_int.h>
#include <hls_math.h>
#include <utils/x_hls_utils.h>
#include <fstream>
#include <vector>
#include <iostream>
#include <iomanip>
int main(int argc,char**argv){
 if(argc!=2&&argc!=3)return 2;
 std::vector<unsigned> bits;unsigned last=0;
 for(unsigned magnitude=0;magnitude<=0x7c00;magnitude++){
  half input=fp_struct<half>(ap_uint<16>(0x8000|magnitude)).to_half();
  unsigned value=fp_struct<half>(hls::half_exp(input)).data().to_uint();
  if(value>=0x7c00)return 3;
  bits.push_back(value);if(value)last=magnitude;
 }
 unsigned first=0;
 if(argc==3)while(first<=last&&bits[first]==bits[0])first++;
 std::ofstream f(argv[1]);if(!f)return 4;
 f<<"// Generated by exp_rom/generate.cpp using Vivado HLS 2018.3.\n#pragma once\n";
 f<<"template<unsigned LANE> static half exact_negative_exp(half value){\n#pragma HLS INLINE\n";
 f<<" static const unsigned short exp_bits["<<last-first+1<<"]={\n";
 for(unsigned i=first;i<=last;i++){f<<bits[i]<<(i==last?"":",");if(i%16==15)f<<"\n";}
 f<<"\n };\n#pragma HLS RESOURCE variable=exp_bits core=ROM_1P_BRAM\n";
 f<<" ap_uint<15> magnitude=fp_struct<half>(value).data().range(14,0);\n";
 if(first)f<<" if(magnitude<"<<first<<")return fp_struct<half>(ap_uint<16>("<<bits[0]<<")).to_half();\n";
 f<<" ap_uint<16> result=magnitude<"<<last+1<<"?exp_bits[magnitude.to_uint()-"<<first<<"]:0;\n";
 f<<" return fp_struct<half>(result).to_half();\n}\n";
 std::cout<<"negative_encodings_checked="<<bits.size()<<" nonzero_prefix_entries="<<last+1
          <<" first_lookup_index="<<first<<" table_bytes="<<(last-first+1)*2<<" all_later_exp_bits_zero=true\n";
 return !f;
}
