// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module expand_frames (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_V_q_V_dout,
        input_V_q_V_empty_n,
        input_V_q_V_read,
        input_V_limit_dout,
        input_V_limit_empty_n,
        input_V_limit_read,
        input_V_dense_dout,
        input_V_dense_empty_n,
        input_V_dense_read,
        input_V_bypass_dout,
        input_V_bypass_empty_n,
        input_V_bypass_read,
        output_V_p_q_V_din,
        output_V_p_q_V_full_n,
        output_V_p_q_V_write,
        output_V_p_limit_din,
        output_V_p_limit_full_n,
        output_V_p_limit_write,
        output_V_p_dense_din,
        output_V_p_dense_full_n,
        output_V_p_dense_write,
        output_V_p_bypass_din,
        output_V_p_bypass_full_n,
        output_V_p_bypass_write,
        output_V_second_din,
        output_V_second_full_n,
        output_V_second_write,
        output_V_end_din,
        output_V_end_full_n,
        output_V_end_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] input_V_q_V_dout;
input   input_V_q_V_empty_n;
output   input_V_q_V_read;
input  [15:0] input_V_limit_dout;
input   input_V_limit_empty_n;
output   input_V_limit_read;
input   input_V_dense_dout;
input   input_V_dense_empty_n;
output   input_V_dense_read;
input   input_V_bypass_dout;
input   input_V_bypass_empty_n;
output   input_V_bypass_read;
output  [511:0] output_V_p_q_V_din;
input   output_V_p_q_V_full_n;
output   output_V_p_q_V_write;
output  [15:0] output_V_p_limit_din;
input   output_V_p_limit_full_n;
output   output_V_p_limit_write;
output   output_V_p_dense_din;
input   output_V_p_dense_full_n;
output   output_V_p_dense_write;
output   output_V_p_bypass_din;
input   output_V_p_bypass_full_n;
output   output_V_p_bypass_write;
output   output_V_second_din;
input   output_V_second_full_n;
output   output_V_second_write;
output   output_V_end_din;
input   output_V_end_full_n;
output   output_V_end_write;

reg ap_done;
reg ap_idle;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    input_V_q_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg   [0:0] ap_phi_mux_end_phi_fu_133_p4;
reg   [0:0] ap_phi_mux_tmp_second_phi_fu_121_p4;
reg    input_V_limit_blk_n;
reg    input_V_dense_blk_n;
reg    input_V_bypass_blk_n;
reg    output_V_p_q_V_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] end_reg_129;
reg    output_V_p_limit_blk_n;
reg    output_V_p_dense_blk_n;
reg    output_V_p_bypass_blk_n;
reg    output_V_second_blk_n;
reg    output_V_end_blk_n;
reg   [0:0] tmp_second_reg_116;
wire   [0:0] second_fu_222_p2;
wire    input_V_q_V0_status;
reg    ap_predicate_op25_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
wire    output_V_end1_status;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] phitmp_fu_228_p2;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    input_V_q_V0_update;
reg    output_V_end1_update;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] end_2_fu_203_p2;
reg   [15:0] tmp_p_limit_fu_66;
reg   [511:0] tmp_p_q_V_fu_70;
reg   [0:0] tmp_p_bypass_fu_74;
reg   [0:0] tmp_p_dense_fu_78;
wire   [1:0] p_Result_i_fu_193_p4;
wire   [0:0] p_demorgan_fu_210_p2;
wire   [0:0] p_s_fu_216_p2;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((end_reg_129 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        end_reg_129 <= phitmp_fu_228_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        end_reg_129 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((end_reg_129 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_second_reg_116 <= second_fu_222_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_second_reg_116 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_tmp_second_phi_fu_121_p4 == 1'd0) & (ap_phi_mux_end_phi_fu_133_p4 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_p_bypass_fu_74 <= input_V_bypass_dout;
        tmp_p_dense_fu_78 <= input_V_dense_dout;
        tmp_p_limit_fu_66 <= input_V_limit_dout;
        tmp_p_q_V_fu_70 <= input_V_q_V_dout;
    end
end

always @ (*) begin
    if ((ap_phi_mux_end_phi_fu_133_p4 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((end_reg_129 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_end_phi_fu_133_p4 = phitmp_fu_228_p2;
    end else begin
        ap_phi_mux_end_phi_fu_133_p4 = end_reg_129;
    end
end

always @ (*) begin
    if (((end_reg_129 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_tmp_second_phi_fu_121_p4 = second_fu_222_p2;
    end else begin
        ap_phi_mux_tmp_second_phi_fu_121_p4 = tmp_second_reg_116;
    end
end

always @ (*) begin
    if (((ap_phi_mux_tmp_second_phi_fu_121_p4 == 1'd0) & (ap_phi_mux_end_phi_fu_133_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_bypass_blk_n = input_V_bypass_empty_n;
    end else begin
        input_V_bypass_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_phi_mux_tmp_second_phi_fu_121_p4 == 1'd0) & (ap_phi_mux_end_phi_fu_133_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_dense_blk_n = input_V_dense_empty_n;
    end else begin
        input_V_dense_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_phi_mux_tmp_second_phi_fu_121_p4 == 1'd0) & (ap_phi_mux_end_phi_fu_133_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_limit_blk_n = input_V_limit_empty_n;
    end else begin
        input_V_limit_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op25_read_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_V_q_V0_update = 1'b1;
    end else begin
        input_V_q_V0_update = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_tmp_second_phi_fu_121_p4 == 1'd0) & (ap_phi_mux_end_phi_fu_133_p4 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_q_V_blk_n = input_V_q_V_empty_n;
    end else begin
        input_V_q_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((end_reg_129 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        output_V_end1_update = 1'b1;
    end else begin
        output_V_end1_update = 1'b0;
    end
end

always @ (*) begin
    if (((end_reg_129 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        output_V_end_blk_n = output_V_end_full_n;
    end else begin
        output_V_end_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((end_reg_129 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        output_V_p_bypass_blk_n = output_V_p_bypass_full_n;
    end else begin
        output_V_p_bypass_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((end_reg_129 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        output_V_p_dense_blk_n = output_V_p_dense_full_n;
    end else begin
        output_V_p_dense_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((end_reg_129 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        output_V_p_limit_blk_n = output_V_p_limit_full_n;
    end else begin
        output_V_p_limit_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((end_reg_129 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        output_V_p_q_V_blk_n = output_V_p_q_V_full_n;
    end else begin
        output_V_p_q_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((end_reg_129 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        output_V_second_blk_n = output_V_second_full_n;
    end else begin
        output_V_second_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_phi_mux_end_phi_fu_133_p4 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_phi_mux_end_phi_fu_133_p4 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((input_V_q_V0_status == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op25_read_state2 == 1'b1)) | ((end_reg_129 == 1'd1) & (output_V_end1_status == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((input_V_q_V0_status == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op25_read_state2 == 1'b1)) | ((end_reg_129 == 1'd1) & (output_V_end1_status == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((input_V_q_V0_status == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op25_read_state2 == 1'b1)) | ((end_reg_129 == 1'd1) & (output_V_end1_status == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((input_V_q_V0_status == 1'b0) & (ap_predicate_op25_read_state2 == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((end_reg_129 == 1'd1) & (output_V_end1_status == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op25_read_state2 = ((ap_phi_mux_tmp_second_phi_fu_121_p4 == 1'd0) & (ap_phi_mux_end_phi_fu_133_p4 == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign end_2_fu_203_p2 = ((p_Result_i_fu_193_p4 == 2'd3) ? 1'b1 : 1'b0);

assign input_V_bypass_read = input_V_q_V0_update;

assign input_V_dense_read = input_V_q_V0_update;

assign input_V_limit_read = input_V_q_V0_update;

assign input_V_q_V0_status = (input_V_q_V_empty_n & input_V_limit_empty_n & input_V_dense_empty_n & input_V_bypass_empty_n);

assign input_V_q_V_read = input_V_q_V0_update;

assign output_V_end1_status = (output_V_second_full_n & output_V_p_q_V_full_n & output_V_p_limit_full_n & output_V_p_dense_full_n & output_V_p_bypass_full_n & output_V_end_full_n);

assign output_V_end_din = end_2_fu_203_p2;

assign output_V_end_write = output_V_end1_update;

assign output_V_p_bypass_din = tmp_p_bypass_fu_74;

assign output_V_p_bypass_write = output_V_end1_update;

assign output_V_p_dense_din = tmp_p_dense_fu_78;

assign output_V_p_dense_write = output_V_end1_update;

assign output_V_p_limit_din = tmp_p_limit_fu_66;

assign output_V_p_limit_write = output_V_end1_update;

assign output_V_p_q_V_din = tmp_p_q_V_fu_70;

assign output_V_p_q_V_write = output_V_end1_update;

assign output_V_second_din = tmp_second_reg_116;

assign output_V_second_write = output_V_end1_update;

assign p_Result_i_fu_193_p4 = {{tmp_p_q_V_fu_70[511:510]}};

assign p_demorgan_fu_210_p2 = (tmp_second_reg_116 | tmp_p_bypass_fu_74);

assign p_s_fu_216_p2 = (p_demorgan_fu_210_p2 ^ 1'd1);

assign phitmp_fu_228_p2 = (end_2_fu_203_p2 ^ 1'd1);

assign second_fu_222_p2 = (tmp_p_dense_fu_78 & p_s_fu_216_p2);

assign start_out = real_start;

endmodule //expand_frames
