// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module merge_frames (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_V_q_V_dout,
        input_V_q_V_empty_n,
        input_V_q_V_read,
        input_V_mask_V_dout,
        input_V_mask_V_empty_n,
        input_V_mask_V_read,
        input_V_dense_dout,
        input_V_dense_empty_n,
        input_V_dense_read,
        input_V_second_dout,
        input_V_second_empty_n,
        input_V_second_read,
        input_V_end_dout,
        input_V_end_empty_n,
        input_V_end_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] input_V_q_V_dout;
input   input_V_q_V_empty_n;
output   input_V_q_V_read;
input  [3:0] input_V_mask_V_dout;
input   input_V_mask_V_empty_n;
output   input_V_mask_V_read;
input   input_V_dense_dout;
input   input_V_dense_empty_n;
output   input_V_dense_read;
input   input_V_second_dout;
input   input_V_second_empty_n;
output   input_V_second_read;
input   input_V_end_dout;
input   input_V_end_empty_n;
output   input_V_end_read;
output  [511:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[511:0] output_V_V_din;
reg output_V_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    input_V_q_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    input_V_mask_V_blk_n;
reg    input_V_dense_blk_n;
reg    input_V_second_blk_n;
reg    input_V_end_blk_n;
reg    output_V_V_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] tmp_s_reg_197;
reg   [0:0] tmp_second_reg_189;
reg   [0:0] tmp_dense_reg_185;
reg   [511:0] tmp_q_V_reg_174;
wire    input_V_q_V0_status;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op40_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_dense_fu_113_p1;
wire   [0:0] tmp_second_fu_117_p1;
wire   [0:0] tmp_end_fu_121_p1;
wire   [0:0] tmp_s_fu_135_p2;
wire   [3:0] ret_V_fu_149_p2;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
wire   [3:0] ap_phi_reg_pp0_iter0_p_s_reg_91;
reg   [3:0] ap_phi_reg_pp0_iter1_p_s_reg_91;
reg    input_V_q_V0_update;
reg    ap_block_pp0_stage0_01001;
wire   [511:0] p_Result_s_fu_155_p5;
reg   [3:0] lhs_V_fu_66;
wire   [1:0] p_Result_i_fu_125_p4;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_121;
reg    ap_condition_137;
reg    ap_condition_157;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((tmp_end_fu_121_p1 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_137)) begin
        if (((tmp_s_fu_135_p2 == 1'd1) & (tmp_dense_fu_113_p1 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_s_reg_91 <= input_V_mask_V_dout;
        end else if ((1'b1 == ap_condition_121)) begin
            ap_phi_reg_pp0_iter1_p_s_reg_91 <= ret_V_fu_149_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_s_reg_91 <= ap_phi_reg_pp0_iter0_p_s_reg_91;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_135_p2 == 1'd1) & (tmp_dense_fu_113_p1 == 1'd1) & (tmp_second_fu_117_p1 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        lhs_V_fu_66 <= input_V_mask_V_dout;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        lhs_V_fu_66 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_dense_reg_185 <= input_V_dense_dout;
        tmp_q_V_reg_174 <= input_V_q_V_dout;
        tmp_s_reg_197 <= tmp_s_fu_135_p2;
        tmp_second_reg_189 <= input_V_second_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_dense_blk_n = input_V_dense_empty_n;
    end else begin
        input_V_dense_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_end_blk_n = input_V_end_empty_n;
    end else begin
        input_V_end_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_mask_V_blk_n = input_V_mask_V_empty_n;
    end else begin
        input_V_mask_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_V_q_V0_update = 1'b1;
    end else begin
        input_V_q_V0_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_q_V_blk_n = input_V_q_V_empty_n;
    end else begin
        input_V_q_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_second_blk_n = input_V_second_empty_n;
    end else begin
        input_V_second_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((tmp_dense_reg_185 == 1'd0) & (tmp_s_reg_197 == 1'd1)) | ((tmp_second_reg_189 == 1'd1) & (tmp_s_reg_197 == 1'd1)))) | ((tmp_s_reg_197 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        output_V_V_blk_n = output_V_V_full_n;
    end else begin
        output_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_157)) begin
        if ((ap_predicate_op40_write_state3 == 1'b1)) begin
            output_V_V_din = p_Result_s_fu_155_p5;
        end else if ((tmp_s_reg_197 == 1'd0)) begin
            output_V_V_din = tmp_q_V_reg_174;
        end else begin
            output_V_V_din = 'bx;
        end
    end else begin
        output_V_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_op40_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_s_reg_197 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        output_V_V_write = 1'b1;
    end else begin
        output_V_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((output_V_V_full_n == 1'b0) & (ap_predicate_op40_write_state3 == 1'b1)) | ((tmp_s_reg_197 == 1'd0) & (output_V_V_full_n == 1'b0)))) | ((input_V_q_V0_status == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((output_V_V_full_n == 1'b0) & (ap_predicate_op40_write_state3 == 1'b1)) | ((tmp_s_reg_197 == 1'd0) & (output_V_V_full_n == 1'b0)))) | ((input_V_q_V0_status == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((output_V_V_full_n == 1'b0) & (ap_predicate_op40_write_state3 == 1'b1)) | ((tmp_s_reg_197 == 1'd0) & (output_V_V_full_n == 1'b0)))) | ((input_V_q_V0_status == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (input_V_q_V0_status == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((output_V_V_full_n == 1'b0) & (ap_predicate_op40_write_state3 == 1'b1)) | ((tmp_s_reg_197 == 1'd0) & (output_V_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_121 = ((tmp_s_fu_135_p2 == 1'd1) & (tmp_second_fu_117_p1 == 1'd1) & (tmp_dense_fu_113_p1 == 1'd1));
end

always @ (*) begin
    ap_condition_137 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_157 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_p_s_reg_91 = 'bx;

always @ (*) begin
    ap_predicate_op40_write_state3 = (((tmp_dense_reg_185 == 1'd0) & (tmp_s_reg_197 == 1'd1)) | ((tmp_second_reg_189 == 1'd1) & (tmp_s_reg_197 == 1'd1)));
end

assign input_V_dense_read = input_V_q_V0_update;

assign input_V_end_read = input_V_q_V0_update;

assign input_V_mask_V_read = input_V_q_V0_update;

assign input_V_q_V0_status = (input_V_second_empty_n & input_V_q_V_empty_n & input_V_mask_V_empty_n & input_V_end_empty_n & input_V_dense_empty_n);

assign input_V_q_V_read = input_V_q_V0_update;

assign input_V_second_read = input_V_q_V0_update;

assign p_Result_i_fu_125_p4 = {{input_V_q_V_dout[511:510]}};

assign p_Result_s_fu_155_p5 = {{tmp_q_V_reg_174[511:228]}, {ap_phi_reg_pp0_iter1_p_s_reg_91}, {tmp_q_V_reg_174[223:0]}};

assign ret_V_fu_149_p2 = (lhs_V_fu_66 | input_V_mask_V_dout);

assign tmp_dense_fu_113_p1 = input_V_dense_dout;

assign tmp_end_fu_121_p1 = input_V_end_dout;

assign tmp_s_fu_135_p2 = ((p_Result_i_fu_125_p4 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_second_fu_117_p1 = input_V_second_dout;

endmodule //merge_frames
