// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module prepare_frames (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        output_V_q_V_din,
        output_V_q_V_full_n,
        output_V_q_V_write,
        output_V_limit_din,
        output_V_limit_full_n,
        output_V_limit_write,
        output_V_dense_din,
        output_V_dense_full_n,
        output_V_dense_write,
        output_V_bypass_din,
        output_V_bypass_full_n,
        output_V_bypass_write,
        mode_dout,
        mode_empty_n,
        mode_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state37 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [511:0] output_V_q_V_din;
input   output_V_q_V_full_n;
output   output_V_q_V_write;
output  [15:0] output_V_limit_din;
input   output_V_limit_full_n;
output   output_V_limit_write;
output   output_V_dense_din;
input   output_V_dense_full_n;
output   output_V_dense_write;
output   output_V_bypass_din;
input   output_V_bypass_full_n;
output   output_V_bypass_write;
input  [31:0] mode_dout;
input   mode_empty_n;
output   mode_read;

reg ap_done;
reg ap_idle;
reg start_write;
reg input_V_V_read;
reg mode_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    input_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    output_V_q_V_blk_n;
reg    ap_enable_reg_pp0_iter34;
reg    output_V_limit_blk_n;
reg    output_V_dense_blk_n;
reg    output_V_bypass_blk_n;
reg    mode_blk_n;
wire   [0:0] tmp_i_fu_165_p2;
reg   [0:0] tmp_i_reg_287;
reg    ap_block_state1;
wire   [0:0] p_not_i_fu_171_p2;
reg   [0:0] p_not_i_reg_292;
wire   [0:0] tmp_i_110_fu_177_p2;
reg   [0:0] tmp_i_110_reg_297;
wire   [0:0] icmp_fu_193_p2;
reg   [0:0] icmp_reg_302;
reg   [511:0] tmp_V_reg_307;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
wire    ap_block_state8_pp0_stage0_iter6;
wire    ap_block_state9_pp0_stage0_iter7;
wire    ap_block_state10_pp0_stage0_iter8;
wire    ap_block_state11_pp0_stage0_iter9;
wire    ap_block_state12_pp0_stage0_iter10;
wire    ap_block_state13_pp0_stage0_iter11;
wire    ap_block_state14_pp0_stage0_iter12;
wire    ap_block_state15_pp0_stage0_iter13;
wire    ap_block_state16_pp0_stage0_iter14;
wire    ap_block_state17_pp0_stage0_iter15;
wire    ap_block_state18_pp0_stage0_iter16;
wire    ap_block_state19_pp0_stage0_iter17;
wire    ap_block_state20_pp0_stage0_iter18;
wire    ap_block_state21_pp0_stage0_iter19;
wire    ap_block_state22_pp0_stage0_iter20;
wire    ap_block_state23_pp0_stage0_iter21;
wire    ap_block_state24_pp0_stage0_iter22;
wire    ap_block_state25_pp0_stage0_iter23;
wire    ap_block_state26_pp0_stage0_iter24;
wire    ap_block_state27_pp0_stage0_iter25;
wire    ap_block_state28_pp0_stage0_iter26;
wire    ap_block_state29_pp0_stage0_iter27;
wire    ap_block_state30_pp0_stage0_iter28;
wire    ap_block_state31_pp0_stage0_iter29;
wire    ap_block_state32_pp0_stage0_iter30;
wire    ap_block_state33_pp0_stage0_iter31;
wire    ap_block_state34_pp0_stage0_iter32;
wire    ap_block_state35_pp0_stage0_iter33;
wire    output_V_q_V1_status;
reg    ap_block_state36_pp0_stage0_iter34;
reg    ap_block_pp0_stage0_11001;
reg   [511:0] tmp_V_reg_307_pp0_iter1_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter2_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter3_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter4_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter5_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter6_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter7_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter8_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter9_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter10_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter11_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter12_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter13_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter14_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter15_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter16_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter17_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter18_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter19_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter20_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter21_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter22_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter23_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter24_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter25_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter26_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter27_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter28_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter29_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter30_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter31_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter32_reg;
reg   [511:0] tmp_V_reg_307_pp0_iter33_reg;
wire   [0:0] p_dense_fu_250_p2;
reg   [0:0] p_dense_reg_312;
reg   [0:0] p_dense_reg_312_pp0_iter1_reg;
reg   [0:0] p_dense_reg_312_pp0_iter2_reg;
reg   [0:0] p_dense_reg_312_pp0_iter3_reg;
reg   [0:0] p_dense_reg_312_pp0_iter4_reg;
reg   [0:0] p_dense_reg_312_pp0_iter5_reg;
reg   [0:0] p_dense_reg_312_pp0_iter6_reg;
reg   [0:0] p_dense_reg_312_pp0_iter7_reg;
reg   [0:0] p_dense_reg_312_pp0_iter8_reg;
reg   [0:0] p_dense_reg_312_pp0_iter9_reg;
reg   [0:0] p_dense_reg_312_pp0_iter10_reg;
reg   [0:0] p_dense_reg_312_pp0_iter11_reg;
reg   [0:0] p_dense_reg_312_pp0_iter12_reg;
reg   [0:0] p_dense_reg_312_pp0_iter13_reg;
reg   [0:0] p_dense_reg_312_pp0_iter14_reg;
reg   [0:0] p_dense_reg_312_pp0_iter15_reg;
reg   [0:0] p_dense_reg_312_pp0_iter16_reg;
reg   [0:0] p_dense_reg_312_pp0_iter17_reg;
reg   [0:0] p_dense_reg_312_pp0_iter18_reg;
reg   [0:0] p_dense_reg_312_pp0_iter19_reg;
reg   [0:0] p_dense_reg_312_pp0_iter20_reg;
reg   [0:0] p_dense_reg_312_pp0_iter21_reg;
reg   [0:0] p_dense_reg_312_pp0_iter22_reg;
reg   [0:0] p_dense_reg_312_pp0_iter23_reg;
reg   [0:0] p_dense_reg_312_pp0_iter24_reg;
reg   [0:0] p_dense_reg_312_pp0_iter25_reg;
reg   [0:0] p_dense_reg_312_pp0_iter26_reg;
reg   [0:0] p_dense_reg_312_pp0_iter27_reg;
reg   [0:0] p_dense_reg_312_pp0_iter28_reg;
reg   [0:0] p_dense_reg_312_pp0_iter29_reg;
reg   [0:0] p_dense_reg_312_pp0_iter30_reg;
reg   [0:0] p_dense_reg_312_pp0_iter31_reg;
reg   [0:0] p_dense_reg_312_pp0_iter32_reg;
reg   [0:0] p_dense_reg_312_pp0_iter33_reg;
wire   [0:0] p_bypass_fu_262_p2;
reg   [0:0] p_bypass_reg_317;
reg   [0:0] p_bypass_reg_317_pp0_iter1_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter2_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter3_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter4_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter5_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter6_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter7_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter8_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter9_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter10_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter11_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter12_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter13_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter14_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter15_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter16_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter17_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter18_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter19_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter20_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter21_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter22_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter23_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter24_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter25_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter26_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter27_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter28_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter29_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter30_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter31_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter32_reg;
reg   [0:0] p_bypass_reg_317_pp0_iter33_reg;
reg   [15:0] p_Result_53_reg_322;
wire   [0:0] phitmp_i_fu_277_p2;
wire   [15:0] opacity_fu_283_p1;
reg   [15:0] opacity_reg_331;
reg   [15:0] opacity_reg_331_pp0_iter2_reg;
wire   [0:0] grp_fu_160_p2;
reg   [0:0] tmp_183_i_reg_337;
reg   [0:0] tmp_183_i_reg_337_pp0_iter4_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter5_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter6_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter7_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter8_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter9_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter10_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter11_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter12_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter13_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter14_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter15_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter16_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter17_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter18_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter19_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter20_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter21_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter22_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter23_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter24_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter25_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter26_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter27_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter28_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter29_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter30_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter31_reg;
reg   [0:0] tmp_183_i_reg_337_pp0_iter32_reg;
wire   [15:0] grp_fu_155_p2;
reg   [15:0] x_assign_reg_341;
wire   [15:0] grp_log_generic_fu_142_ap_return;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
wire    grp_log_generic_fu_142_ap_start;
wire    grp_log_generic_fu_142_ap_done;
wire    grp_log_generic_fu_142_ap_idle;
wire    grp_log_generic_fu_142_ap_ready;
reg    grp_log_generic_fu_142_ap_ce;
reg    ap_block_state2_pp0_stage0_iter0_ignore_call1;
wire    ap_block_state3_pp0_stage0_iter1_ignore_call1;
wire    ap_block_state4_pp0_stage0_iter2_ignore_call1;
wire    ap_block_state5_pp0_stage0_iter3_ignore_call1;
wire    ap_block_state6_pp0_stage0_iter4_ignore_call1;
wire    ap_block_state7_pp0_stage0_iter5_ignore_call1;
wire    ap_block_state8_pp0_stage0_iter6_ignore_call1;
wire    ap_block_state9_pp0_stage0_iter7_ignore_call1;
wire    ap_block_state10_pp0_stage0_iter8_ignore_call1;
wire    ap_block_state11_pp0_stage0_iter9_ignore_call1;
wire    ap_block_state12_pp0_stage0_iter10_ignore_call1;
wire    ap_block_state13_pp0_stage0_iter11_ignore_call1;
wire    ap_block_state14_pp0_stage0_iter12_ignore_call1;
wire    ap_block_state15_pp0_stage0_iter13_ignore_call1;
wire    ap_block_state16_pp0_stage0_iter14_ignore_call1;
wire    ap_block_state17_pp0_stage0_iter15_ignore_call1;
wire    ap_block_state18_pp0_stage0_iter16_ignore_call1;
wire    ap_block_state19_pp0_stage0_iter17_ignore_call1;
wire    ap_block_state20_pp0_stage0_iter18_ignore_call1;
wire    ap_block_state21_pp0_stage0_iter19_ignore_call1;
wire    ap_block_state22_pp0_stage0_iter20_ignore_call1;
wire    ap_block_state23_pp0_stage0_iter21_ignore_call1;
wire    ap_block_state24_pp0_stage0_iter22_ignore_call1;
wire    ap_block_state25_pp0_stage0_iter23_ignore_call1;
wire    ap_block_state26_pp0_stage0_iter24_ignore_call1;
wire    ap_block_state27_pp0_stage0_iter25_ignore_call1;
wire    ap_block_state28_pp0_stage0_iter26_ignore_call1;
wire    ap_block_state29_pp0_stage0_iter27_ignore_call1;
wire    ap_block_state30_pp0_stage0_iter28_ignore_call1;
wire    ap_block_state31_pp0_stage0_iter29_ignore_call1;
wire    ap_block_state32_pp0_stage0_iter30_ignore_call1;
wire    ap_block_state33_pp0_stage0_iter31_ignore_call1;
wire    ap_block_state34_pp0_stage0_iter32_ignore_call1;
wire    ap_block_state35_pp0_stage0_iter33_ignore_call1;
reg    ap_block_state36_pp0_stage0_iter34_ignore_call1;
reg    ap_block_pp0_stage0_11001_ignoreCallOp79;
wire   [15:0] ap_phi_reg_pp0_iter0_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter1_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter2_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter3_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter4_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter5_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter6_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter7_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter8_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter9_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter10_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter11_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter12_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter13_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter14_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter15_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter16_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter17_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter18_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter19_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter20_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter21_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter22_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter23_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter24_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter25_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter26_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter27_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter28_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter29_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter30_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter31_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter32_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter33_p_limit_reg_130;
reg   [15:0] ap_phi_reg_pp0_iter34_p_limit_reg_130;
reg    grp_log_generic_fu_142_ap_start_reg;
reg    output_V_q_V1_update;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] grp_fu_160_p0;
wire   [30:0] tmp_fu_183_p4;
wire   [1:0] p_Result_i_i_fu_199_p4;
wire   [0:0] p_Result_s_fu_209_p3;
wire   [0:0] brmerge_i_fu_223_p2;
wire   [0:0] or_cond_i_fu_228_p2;
wire   [0:0] p_Result_i_0_i_fu_233_p2;
wire   [0:0] not_or_cond_i_fu_238_p2;
wire   [0:0] tmp_181_i_fu_217_p2;
wire   [0:0] p_Result_i_0_i_111_fu_244_p2;
wire   [0:0] tmp_182_i_fu_256_p2;
reg    grp_fu_155_ce;
reg    grp_fu_160_ce;
reg    ap_block_pp0_stage0_00001;
wire    ap_CS_fsm_state37;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 grp_log_generic_fu_142_ap_start_reg = 1'b0;
end

log_generic grp_log_generic_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_log_generic_fu_142_ap_start),
    .ap_done(grp_log_generic_fu_142_ap_done),
    .ap_idle(grp_log_generic_fu_142_ap_idle),
    .ap_ready(grp_log_generic_fu_142_ap_ready),
    .ap_ce(grp_log_generic_fu_142_ap_ce),
    .base_r(x_assign_reg_341),
    .ap_return(grp_log_generic_fu_142_ap_return)
);

flicker_render_piudo #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
flicker_render_piudo_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(opacity_reg_331_pp0_iter2_reg),
    .din1(16'd23544),
    .ce(grp_fu_155_ce),
    .dout(grp_fu_155_p2)
);

flicker_render_pivdy #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 1 ))
flicker_render_pivdy_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_160_p0),
    .din1(16'd0),
    .ce(grp_fu_160_ce),
    .opcode(5'd2),
    .dout(grp_fu_160_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state37)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (phitmp_i_fu_277_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (mode_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end else if ((~((real_start == 1'b0) | (mode_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter34 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_log_generic_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_183_i_reg_337_pp0_iter7_reg == 1'd1) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            grp_log_generic_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_log_generic_fu_142_ap_ready == 1'b1)) begin
            grp_log_generic_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter33 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((tmp_183_i_reg_337_pp0_iter32_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter34_p_limit_reg_130 <= grp_log_generic_fu_142_ap_return;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter34_p_limit_reg_130 <= ap_phi_reg_pp0_iter33_p_limit_reg_130;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((grp_fu_160_p2 == 1'd0)) begin
            ap_phi_reg_pp0_iter4_p_limit_reg_130 <= 16'd64511;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_p_limit_reg_130 <= ap_phi_reg_pp0_iter3_p_limit_reg_130;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_p_limit_reg_130 <= ap_phi_reg_pp0_iter9_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_p_limit_reg_130 <= ap_phi_reg_pp0_iter10_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_p_limit_reg_130 <= ap_phi_reg_pp0_iter11_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_p_limit_reg_130 <= ap_phi_reg_pp0_iter12_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_p_limit_reg_130 <= ap_phi_reg_pp0_iter13_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter15_p_limit_reg_130 <= ap_phi_reg_pp0_iter14_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter16_p_limit_reg_130 <= ap_phi_reg_pp0_iter15_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter17_p_limit_reg_130 <= ap_phi_reg_pp0_iter16_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter18_p_limit_reg_130 <= ap_phi_reg_pp0_iter17_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter19_p_limit_reg_130 <= ap_phi_reg_pp0_iter18_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_p_limit_reg_130 <= ap_phi_reg_pp0_iter0_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter20_p_limit_reg_130 <= ap_phi_reg_pp0_iter19_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter21_p_limit_reg_130 <= ap_phi_reg_pp0_iter20_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter22_p_limit_reg_130 <= ap_phi_reg_pp0_iter21_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter23_p_limit_reg_130 <= ap_phi_reg_pp0_iter22_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter24_p_limit_reg_130 <= ap_phi_reg_pp0_iter23_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter25_p_limit_reg_130 <= ap_phi_reg_pp0_iter24_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter26_p_limit_reg_130 <= ap_phi_reg_pp0_iter25_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter27_p_limit_reg_130 <= ap_phi_reg_pp0_iter26_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter27 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter28_p_limit_reg_130 <= ap_phi_reg_pp0_iter27_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter28 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter29_p_limit_reg_130 <= ap_phi_reg_pp0_iter28_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_p_limit_reg_130 <= ap_phi_reg_pp0_iter1_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter29 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter30_p_limit_reg_130 <= ap_phi_reg_pp0_iter29_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter30 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter31_p_limit_reg_130 <= ap_phi_reg_pp0_iter30_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter31 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter32_p_limit_reg_130 <= ap_phi_reg_pp0_iter31_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter32 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter33_p_limit_reg_130 <= ap_phi_reg_pp0_iter32_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_p_limit_reg_130 <= ap_phi_reg_pp0_iter2_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_p_limit_reg_130 <= ap_phi_reg_pp0_iter4_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_p_limit_reg_130 <= ap_phi_reg_pp0_iter5_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_p_limit_reg_130 <= ap_phi_reg_pp0_iter6_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_p_limit_reg_130 <= ap_phi_reg_pp0_iter7_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_p_limit_reg_130 <= ap_phi_reg_pp0_iter8_p_limit_reg_130;
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (mode_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_reg_302 <= icmp_fu_193_p2;
        p_not_i_reg_292 <= p_not_i_fu_171_p2;
        tmp_i_110_reg_297 <= tmp_i_110_fu_177_p2;
        tmp_i_reg_287 <= tmp_i_fu_165_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        opacity_reg_331 <= opacity_fu_283_p1;
        p_Result_53_reg_322 <= {{input_V_V_dout[95:80]}};
        p_bypass_reg_317 <= p_bypass_fu_262_p2;
        p_bypass_reg_317_pp0_iter1_reg <= p_bypass_reg_317;
        p_dense_reg_312 <= p_dense_fu_250_p2;
        p_dense_reg_312_pp0_iter1_reg <= p_dense_reg_312;
        tmp_V_reg_307 <= input_V_V_dout;
        tmp_V_reg_307_pp0_iter1_reg <= tmp_V_reg_307;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        opacity_reg_331_pp0_iter2_reg <= opacity_reg_331;
        p_bypass_reg_317_pp0_iter10_reg <= p_bypass_reg_317_pp0_iter9_reg;
        p_bypass_reg_317_pp0_iter11_reg <= p_bypass_reg_317_pp0_iter10_reg;
        p_bypass_reg_317_pp0_iter12_reg <= p_bypass_reg_317_pp0_iter11_reg;
        p_bypass_reg_317_pp0_iter13_reg <= p_bypass_reg_317_pp0_iter12_reg;
        p_bypass_reg_317_pp0_iter14_reg <= p_bypass_reg_317_pp0_iter13_reg;
        p_bypass_reg_317_pp0_iter15_reg <= p_bypass_reg_317_pp0_iter14_reg;
        p_bypass_reg_317_pp0_iter16_reg <= p_bypass_reg_317_pp0_iter15_reg;
        p_bypass_reg_317_pp0_iter17_reg <= p_bypass_reg_317_pp0_iter16_reg;
        p_bypass_reg_317_pp0_iter18_reg <= p_bypass_reg_317_pp0_iter17_reg;
        p_bypass_reg_317_pp0_iter19_reg <= p_bypass_reg_317_pp0_iter18_reg;
        p_bypass_reg_317_pp0_iter20_reg <= p_bypass_reg_317_pp0_iter19_reg;
        p_bypass_reg_317_pp0_iter21_reg <= p_bypass_reg_317_pp0_iter20_reg;
        p_bypass_reg_317_pp0_iter22_reg <= p_bypass_reg_317_pp0_iter21_reg;
        p_bypass_reg_317_pp0_iter23_reg <= p_bypass_reg_317_pp0_iter22_reg;
        p_bypass_reg_317_pp0_iter24_reg <= p_bypass_reg_317_pp0_iter23_reg;
        p_bypass_reg_317_pp0_iter25_reg <= p_bypass_reg_317_pp0_iter24_reg;
        p_bypass_reg_317_pp0_iter26_reg <= p_bypass_reg_317_pp0_iter25_reg;
        p_bypass_reg_317_pp0_iter27_reg <= p_bypass_reg_317_pp0_iter26_reg;
        p_bypass_reg_317_pp0_iter28_reg <= p_bypass_reg_317_pp0_iter27_reg;
        p_bypass_reg_317_pp0_iter29_reg <= p_bypass_reg_317_pp0_iter28_reg;
        p_bypass_reg_317_pp0_iter2_reg <= p_bypass_reg_317_pp0_iter1_reg;
        p_bypass_reg_317_pp0_iter30_reg <= p_bypass_reg_317_pp0_iter29_reg;
        p_bypass_reg_317_pp0_iter31_reg <= p_bypass_reg_317_pp0_iter30_reg;
        p_bypass_reg_317_pp0_iter32_reg <= p_bypass_reg_317_pp0_iter31_reg;
        p_bypass_reg_317_pp0_iter33_reg <= p_bypass_reg_317_pp0_iter32_reg;
        p_bypass_reg_317_pp0_iter3_reg <= p_bypass_reg_317_pp0_iter2_reg;
        p_bypass_reg_317_pp0_iter4_reg <= p_bypass_reg_317_pp0_iter3_reg;
        p_bypass_reg_317_pp0_iter5_reg <= p_bypass_reg_317_pp0_iter4_reg;
        p_bypass_reg_317_pp0_iter6_reg <= p_bypass_reg_317_pp0_iter5_reg;
        p_bypass_reg_317_pp0_iter7_reg <= p_bypass_reg_317_pp0_iter6_reg;
        p_bypass_reg_317_pp0_iter8_reg <= p_bypass_reg_317_pp0_iter7_reg;
        p_bypass_reg_317_pp0_iter9_reg <= p_bypass_reg_317_pp0_iter8_reg;
        p_dense_reg_312_pp0_iter10_reg <= p_dense_reg_312_pp0_iter9_reg;
        p_dense_reg_312_pp0_iter11_reg <= p_dense_reg_312_pp0_iter10_reg;
        p_dense_reg_312_pp0_iter12_reg <= p_dense_reg_312_pp0_iter11_reg;
        p_dense_reg_312_pp0_iter13_reg <= p_dense_reg_312_pp0_iter12_reg;
        p_dense_reg_312_pp0_iter14_reg <= p_dense_reg_312_pp0_iter13_reg;
        p_dense_reg_312_pp0_iter15_reg <= p_dense_reg_312_pp0_iter14_reg;
        p_dense_reg_312_pp0_iter16_reg <= p_dense_reg_312_pp0_iter15_reg;
        p_dense_reg_312_pp0_iter17_reg <= p_dense_reg_312_pp0_iter16_reg;
        p_dense_reg_312_pp0_iter18_reg <= p_dense_reg_312_pp0_iter17_reg;
        p_dense_reg_312_pp0_iter19_reg <= p_dense_reg_312_pp0_iter18_reg;
        p_dense_reg_312_pp0_iter20_reg <= p_dense_reg_312_pp0_iter19_reg;
        p_dense_reg_312_pp0_iter21_reg <= p_dense_reg_312_pp0_iter20_reg;
        p_dense_reg_312_pp0_iter22_reg <= p_dense_reg_312_pp0_iter21_reg;
        p_dense_reg_312_pp0_iter23_reg <= p_dense_reg_312_pp0_iter22_reg;
        p_dense_reg_312_pp0_iter24_reg <= p_dense_reg_312_pp0_iter23_reg;
        p_dense_reg_312_pp0_iter25_reg <= p_dense_reg_312_pp0_iter24_reg;
        p_dense_reg_312_pp0_iter26_reg <= p_dense_reg_312_pp0_iter25_reg;
        p_dense_reg_312_pp0_iter27_reg <= p_dense_reg_312_pp0_iter26_reg;
        p_dense_reg_312_pp0_iter28_reg <= p_dense_reg_312_pp0_iter27_reg;
        p_dense_reg_312_pp0_iter29_reg <= p_dense_reg_312_pp0_iter28_reg;
        p_dense_reg_312_pp0_iter2_reg <= p_dense_reg_312_pp0_iter1_reg;
        p_dense_reg_312_pp0_iter30_reg <= p_dense_reg_312_pp0_iter29_reg;
        p_dense_reg_312_pp0_iter31_reg <= p_dense_reg_312_pp0_iter30_reg;
        p_dense_reg_312_pp0_iter32_reg <= p_dense_reg_312_pp0_iter31_reg;
        p_dense_reg_312_pp0_iter33_reg <= p_dense_reg_312_pp0_iter32_reg;
        p_dense_reg_312_pp0_iter3_reg <= p_dense_reg_312_pp0_iter2_reg;
        p_dense_reg_312_pp0_iter4_reg <= p_dense_reg_312_pp0_iter3_reg;
        p_dense_reg_312_pp0_iter5_reg <= p_dense_reg_312_pp0_iter4_reg;
        p_dense_reg_312_pp0_iter6_reg <= p_dense_reg_312_pp0_iter5_reg;
        p_dense_reg_312_pp0_iter7_reg <= p_dense_reg_312_pp0_iter6_reg;
        p_dense_reg_312_pp0_iter8_reg <= p_dense_reg_312_pp0_iter7_reg;
        p_dense_reg_312_pp0_iter9_reg <= p_dense_reg_312_pp0_iter8_reg;
        tmp_183_i_reg_337 <= grp_fu_160_p2;
        tmp_183_i_reg_337_pp0_iter10_reg <= tmp_183_i_reg_337_pp0_iter9_reg;
        tmp_183_i_reg_337_pp0_iter11_reg <= tmp_183_i_reg_337_pp0_iter10_reg;
        tmp_183_i_reg_337_pp0_iter12_reg <= tmp_183_i_reg_337_pp0_iter11_reg;
        tmp_183_i_reg_337_pp0_iter13_reg <= tmp_183_i_reg_337_pp0_iter12_reg;
        tmp_183_i_reg_337_pp0_iter14_reg <= tmp_183_i_reg_337_pp0_iter13_reg;
        tmp_183_i_reg_337_pp0_iter15_reg <= tmp_183_i_reg_337_pp0_iter14_reg;
        tmp_183_i_reg_337_pp0_iter16_reg <= tmp_183_i_reg_337_pp0_iter15_reg;
        tmp_183_i_reg_337_pp0_iter17_reg <= tmp_183_i_reg_337_pp0_iter16_reg;
        tmp_183_i_reg_337_pp0_iter18_reg <= tmp_183_i_reg_337_pp0_iter17_reg;
        tmp_183_i_reg_337_pp0_iter19_reg <= tmp_183_i_reg_337_pp0_iter18_reg;
        tmp_183_i_reg_337_pp0_iter20_reg <= tmp_183_i_reg_337_pp0_iter19_reg;
        tmp_183_i_reg_337_pp0_iter21_reg <= tmp_183_i_reg_337_pp0_iter20_reg;
        tmp_183_i_reg_337_pp0_iter22_reg <= tmp_183_i_reg_337_pp0_iter21_reg;
        tmp_183_i_reg_337_pp0_iter23_reg <= tmp_183_i_reg_337_pp0_iter22_reg;
        tmp_183_i_reg_337_pp0_iter24_reg <= tmp_183_i_reg_337_pp0_iter23_reg;
        tmp_183_i_reg_337_pp0_iter25_reg <= tmp_183_i_reg_337_pp0_iter24_reg;
        tmp_183_i_reg_337_pp0_iter26_reg <= tmp_183_i_reg_337_pp0_iter25_reg;
        tmp_183_i_reg_337_pp0_iter27_reg <= tmp_183_i_reg_337_pp0_iter26_reg;
        tmp_183_i_reg_337_pp0_iter28_reg <= tmp_183_i_reg_337_pp0_iter27_reg;
        tmp_183_i_reg_337_pp0_iter29_reg <= tmp_183_i_reg_337_pp0_iter28_reg;
        tmp_183_i_reg_337_pp0_iter30_reg <= tmp_183_i_reg_337_pp0_iter29_reg;
        tmp_183_i_reg_337_pp0_iter31_reg <= tmp_183_i_reg_337_pp0_iter30_reg;
        tmp_183_i_reg_337_pp0_iter32_reg <= tmp_183_i_reg_337_pp0_iter31_reg;
        tmp_183_i_reg_337_pp0_iter4_reg <= tmp_183_i_reg_337;
        tmp_183_i_reg_337_pp0_iter5_reg <= tmp_183_i_reg_337_pp0_iter4_reg;
        tmp_183_i_reg_337_pp0_iter6_reg <= tmp_183_i_reg_337_pp0_iter5_reg;
        tmp_183_i_reg_337_pp0_iter7_reg <= tmp_183_i_reg_337_pp0_iter6_reg;
        tmp_183_i_reg_337_pp0_iter8_reg <= tmp_183_i_reg_337_pp0_iter7_reg;
        tmp_183_i_reg_337_pp0_iter9_reg <= tmp_183_i_reg_337_pp0_iter8_reg;
        tmp_V_reg_307_pp0_iter10_reg <= tmp_V_reg_307_pp0_iter9_reg;
        tmp_V_reg_307_pp0_iter11_reg <= tmp_V_reg_307_pp0_iter10_reg;
        tmp_V_reg_307_pp0_iter12_reg <= tmp_V_reg_307_pp0_iter11_reg;
        tmp_V_reg_307_pp0_iter13_reg <= tmp_V_reg_307_pp0_iter12_reg;
        tmp_V_reg_307_pp0_iter14_reg <= tmp_V_reg_307_pp0_iter13_reg;
        tmp_V_reg_307_pp0_iter15_reg <= tmp_V_reg_307_pp0_iter14_reg;
        tmp_V_reg_307_pp0_iter16_reg <= tmp_V_reg_307_pp0_iter15_reg;
        tmp_V_reg_307_pp0_iter17_reg <= tmp_V_reg_307_pp0_iter16_reg;
        tmp_V_reg_307_pp0_iter18_reg <= tmp_V_reg_307_pp0_iter17_reg;
        tmp_V_reg_307_pp0_iter19_reg <= tmp_V_reg_307_pp0_iter18_reg;
        tmp_V_reg_307_pp0_iter20_reg <= tmp_V_reg_307_pp0_iter19_reg;
        tmp_V_reg_307_pp0_iter21_reg <= tmp_V_reg_307_pp0_iter20_reg;
        tmp_V_reg_307_pp0_iter22_reg <= tmp_V_reg_307_pp0_iter21_reg;
        tmp_V_reg_307_pp0_iter23_reg <= tmp_V_reg_307_pp0_iter22_reg;
        tmp_V_reg_307_pp0_iter24_reg <= tmp_V_reg_307_pp0_iter23_reg;
        tmp_V_reg_307_pp0_iter25_reg <= tmp_V_reg_307_pp0_iter24_reg;
        tmp_V_reg_307_pp0_iter26_reg <= tmp_V_reg_307_pp0_iter25_reg;
        tmp_V_reg_307_pp0_iter27_reg <= tmp_V_reg_307_pp0_iter26_reg;
        tmp_V_reg_307_pp0_iter28_reg <= tmp_V_reg_307_pp0_iter27_reg;
        tmp_V_reg_307_pp0_iter29_reg <= tmp_V_reg_307_pp0_iter28_reg;
        tmp_V_reg_307_pp0_iter2_reg <= tmp_V_reg_307_pp0_iter1_reg;
        tmp_V_reg_307_pp0_iter30_reg <= tmp_V_reg_307_pp0_iter29_reg;
        tmp_V_reg_307_pp0_iter31_reg <= tmp_V_reg_307_pp0_iter30_reg;
        tmp_V_reg_307_pp0_iter32_reg <= tmp_V_reg_307_pp0_iter31_reg;
        tmp_V_reg_307_pp0_iter33_reg <= tmp_V_reg_307_pp0_iter32_reg;
        tmp_V_reg_307_pp0_iter3_reg <= tmp_V_reg_307_pp0_iter2_reg;
        tmp_V_reg_307_pp0_iter4_reg <= tmp_V_reg_307_pp0_iter3_reg;
        tmp_V_reg_307_pp0_iter5_reg <= tmp_V_reg_307_pp0_iter4_reg;
        tmp_V_reg_307_pp0_iter6_reg <= tmp_V_reg_307_pp0_iter5_reg;
        tmp_V_reg_307_pp0_iter7_reg <= tmp_V_reg_307_pp0_iter6_reg;
        tmp_V_reg_307_pp0_iter8_reg <= tmp_V_reg_307_pp0_iter7_reg;
        tmp_V_reg_307_pp0_iter9_reg <= tmp_V_reg_307_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_183_i_reg_337_pp0_iter7_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        x_assign_reg_341 <= grp_fu_155_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_155_ce = 1'b1;
    end else begin
        grp_fu_155_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_160_ce = 1'b1;
    end else begin
        grp_fu_160_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp79) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_log_generic_fu_142_ap_ce = 1'b1;
    end else begin
        grp_log_generic_fu_142_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_V_blk_n = input_V_V_empty_n;
    end else begin
        input_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_V_V_read = 1'b1;
    end else begin
        input_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_blk_n = mode_empty_n;
    end else begin
        mode_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (mode_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_read = 1'b1;
    end else begin
        mode_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        output_V_bypass_blk_n = output_V_bypass_full_n;
    end else begin
        output_V_bypass_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        output_V_dense_blk_n = output_V_dense_full_n;
    end else begin
        output_V_dense_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        output_V_limit_blk_n = output_V_limit_full_n;
    end else begin
        output_V_limit_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter34 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        output_V_q_V1_update = 1'b1;
    end else begin
        output_V_q_V1_update = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        output_V_q_V_blk_n = output_V_q_V_full_n;
    end else begin
        output_V_q_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (mode_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter33 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter33 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = (((output_V_q_V1_status == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((output_V_q_V1_status == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((output_V_q_V1_status == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp79 = (((output_V_q_V1_status == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((output_V_q_V1_status == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b1)) | ((input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (mode_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter8_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter9_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter10_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter11_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter12_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter13_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter14_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter15_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter16_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter17_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter18_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter19_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter20_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter21_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter22_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter23_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter24_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter25_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter26_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter27_ignore_call1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (input_V_V_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0_ignore_call1 = (input_V_V_empty_n == 1'b0);
end

assign ap_block_state30_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter28_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter29_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter30_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter31_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter32_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter33_ignore_call1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state36_pp0_stage0_iter34 = (output_V_q_V1_status == 1'b0);
end

always @ (*) begin
    ap_block_state36_pp0_stage0_iter34_ignore_call1 = (output_V_q_V1_status == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter6_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter7_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_p_limit_reg_130 = 'bx;

assign ap_ready = internal_ap_ready;

assign brmerge_i_fu_223_p2 = (p_not_i_reg_292 | p_Result_s_fu_209_p3);

assign grp_fu_160_p0 = p_Result_53_reg_322;

assign grp_log_generic_fu_142_ap_start = grp_log_generic_fu_142_ap_start_reg;

assign icmp_fu_193_p2 = ((tmp_fu_183_p4 == 31'd0) ? 1'b1 : 1'b0);

assign not_or_cond_i_fu_238_p2 = (or_cond_i_fu_228_p2 ^ 1'd1);

assign opacity_fu_283_p1 = p_Result_53_reg_322;

assign or_cond_i_fu_228_p2 = (tmp_i_reg_287 & brmerge_i_fu_223_p2);

assign output_V_bypass_din = p_bypass_reg_317_pp0_iter33_reg;

assign output_V_bypass_write = output_V_q_V1_update;

assign output_V_dense_din = p_dense_reg_312_pp0_iter33_reg;

assign output_V_dense_write = output_V_q_V1_update;

assign output_V_limit_din = ap_phi_reg_pp0_iter34_p_limit_reg_130;

assign output_V_limit_write = output_V_q_V1_update;

assign output_V_q_V1_status = (output_V_q_V_full_n & output_V_limit_full_n & output_V_dense_full_n & output_V_bypass_full_n);

assign output_V_q_V_din = tmp_V_reg_307_pp0_iter33_reg;

assign output_V_q_V_write = output_V_q_V1_update;

assign p_Result_i_0_i_111_fu_244_p2 = (p_Result_i_0_i_fu_233_p2 | not_or_cond_i_fu_238_p2);

assign p_Result_i_0_i_fu_233_p2 = (tmp_i_110_reg_297 & p_Result_s_fu_209_p3);

assign p_Result_i_i_fu_199_p4 = {{input_V_V_dout[511:510]}};

assign p_Result_s_fu_209_p3 = input_V_V_dout[32'd186];

assign p_bypass_fu_262_p2 = (tmp_182_i_fu_256_p2 | icmp_reg_302);

assign p_dense_fu_250_p2 = (tmp_181_i_fu_217_p2 & p_Result_i_0_i_111_fu_244_p2);

assign p_not_i_fu_171_p2 = ((mode_dout != 32'd4) ? 1'b1 : 1'b0);

assign phitmp_i_fu_277_p2 = ((p_Result_i_i_fu_199_p4 == 2'd3) ? 1'b1 : 1'b0);

assign start_out = real_start;

assign tmp_181_i_fu_217_p2 = ((p_Result_i_i_fu_199_p4 == 2'd0) ? 1'b1 : 1'b0);

assign tmp_182_i_fu_256_p2 = ((p_Result_i_i_fu_199_p4 != 2'd0) ? 1'b1 : 1'b0);

assign tmp_fu_183_p4 = {{mode_dout[31:1]}};

assign tmp_i_110_fu_177_p2 = ((mode_dout == 32'd5) ? 1'b1 : 1'b0);

assign tmp_i_fu_165_p2 = ((mode_dout != 32'd2) ? 1'b1 : 1'b0);

endmodule //prepare_frames
