// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module render_lane_3u_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_pp0_stage0 = 11'd4;
parameter    ap_ST_fsm_state6 = 11'd8;
parameter    ap_ST_fsm_state7 = 11'd16;
parameter    ap_ST_fsm_pp1_stage0 = 11'd32;
parameter    ap_ST_fsm_state11 = 11'd64;
parameter    ap_ST_fsm_pp2_stage0 = 11'd128;
parameter    ap_ST_fsm_state31 = 11'd256;
parameter    ap_ST_fsm_state32 = 11'd512;
parameter    ap_ST_fsm_state33 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [127:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_V_V_read;
reg output_V_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    input_V_V_blk_n;
wire    ap_CS_fsm_state2;
reg    output_V_V_blk_n;
reg    ap_enable_reg_pp2_iter18;
wire    ap_block_pp2_stage0;
reg   [0:0] tmp_58_reg_1137;
reg   [0:0] tmp_58_reg_1137_pp2_iter17_reg;
reg   [4:0] k3_reg_528;
reg   [4:0] k5_reg_540;
reg   [6:0] p1_reg_551;
wire   [15:0] rr_q0;
reg   [15:0] reg_613;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_59_reg_1011;
wire    ap_block_state12_pp2_stage0_iter0;
wire    ap_block_state13_pp2_stage0_iter1;
wire    ap_block_state14_pp2_stage0_iter2;
wire    ap_block_state15_pp2_stage0_iter3;
wire    ap_block_state16_pp2_stage0_iter4;
wire    ap_block_state17_pp2_stage0_iter5;
wire    ap_block_state18_pp2_stage0_iter6;
wire    ap_block_state19_pp2_stage0_iter7;
wire    ap_block_state20_pp2_stage0_iter8;
wire    ap_block_state21_pp2_stage0_iter9;
wire    ap_block_state22_pp2_stage0_iter10;
wire    ap_block_state23_pp2_stage0_iter11;
wire    ap_block_state24_pp2_stage0_iter12;
wire    ap_block_state25_pp2_stage0_iter13;
wire    ap_block_state26_pp2_stage0_iter14;
wire    ap_block_state27_pp2_stage0_iter15;
wire    ap_block_state28_pp2_stage0_iter16;
wire    ap_block_state29_pp2_stage0_iter17;
reg    ap_block_state30_pp2_stage0_iter18;
reg    ap_block_pp2_stage0_11001;
reg    ap_enable_reg_pp2_iter7;
reg   [0:0] tmp_58_reg_1137_pp2_iter6_reg;
wire   [15:0] gg_q0;
reg   [15:0] reg_619;
wire   [15:0] bb_q0;
reg   [15:0] reg_625;
wire   [15:0] tt_q0;
reg   [15:0] reg_631;
reg   [15:0] reg_631_pp2_iter2_reg;
reg   [15:0] reg_631_pp2_iter3_reg;
reg   [15:0] reg_631_pp2_iter4_reg;
reg   [15:0] reg_631_pp2_iter5_reg;
reg   [15:0] reg_631_pp2_iter6_reg;
reg   [15:0] reg_631_pp2_iter7_reg;
reg   [15:0] reg_631_pp2_iter8_reg;
reg   [15:0] reg_631_pp2_iter9_reg;
reg   [15:0] reg_631_pp2_iter10_reg;
reg   [15:0] reg_631_pp2_iter11_reg;
reg   [15:0] reg_631_pp2_iter12_reg;
reg   [15:0] reg_631_pp2_iter13_reg;
reg   [15:0] reg_631_pp2_iter14_reg;
reg   [15:0] reg_631_pp2_iter15_reg;
reg   [15:0] reg_631_pp2_iter16_reg;
reg   [15:0] reg_631_pp2_iter17_reg;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire   [31:0] last_q0;
reg   [31:0] reg_639;
reg    ap_enable_reg_pp2_iter17;
reg   [0:0] tmp_58_reg_1137_pp2_iter16_reg;
reg   [511:0] tmp_V_1_reg_973;
wire   [0:0] tmp_fu_659_p2;
wire   [0:0] tmp_s_fu_665_p2;
wire   [0:0] tmp_54_fu_671_p2;
wire   [5:0] tmp_56_fu_687_p3;
reg   [5:0] tmp_56_reg_990;
wire   [15:0] br_fu_705_p1;
reg   [15:0] br_reg_996;
wire   [15:0] bg_fu_719_p1;
reg   [15:0] bg_reg_1001;
wire   [15:0] bc_fu_733_p1;
reg   [15:0] bc_reg_1006;
wire   [0:0] tmp_59_fu_737_p2;
reg   [0:0] tmp_59_reg_1011_pp0_iter1_reg;
wire   [4:0] k_fu_743_p2;
reg   [4:0] k_reg_1015;
reg    ap_enable_reg_pp0_iter0;
wire   [63:0] tmp_67_fu_768_p1;
reg   [63:0] tmp_67_reg_1050;
wire   [0:0] tmp_68_fu_773_p2;
reg   [0:0] tmp_68_reg_1059;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state8_pp1_stage0_iter0;
wire    ap_block_state9_pp1_stage0_iter1;
wire    ap_block_state10_pp1_stage0_iter2;
wire    ap_block_pp1_stage0_11001;
reg   [0:0] tmp_68_reg_1059_pp1_iter1_reg;
wire   [4:0] k_1_fu_779_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [5:0] p_4_fu_789_p2;
reg   [5:0] p_4_reg_1068;
wire   [15:0] mr_q0;
reg   [15:0] mr_load_reg_1103;
reg    ap_enable_reg_pp1_iter1;
wire   [63:0] tmp_70_fu_804_p1;
reg   [63:0] tmp_70_reg_1108;
wire   [15:0] mg_q0;
reg   [15:0] mg_load_reg_1117;
wire   [15:0] mb_q0;
reg   [15:0] mb_load_reg_1122;
wire   [15:0] mt_q0;
reg   [15:0] mt_load_reg_1127;
wire   [31:0] ml_q0;
reg   [31:0] ml_load_reg_1132;
wire   [0:0] tmp_58_fu_808_p2;
reg   [0:0] tmp_58_reg_1137_pp2_iter1_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter2_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter3_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter4_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter5_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter7_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter8_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter9_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter10_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter11_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter12_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter13_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter14_reg;
reg   [0:0] tmp_58_reg_1137_pp2_iter15_reg;
wire   [6:0] p_2_fu_814_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [1:0] tmp_72_fu_820_p1;
reg   [1:0] tmp_72_reg_1146;
reg   [1:0] tmp_72_reg_1146_pp2_iter1_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter2_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter3_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter4_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter5_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter6_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter7_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter8_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter9_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter10_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter11_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter12_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter13_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter14_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter15_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter16_reg;
reg   [1:0] tmp_72_reg_1146_pp2_iter17_reg;
reg   [0:0] tmp_73_reg_1151;
reg   [0:0] tmp_73_reg_1151_pp2_iter1_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter2_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter3_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter4_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter5_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter6_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter7_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter8_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter9_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter10_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter11_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter12_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter13_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter14_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter15_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter16_reg;
reg   [0:0] tmp_73_reg_1151_pp2_iter17_reg;
wire   [63:0] tmp_60_fu_832_p1;
reg   [63:0] tmp_60_reg_1156;
reg   [63:0] tmp_60_reg_1156_pp2_iter1_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter2_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter3_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter4_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter5_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter6_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter7_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter8_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter9_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter10_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter11_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter12_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter13_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter14_reg;
reg   [63:0] tmp_60_reg_1156_pp2_iter15_reg;
reg   [0:0] tmp_74_reg_1169;
reg   [0:0] tmp_74_reg_1169_pp2_iter1_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter2_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter3_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter4_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter5_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter6_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter7_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter8_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter9_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter10_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter11_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter12_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter13_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter14_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter15_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter16_reg;
reg   [0:0] tmp_74_reg_1169_pp2_iter17_reg;
reg   [1:0] tmp_8_reg_1174;
reg   [1:0] tmp_8_reg_1174_pp2_iter1_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter2_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter3_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter4_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter5_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter6_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter7_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter8_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter9_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter10_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter11_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter12_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter13_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter14_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter15_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter16_reg;
reg   [1:0] tmp_8_reg_1174_pp2_iter17_reg;
wire   [15:0] grp_fu_598_p2;
reg   [15:0] tmp_61_reg_1194;
wire   [15:0] grp_fu_602_p2;
reg   [15:0] tmp_62_reg_1199;
wire   [15:0] grp_fu_606_p2;
reg   [15:0] tmp_63_reg_1204;
wire   [15:0] grp_fu_586_p2;
reg   [15:0] v_assign_reg_1214;
wire   [15:0] grp_fu_590_p2;
reg   [15:0] v_assign_1_reg_1219;
wire   [15:0] grp_fu_594_p2;
reg   [15:0] v_assign_2_reg_1224;
wire   [6:0] p_1_fu_950_p2;
wire    ap_CS_fsm_state32;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter2;
wire    ap_CS_fsm_state7;
wire    grp_evaluate_mini_3u_s_fu_573_ap_ready;
wire    grp_evaluate_mini_3u_s_fu_573_ap_done;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state8;
reg    ap_enable_reg_pp1_iter2;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state12;
reg    ap_enable_reg_pp2_iter2;
reg    ap_enable_reg_pp2_iter3;
reg    ap_enable_reg_pp2_iter4;
reg    ap_enable_reg_pp2_iter5;
reg    ap_enable_reg_pp2_iter6;
reg    ap_enable_reg_pp2_iter8;
reg    ap_enable_reg_pp2_iter9;
reg    ap_enable_reg_pp2_iter10;
reg    ap_enable_reg_pp2_iter11;
reg    ap_enable_reg_pp2_iter12;
reg    ap_enable_reg_pp2_iter13;
reg    ap_enable_reg_pp2_iter14;
reg    ap_enable_reg_pp2_iter15;
reg    ap_enable_reg_pp2_iter16;
reg   [5:0] rr_address0;
reg    rr_ce0;
reg   [5:0] rr_address1;
reg    rr_ce1;
reg    rr_we1;
reg   [15:0] rr_d1;
reg   [5:0] gg_address0;
reg    gg_ce0;
reg   [5:0] gg_address1;
reg    gg_ce1;
reg    gg_we1;
reg   [15:0] gg_d1;
reg   [5:0] bb_address0;
reg    bb_ce0;
reg   [5:0] bb_address1;
reg    bb_ce1;
reg    bb_we1;
reg   [15:0] bb_d1;
reg   [5:0] tt_address0;
reg    tt_ce0;
reg   [5:0] tt_address1;
reg    tt_ce1;
reg    tt_we1;
reg   [15:0] tt_d1;
reg   [5:0] last_address0;
reg    last_ce0;
reg    last_we0;
reg   [31:0] last_d0;
reg   [5:0] stopped_address0;
reg    stopped_ce0;
reg    stopped_we0;
reg   [0:0] stopped_d0;
wire   [0:0] stopped_q0;
reg   [3:0] mr_address0;
reg    mr_ce0;
reg    mr_we0;
reg    mr_ce1;
reg    mr_we1;
reg   [3:0] mg_address0;
reg    mg_ce0;
reg    mg_we0;
reg    mg_ce1;
reg    mg_we1;
reg   [3:0] mb_address0;
reg    mb_ce0;
reg    mb_we0;
reg    mb_ce1;
reg    mb_we1;
reg   [3:0] mt_address0;
reg    mt_ce0;
reg    mt_we0;
reg    mt_ce1;
reg    mt_we1;
reg   [3:0] ml_address0;
reg    ml_ce0;
reg    ml_we0;
reg   [31:0] ml_d0;
reg   [3:0] ms_address0;
reg    ms_ce0;
reg    ms_we0;
wire   [0:0] ms_q0;
reg    ms_ce1;
reg    ms_we1;
wire    grp_evaluate_mini_3u_s_fu_573_ap_start;
wire    grp_evaluate_mini_3u_s_fu_573_ap_idle;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_rr_address0;
wire    grp_evaluate_mini_3u_s_fu_573_rr_ce0;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_rr_address1;
wire    grp_evaluate_mini_3u_s_fu_573_rr_ce1;
wire    grp_evaluate_mini_3u_s_fu_573_rr_we1;
wire   [15:0] grp_evaluate_mini_3u_s_fu_573_rr_d1;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_gg_address0;
wire    grp_evaluate_mini_3u_s_fu_573_gg_ce0;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_gg_address1;
wire    grp_evaluate_mini_3u_s_fu_573_gg_ce1;
wire    grp_evaluate_mini_3u_s_fu_573_gg_we1;
wire   [15:0] grp_evaluate_mini_3u_s_fu_573_gg_d1;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_bb_address0;
wire    grp_evaluate_mini_3u_s_fu_573_bb_ce0;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_bb_address1;
wire    grp_evaluate_mini_3u_s_fu_573_bb_ce1;
wire    grp_evaluate_mini_3u_s_fu_573_bb_we1;
wire   [15:0] grp_evaluate_mini_3u_s_fu_573_bb_d1;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_tt_address0;
wire    grp_evaluate_mini_3u_s_fu_573_tt_ce0;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_tt_address1;
wire    grp_evaluate_mini_3u_s_fu_573_tt_ce1;
wire    grp_evaluate_mini_3u_s_fu_573_tt_we1;
wire   [15:0] grp_evaluate_mini_3u_s_fu_573_tt_d1;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_last_address0;
wire    grp_evaluate_mini_3u_s_fu_573_last_ce0;
wire    grp_evaluate_mini_3u_s_fu_573_last_we0;
wire   [31:0] grp_evaluate_mini_3u_s_fu_573_last_d0;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_stopped_address0;
wire    grp_evaluate_mini_3u_s_fu_573_stopped_ce0;
wire   [3:0] grp_evaluate_mini_3u_s_fu_573_stopped_address1;
wire    grp_evaluate_mini_3u_s_fu_573_stopped_ce1;
wire    grp_evaluate_mini_3u_s_fu_573_stopped_we1;
wire   [0:0] grp_evaluate_mini_3u_s_fu_573_stopped_d1;
reg   [4:0] ap_phi_mux_k3_phi_fu_532_p4;
wire    ap_block_pp0_stage0;
reg   [6:0] p_reg_562;
wire   [0:0] tmp_55_fu_944_p2;
reg    grp_evaluate_mini_3u_s_fu_573_ap_start_reg;
wire    ap_CS_fsm_state6;
wire   [63:0] tmp_66_fu_758_p1;
wire   [63:0] tmp_69_fu_794_p1;
wire    ap_block_pp1_stage0;
wire   [63:0] tmp_57_fu_956_p1;
reg    ap_block_pp2_stage0_01001;
reg   [31:0] tile_fu_134;
reg    ap_block_state1;
wire   [31:0] tile_1_fu_933_p2;
wire    ap_CS_fsm_state31;
wire   [1:0] p_Result_i_fu_649_p4;
wire   [1:0] tmp_5_fu_677_p4;
wire   [15:0] p_Result_s_fu_695_p4;
wire   [15:0] p_Result_25_fu_709_p4;
wire   [15:0] p_Result_26_fu_723_p4;
wire   [5:0] k3_cast_fu_749_p1;
wire   [5:0] p_3_fu_753_p2;
wire   [5:0] k5_cast_fu_785_p1;
wire   [7:0] y_fu_868_p5;
wire   [7:0] tmp_64_fu_878_p2;
wire   [23:0] tmp_75_fu_884_p1;
wire   [3:0] tmp_65_fu_888_p4;
wire   [31:0] x_fu_898_p6;
wire   [31:0] val_assign_s_fu_910_p2;
wire   [15:0] p_Val2_8_fu_864_p1;
wire   [15:0] p_Val2_7_fu_861_p1;
wire   [15:0] p_Val2_6_fu_858_p1;
wire   [15:0] p_Val2_5_fu_855_p1;
reg    grp_fu_586_ce;
reg    grp_fu_590_ce;
reg    grp_fu_594_ce;
reg    grp_fu_598_ce;
reg    grp_fu_602_ce;
reg    grp_fu_606_ce;
reg   [10:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 ap_enable_reg_pp2_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter7 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter3 = 1'b0;
#0 ap_enable_reg_pp2_iter4 = 1'b0;
#0 ap_enable_reg_pp2_iter5 = 1'b0;
#0 ap_enable_reg_pp2_iter6 = 1'b0;
#0 ap_enable_reg_pp2_iter8 = 1'b0;
#0 ap_enable_reg_pp2_iter9 = 1'b0;
#0 ap_enable_reg_pp2_iter10 = 1'b0;
#0 ap_enable_reg_pp2_iter11 = 1'b0;
#0 ap_enable_reg_pp2_iter12 = 1'b0;
#0 ap_enable_reg_pp2_iter13 = 1'b0;
#0 ap_enable_reg_pp2_iter14 = 1'b0;
#0 ap_enable_reg_pp2_iter15 = 1'b0;
#0 ap_enable_reg_pp2_iter16 = 1'b0;
#0 grp_evaluate_mini_3u_s_fu_573_ap_start_reg = 1'b0;
end

render_lane_0u_s_rr #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
rr_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rr_address0),
    .ce0(rr_ce0),
    .q0(rr_q0),
    .address1(rr_address1),
    .ce1(rr_ce1),
    .we1(rr_we1),
    .d1(rr_d1)
);

render_lane_0u_s_rr #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
gg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(gg_address0),
    .ce0(gg_ce0),
    .q0(gg_q0),
    .address1(gg_address1),
    .ce1(gg_ce1),
    .we1(gg_we1),
    .d1(gg_d1)
);

render_lane_0u_s_rr #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
bb_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bb_address0),
    .ce0(bb_ce0),
    .q0(bb_q0),
    .address1(bb_address1),
    .ce1(bb_ce1),
    .we1(bb_we1),
    .d1(bb_d1)
);

render_lane_0u_s_rr #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
tt_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tt_address0),
    .ce0(tt_ce0),
    .q0(tt_q0),
    .address1(tt_address1),
    .ce1(tt_ce1),
    .we1(tt_we1),
    .d1(tt_d1)
);

render_lane_0u_s_Ffa #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
last_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(last_address0),
    .ce0(last_ce0),
    .we0(last_we0),
    .d0(last_d0),
    .q0(last_q0)
);

render_lane_0u_s_Gfk #(
    .DataWidth( 1 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
stopped_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(stopped_address0),
    .ce0(stopped_ce0),
    .we0(stopped_we0),
    .d0(stopped_d0),
    .q0(stopped_q0)
);

render_lane_0u_s_mr #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
mr_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mr_address0),
    .ce0(mr_ce0),
    .we0(mr_we0),
    .d0(reg_613),
    .q0(mr_q0),
    .address1(grp_evaluate_mini_3u_s_fu_573_rr_address1),
    .ce1(mr_ce1),
    .we1(mr_we1),
    .d1(grp_evaluate_mini_3u_s_fu_573_rr_d1)
);

render_lane_0u_s_mr #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
mg_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mg_address0),
    .ce0(mg_ce0),
    .we0(mg_we0),
    .d0(reg_619),
    .q0(mg_q0),
    .address1(grp_evaluate_mini_3u_s_fu_573_gg_address1),
    .ce1(mg_ce1),
    .we1(mg_we1),
    .d1(grp_evaluate_mini_3u_s_fu_573_gg_d1)
);

render_lane_0u_s_mr #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
mb_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mb_address0),
    .ce0(mb_ce0),
    .we0(mb_we0),
    .d0(reg_625),
    .q0(mb_q0),
    .address1(grp_evaluate_mini_3u_s_fu_573_bb_address1),
    .ce1(mb_ce1),
    .we1(mb_we1),
    .d1(grp_evaluate_mini_3u_s_fu_573_bb_d1)
);

render_lane_0u_s_mr #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
mt_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mt_address0),
    .ce0(mt_ce0),
    .we0(mt_we0),
    .d0(reg_631),
    .q0(mt_q0),
    .address1(grp_evaluate_mini_3u_s_fu_573_tt_address1),
    .ce1(mt_ce1),
    .we1(mt_we1),
    .d1(grp_evaluate_mini_3u_s_fu_573_tt_d1)
);

render_lane_0u_s_ml #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
ml_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ml_address0),
    .ce0(ml_ce0),
    .we0(ml_we0),
    .d0(ml_d0),
    .q0(ml_q0)
);

render_lane_0u_s_ms #(
    .DataWidth( 1 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
ms_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ms_address0),
    .ce0(ms_ce0),
    .we0(ms_we0),
    .d0(stopped_q0),
    .q0(ms_q0),
    .address1(grp_evaluate_mini_3u_s_fu_573_stopped_address1),
    .ce1(ms_ce1),
    .we1(ms_we1),
    .d1(grp_evaluate_mini_3u_s_fu_573_stopped_d1)
);

evaluate_mini_3u_s grp_evaluate_mini_3u_s_fu_573(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_evaluate_mini_3u_s_fu_573_ap_start),
    .ap_done(grp_evaluate_mini_3u_s_fu_573_ap_done),
    .ap_idle(grp_evaluate_mini_3u_s_fu_573_ap_idle),
    .ap_ready(grp_evaluate_mini_3u_s_fu_573_ap_ready),
    .q_V(tmp_V_1_reg_973),
    .rr_address0(grp_evaluate_mini_3u_s_fu_573_rr_address0),
    .rr_ce0(grp_evaluate_mini_3u_s_fu_573_rr_ce0),
    .rr_q0(mr_q0),
    .rr_address1(grp_evaluate_mini_3u_s_fu_573_rr_address1),
    .rr_ce1(grp_evaluate_mini_3u_s_fu_573_rr_ce1),
    .rr_we1(grp_evaluate_mini_3u_s_fu_573_rr_we1),
    .rr_d1(grp_evaluate_mini_3u_s_fu_573_rr_d1),
    .gg_address0(grp_evaluate_mini_3u_s_fu_573_gg_address0),
    .gg_ce0(grp_evaluate_mini_3u_s_fu_573_gg_ce0),
    .gg_q0(mg_q0),
    .gg_address1(grp_evaluate_mini_3u_s_fu_573_gg_address1),
    .gg_ce1(grp_evaluate_mini_3u_s_fu_573_gg_ce1),
    .gg_we1(grp_evaluate_mini_3u_s_fu_573_gg_we1),
    .gg_d1(grp_evaluate_mini_3u_s_fu_573_gg_d1),
    .bb_address0(grp_evaluate_mini_3u_s_fu_573_bb_address0),
    .bb_ce0(grp_evaluate_mini_3u_s_fu_573_bb_ce0),
    .bb_q0(mb_q0),
    .bb_address1(grp_evaluate_mini_3u_s_fu_573_bb_address1),
    .bb_ce1(grp_evaluate_mini_3u_s_fu_573_bb_ce1),
    .bb_we1(grp_evaluate_mini_3u_s_fu_573_bb_we1),
    .bb_d1(grp_evaluate_mini_3u_s_fu_573_bb_d1),
    .tt_address0(grp_evaluate_mini_3u_s_fu_573_tt_address0),
    .tt_ce0(grp_evaluate_mini_3u_s_fu_573_tt_ce0),
    .tt_q0(mt_q0),
    .tt_address1(grp_evaluate_mini_3u_s_fu_573_tt_address1),
    .tt_ce1(grp_evaluate_mini_3u_s_fu_573_tt_ce1),
    .tt_we1(grp_evaluate_mini_3u_s_fu_573_tt_we1),
    .tt_d1(grp_evaluate_mini_3u_s_fu_573_tt_d1),
    .last_address0(grp_evaluate_mini_3u_s_fu_573_last_address0),
    .last_ce0(grp_evaluate_mini_3u_s_fu_573_last_ce0),
    .last_we0(grp_evaluate_mini_3u_s_fu_573_last_we0),
    .last_d0(grp_evaluate_mini_3u_s_fu_573_last_d0),
    .stopped_address0(grp_evaluate_mini_3u_s_fu_573_stopped_address0),
    .stopped_ce0(grp_evaluate_mini_3u_s_fu_573_stopped_ce0),
    .stopped_q0(ms_q0),
    .stopped_address1(grp_evaluate_mini_3u_s_fu_573_stopped_address1),
    .stopped_ce1(grp_evaluate_mini_3u_s_fu_573_stopped_ce1),
    .stopped_we1(grp_evaluate_mini_3u_s_fu_573_stopped_we1),
    .stopped_d1(grp_evaluate_mini_3u_s_fu_573_stopped_d1)
);

flicker_render_pixdS #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
flicker_render_pixdS_U314(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_613),
    .din1(tmp_61_reg_1194),
    .ce(grp_fu_586_ce),
    .dout(grp_fu_586_p2)
);

flicker_render_pixdS #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
flicker_render_pixdS_U315(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_619),
    .din1(tmp_62_reg_1199),
    .ce(grp_fu_590_ce),
    .dout(grp_fu_590_p2)
);

flicker_render_pixdS #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
flicker_render_pixdS_U316(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_625),
    .din1(tmp_63_reg_1204),
    .ce(grp_fu_594_ce),
    .dout(grp_fu_594_p2)
);

flicker_render_piudo #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
flicker_render_piudo_U317(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(br_reg_996),
    .din1(reg_631),
    .ce(grp_fu_598_ce),
    .dout(grp_fu_598_p2)
);

flicker_render_piudo #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
flicker_render_piudo_U318(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bg_reg_1001),
    .din1(reg_631),
    .ce(grp_fu_602_ce),
    .dout(grp_fu_602_p2)
);

flicker_render_piudo #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
flicker_render_piudo_U319(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(bc_reg_1006),
    .din1(reg_631),
    .ce(grp_fu_606_ce),
    .dout(grp_fu_606_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_659_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((tmp_54_fu_671_p2 == 1'd0) & (tmp_s_fu_665_p2 == 1'd0) & (tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((tmp_54_fu_671_p2 == 1'd0) & (tmp_s_fu_665_p2 == 1'd0) & (tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state8) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((grp_evaluate_mini_3u_s_fu_573_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state8)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state8);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if (((grp_evaluate_mini_3u_s_fu_573_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state12) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((tmp_s_fu_665_p2 == 1'd0) & (tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (tmp_54_fu_671_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp2_exit_iter0_state12)) begin
                ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state12);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter10 <= ap_enable_reg_pp2_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter11 <= ap_enable_reg_pp2_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter12 <= ap_enable_reg_pp2_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter13 <= ap_enable_reg_pp2_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter14 <= ap_enable_reg_pp2_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter15 <= ap_enable_reg_pp2_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter16 <= ap_enable_reg_pp2_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter17 <= ap_enable_reg_pp2_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter18 <= ap_enable_reg_pp2_iter17;
        end else if (((tmp_s_fu_665_p2 == 1'd0) & (tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (tmp_54_fu_671_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp2_iter18 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter3 <= ap_enable_reg_pp2_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter4 <= ap_enable_reg_pp2_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter5 <= ap_enable_reg_pp2_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter6 <= ap_enable_reg_pp2_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter7 <= ap_enable_reg_pp2_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter8 <= ap_enable_reg_pp2_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter9 <= ap_enable_reg_pp2_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_evaluate_mini_3u_s_fu_573_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_evaluate_mini_3u_s_fu_573_ap_start_reg <= 1'b1;
        end else if ((grp_evaluate_mini_3u_s_fu_573_ap_ready == 1'b1)) begin
            grp_evaluate_mini_3u_s_fu_573_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k3_reg_528 <= k_reg_1015;
    end else if (((tmp_54_fu_671_p2 == 1'd0) & (tmp_s_fu_665_p2 == 1'd0) & (tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        k3_reg_528 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_68_fu_773_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        k5_reg_540 <= k_1_fu_779_p2;
    end else if (((grp_evaluate_mini_3u_s_fu_573_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        k5_reg_540 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_58_fu_808_p2 == 1'd0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        p1_reg_551 <= p_2_fu_814_p2;
    end else if (((tmp_s_fu_665_p2 == 1'd0) & (tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (tmp_54_fu_671_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p1_reg_551 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (tmp_s_fu_665_p2 == 1'd1))) begin
        p_reg_562 <= 7'd0;
    end else if (((tmp_55_fu_944_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32))) begin
        p_reg_562 <= p_1_fu_950_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        tile_fu_134 <= tile_1_fu_933_p2;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tile_fu_134 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_fu_665_p2 == 1'd0) & (tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (tmp_54_fu_671_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        bc_reg_1006 <= bc_fu_733_p1;
        bg_reg_1001 <= bg_fu_719_p1;
        br_reg_996 <= br_fu_705_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        k_reg_1015 <= k_fu_743_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_68_reg_1059 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        mb_load_reg_1122 <= mb_q0;
        mg_load_reg_1117 <= mg_q0;
        ml_load_reg_1132 <= ml_q0;
        mr_load_reg_1103 <= mr_q0;
        mt_load_reg_1127 <= mt_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_68_fu_773_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        p_4_reg_1068 <= p_4_fu_789_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_58_reg_1137_pp2_iter6_reg == 1'd0) & (ap_enable_reg_pp2_iter7 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        reg_613 <= rr_q0;
        reg_619 <= gg_q0;
        reg_625 <= bb_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_58_reg_1137 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        reg_631 <= tt_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp2_stage0_11001)) begin
        reg_631_pp2_iter10_reg <= reg_631_pp2_iter9_reg;
        reg_631_pp2_iter11_reg <= reg_631_pp2_iter10_reg;
        reg_631_pp2_iter12_reg <= reg_631_pp2_iter11_reg;
        reg_631_pp2_iter13_reg <= reg_631_pp2_iter12_reg;
        reg_631_pp2_iter14_reg <= reg_631_pp2_iter13_reg;
        reg_631_pp2_iter15_reg <= reg_631_pp2_iter14_reg;
        reg_631_pp2_iter16_reg <= reg_631_pp2_iter15_reg;
        reg_631_pp2_iter17_reg <= reg_631_pp2_iter16_reg;
        reg_631_pp2_iter2_reg <= reg_631;
        reg_631_pp2_iter3_reg <= reg_631_pp2_iter2_reg;
        reg_631_pp2_iter4_reg <= reg_631_pp2_iter3_reg;
        reg_631_pp2_iter5_reg <= reg_631_pp2_iter4_reg;
        reg_631_pp2_iter6_reg <= reg_631_pp2_iter5_reg;
        reg_631_pp2_iter7_reg <= reg_631_pp2_iter6_reg;
        reg_631_pp2_iter8_reg <= reg_631_pp2_iter7_reg;
        reg_631_pp2_iter9_reg <= reg_631_pp2_iter8_reg;
        tmp_58_reg_1137_pp2_iter10_reg <= tmp_58_reg_1137_pp2_iter9_reg;
        tmp_58_reg_1137_pp2_iter11_reg <= tmp_58_reg_1137_pp2_iter10_reg;
        tmp_58_reg_1137_pp2_iter12_reg <= tmp_58_reg_1137_pp2_iter11_reg;
        tmp_58_reg_1137_pp2_iter13_reg <= tmp_58_reg_1137_pp2_iter12_reg;
        tmp_58_reg_1137_pp2_iter14_reg <= tmp_58_reg_1137_pp2_iter13_reg;
        tmp_58_reg_1137_pp2_iter15_reg <= tmp_58_reg_1137_pp2_iter14_reg;
        tmp_58_reg_1137_pp2_iter16_reg <= tmp_58_reg_1137_pp2_iter15_reg;
        tmp_58_reg_1137_pp2_iter17_reg <= tmp_58_reg_1137_pp2_iter16_reg;
        tmp_58_reg_1137_pp2_iter2_reg <= tmp_58_reg_1137_pp2_iter1_reg;
        tmp_58_reg_1137_pp2_iter3_reg <= tmp_58_reg_1137_pp2_iter2_reg;
        tmp_58_reg_1137_pp2_iter4_reg <= tmp_58_reg_1137_pp2_iter3_reg;
        tmp_58_reg_1137_pp2_iter5_reg <= tmp_58_reg_1137_pp2_iter4_reg;
        tmp_58_reg_1137_pp2_iter6_reg <= tmp_58_reg_1137_pp2_iter5_reg;
        tmp_58_reg_1137_pp2_iter7_reg <= tmp_58_reg_1137_pp2_iter6_reg;
        tmp_58_reg_1137_pp2_iter8_reg <= tmp_58_reg_1137_pp2_iter7_reg;
        tmp_58_reg_1137_pp2_iter9_reg <= tmp_58_reg_1137_pp2_iter8_reg;
        tmp_60_reg_1156_pp2_iter10_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter9_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter11_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter10_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter12_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter11_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter13_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter12_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter14_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter13_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter15_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter14_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter2_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter1_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter3_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter2_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter4_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter3_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter5_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter4_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter6_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter5_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter7_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter6_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter8_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter7_reg[6 : 0];
        tmp_60_reg_1156_pp2_iter9_reg[6 : 0] <= tmp_60_reg_1156_pp2_iter8_reg[6 : 0];
        tmp_72_reg_1146_pp2_iter10_reg <= tmp_72_reg_1146_pp2_iter9_reg;
        tmp_72_reg_1146_pp2_iter11_reg <= tmp_72_reg_1146_pp2_iter10_reg;
        tmp_72_reg_1146_pp2_iter12_reg <= tmp_72_reg_1146_pp2_iter11_reg;
        tmp_72_reg_1146_pp2_iter13_reg <= tmp_72_reg_1146_pp2_iter12_reg;
        tmp_72_reg_1146_pp2_iter14_reg <= tmp_72_reg_1146_pp2_iter13_reg;
        tmp_72_reg_1146_pp2_iter15_reg <= tmp_72_reg_1146_pp2_iter14_reg;
        tmp_72_reg_1146_pp2_iter16_reg <= tmp_72_reg_1146_pp2_iter15_reg;
        tmp_72_reg_1146_pp2_iter17_reg <= tmp_72_reg_1146_pp2_iter16_reg;
        tmp_72_reg_1146_pp2_iter2_reg <= tmp_72_reg_1146_pp2_iter1_reg;
        tmp_72_reg_1146_pp2_iter3_reg <= tmp_72_reg_1146_pp2_iter2_reg;
        tmp_72_reg_1146_pp2_iter4_reg <= tmp_72_reg_1146_pp2_iter3_reg;
        tmp_72_reg_1146_pp2_iter5_reg <= tmp_72_reg_1146_pp2_iter4_reg;
        tmp_72_reg_1146_pp2_iter6_reg <= tmp_72_reg_1146_pp2_iter5_reg;
        tmp_72_reg_1146_pp2_iter7_reg <= tmp_72_reg_1146_pp2_iter6_reg;
        tmp_72_reg_1146_pp2_iter8_reg <= tmp_72_reg_1146_pp2_iter7_reg;
        tmp_72_reg_1146_pp2_iter9_reg <= tmp_72_reg_1146_pp2_iter8_reg;
        tmp_73_reg_1151_pp2_iter10_reg <= tmp_73_reg_1151_pp2_iter9_reg;
        tmp_73_reg_1151_pp2_iter11_reg <= tmp_73_reg_1151_pp2_iter10_reg;
        tmp_73_reg_1151_pp2_iter12_reg <= tmp_73_reg_1151_pp2_iter11_reg;
        tmp_73_reg_1151_pp2_iter13_reg <= tmp_73_reg_1151_pp2_iter12_reg;
        tmp_73_reg_1151_pp2_iter14_reg <= tmp_73_reg_1151_pp2_iter13_reg;
        tmp_73_reg_1151_pp2_iter15_reg <= tmp_73_reg_1151_pp2_iter14_reg;
        tmp_73_reg_1151_pp2_iter16_reg <= tmp_73_reg_1151_pp2_iter15_reg;
        tmp_73_reg_1151_pp2_iter17_reg <= tmp_73_reg_1151_pp2_iter16_reg;
        tmp_73_reg_1151_pp2_iter2_reg <= tmp_73_reg_1151_pp2_iter1_reg;
        tmp_73_reg_1151_pp2_iter3_reg <= tmp_73_reg_1151_pp2_iter2_reg;
        tmp_73_reg_1151_pp2_iter4_reg <= tmp_73_reg_1151_pp2_iter3_reg;
        tmp_73_reg_1151_pp2_iter5_reg <= tmp_73_reg_1151_pp2_iter4_reg;
        tmp_73_reg_1151_pp2_iter6_reg <= tmp_73_reg_1151_pp2_iter5_reg;
        tmp_73_reg_1151_pp2_iter7_reg <= tmp_73_reg_1151_pp2_iter6_reg;
        tmp_73_reg_1151_pp2_iter8_reg <= tmp_73_reg_1151_pp2_iter7_reg;
        tmp_73_reg_1151_pp2_iter9_reg <= tmp_73_reg_1151_pp2_iter8_reg;
        tmp_74_reg_1169_pp2_iter10_reg <= tmp_74_reg_1169_pp2_iter9_reg;
        tmp_74_reg_1169_pp2_iter11_reg <= tmp_74_reg_1169_pp2_iter10_reg;
        tmp_74_reg_1169_pp2_iter12_reg <= tmp_74_reg_1169_pp2_iter11_reg;
        tmp_74_reg_1169_pp2_iter13_reg <= tmp_74_reg_1169_pp2_iter12_reg;
        tmp_74_reg_1169_pp2_iter14_reg <= tmp_74_reg_1169_pp2_iter13_reg;
        tmp_74_reg_1169_pp2_iter15_reg <= tmp_74_reg_1169_pp2_iter14_reg;
        tmp_74_reg_1169_pp2_iter16_reg <= tmp_74_reg_1169_pp2_iter15_reg;
        tmp_74_reg_1169_pp2_iter17_reg <= tmp_74_reg_1169_pp2_iter16_reg;
        tmp_74_reg_1169_pp2_iter2_reg <= tmp_74_reg_1169_pp2_iter1_reg;
        tmp_74_reg_1169_pp2_iter3_reg <= tmp_74_reg_1169_pp2_iter2_reg;
        tmp_74_reg_1169_pp2_iter4_reg <= tmp_74_reg_1169_pp2_iter3_reg;
        tmp_74_reg_1169_pp2_iter5_reg <= tmp_74_reg_1169_pp2_iter4_reg;
        tmp_74_reg_1169_pp2_iter6_reg <= tmp_74_reg_1169_pp2_iter5_reg;
        tmp_74_reg_1169_pp2_iter7_reg <= tmp_74_reg_1169_pp2_iter6_reg;
        tmp_74_reg_1169_pp2_iter8_reg <= tmp_74_reg_1169_pp2_iter7_reg;
        tmp_74_reg_1169_pp2_iter9_reg <= tmp_74_reg_1169_pp2_iter8_reg;
        tmp_8_reg_1174_pp2_iter10_reg <= tmp_8_reg_1174_pp2_iter9_reg;
        tmp_8_reg_1174_pp2_iter11_reg <= tmp_8_reg_1174_pp2_iter10_reg;
        tmp_8_reg_1174_pp2_iter12_reg <= tmp_8_reg_1174_pp2_iter11_reg;
        tmp_8_reg_1174_pp2_iter13_reg <= tmp_8_reg_1174_pp2_iter12_reg;
        tmp_8_reg_1174_pp2_iter14_reg <= tmp_8_reg_1174_pp2_iter13_reg;
        tmp_8_reg_1174_pp2_iter15_reg <= tmp_8_reg_1174_pp2_iter14_reg;
        tmp_8_reg_1174_pp2_iter16_reg <= tmp_8_reg_1174_pp2_iter15_reg;
        tmp_8_reg_1174_pp2_iter17_reg <= tmp_8_reg_1174_pp2_iter16_reg;
        tmp_8_reg_1174_pp2_iter2_reg <= tmp_8_reg_1174_pp2_iter1_reg;
        tmp_8_reg_1174_pp2_iter3_reg <= tmp_8_reg_1174_pp2_iter2_reg;
        tmp_8_reg_1174_pp2_iter4_reg <= tmp_8_reg_1174_pp2_iter3_reg;
        tmp_8_reg_1174_pp2_iter5_reg <= tmp_8_reg_1174_pp2_iter4_reg;
        tmp_8_reg_1174_pp2_iter6_reg <= tmp_8_reg_1174_pp2_iter5_reg;
        tmp_8_reg_1174_pp2_iter7_reg <= tmp_8_reg_1174_pp2_iter6_reg;
        tmp_8_reg_1174_pp2_iter8_reg <= tmp_8_reg_1174_pp2_iter7_reg;
        tmp_8_reg_1174_pp2_iter9_reg <= tmp_8_reg_1174_pp2_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_58_reg_1137_pp2_iter16_reg == 1'd0) & (ap_enable_reg_pp2_iter17 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        reg_639 <= last_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_54_fu_671_p2 == 1'd0) & (tmp_s_fu_665_p2 == 1'd0) & (tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_56_reg_990[5 : 4] <= tmp_56_fu_687_p3[5 : 4];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_58_reg_1137 <= tmp_58_fu_808_p2;
        tmp_58_reg_1137_pp2_iter1_reg <= tmp_58_reg_1137;
        tmp_60_reg_1156_pp2_iter1_reg[6 : 0] <= tmp_60_reg_1156[6 : 0];
        tmp_72_reg_1146_pp2_iter1_reg <= tmp_72_reg_1146;
        tmp_73_reg_1151_pp2_iter1_reg <= tmp_73_reg_1151;
        tmp_74_reg_1169_pp2_iter1_reg <= tmp_74_reg_1169;
        tmp_8_reg_1174_pp2_iter1_reg <= tmp_8_reg_1174;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_59_reg_1011 <= tmp_59_fu_737_p2;
        tmp_59_reg_1011_pp0_iter1_reg <= tmp_59_reg_1011;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_58_fu_808_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_60_reg_1156[6 : 0] <= tmp_60_fu_832_p1[6 : 0];
        tmp_72_reg_1146 <= tmp_72_fu_820_p1;
        tmp_73_reg_1151 <= p1_reg_551[32'd4];
        tmp_74_reg_1169 <= p1_reg_551[32'd5];
        tmp_8_reg_1174 <= {{p1_reg_551[3:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_58_reg_1137_pp2_iter6_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        tmp_61_reg_1194 <= grp_fu_598_p2;
        tmp_62_reg_1199 <= grp_fu_602_p2;
        tmp_63_reg_1204 <= grp_fu_606_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_67_reg_1050[4 : 0] <= tmp_67_fu_768_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        tmp_68_reg_1059 <= tmp_68_fu_773_p2;
        tmp_68_reg_1059_pp1_iter1_reg <= tmp_68_reg_1059;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_68_reg_1059 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        tmp_70_reg_1108[5 : 0] <= tmp_70_fu_804_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_V_1_reg_973 <= input_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_58_reg_1137_pp2_iter16_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        v_assign_1_reg_1219 <= grp_fu_590_p2;
        v_assign_2_reg_1224 <= grp_fu_594_p2;
        v_assign_reg_1214 <= grp_fu_586_p2;
    end
end

always @ (*) begin
    if ((tmp_59_fu_737_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_68_fu_773_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_58_fu_808_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state12 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state12 = 1'b0;
    end
end

always @ (*) begin
    if (((input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_659_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter16 == 1'b0) & (ap_enable_reg_pp2_iter15 == 1'b0) & (ap_enable_reg_pp2_iter14 == 1'b0) & (ap_enable_reg_pp2_iter13 == 1'b0) & (ap_enable_reg_pp2_iter12 == 1'b0) & (ap_enable_reg_pp2_iter11 == 1'b0) & (ap_enable_reg_pp2_iter10 == 1'b0) & (ap_enable_reg_pp2_iter9 == 1'b0) & (ap_enable_reg_pp2_iter8 == 1'b0) & (ap_enable_reg_pp2_iter6 == 1'b0) & (ap_enable_reg_pp2_iter5 == 1'b0) & (ap_enable_reg_pp2_iter4 == 1'b0) & (ap_enable_reg_pp2_iter3 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter18 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter17 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter7 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (tmp_59_reg_1011 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_k3_phi_fu_532_p4 = k_reg_1015;
    end else begin
        ap_phi_mux_k3_phi_fu_532_p4 = k3_reg_528;
    end
end

always @ (*) begin
    if (((input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_659_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter6 == 1'b1))) begin
        bb_address0 = tmp_60_reg_1156_pp2_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        bb_address0 = tmp_66_fu_758_p1;
    end else begin
        bb_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        bb_address1 = tmp_57_fu_956_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        bb_address1 = tmp_70_reg_1108;
    end else begin
        bb_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp2_iter6 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        bb_ce0 = 1'b1;
    end else begin
        bb_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        bb_ce1 = 1'b1;
    end else begin
        bb_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        bb_d1 = 16'd0;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        bb_d1 = mb_load_reg_1122;
    end else begin
        bb_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_55_fu_944_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32)) | ((tmp_68_reg_1059_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        bb_we1 = 1'b1;
    end else begin
        bb_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter6 == 1'b1))) begin
        gg_address0 = tmp_60_reg_1156_pp2_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        gg_address0 = tmp_66_fu_758_p1;
    end else begin
        gg_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        gg_address1 = tmp_57_fu_956_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        gg_address1 = tmp_70_reg_1108;
    end else begin
        gg_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp2_iter6 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        gg_ce0 = 1'b1;
    end else begin
        gg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        gg_ce1 = 1'b1;
    end else begin
        gg_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        gg_d1 = 16'd0;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        gg_d1 = mg_load_reg_1117;
    end else begin
        gg_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_55_fu_944_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32)) | ((tmp_68_reg_1059_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        gg_we1 = 1'b1;
    end else begin
        gg_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        grp_fu_586_ce = 1'b1;
    end else begin
        grp_fu_586_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        grp_fu_590_ce = 1'b1;
    end else begin
        grp_fu_590_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        grp_fu_594_ce = 1'b1;
    end else begin
        grp_fu_594_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        grp_fu_598_ce = 1'b1;
    end else begin
        grp_fu_598_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        grp_fu_602_ce = 1'b1;
    end else begin
        grp_fu_602_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        grp_fu_606_ce = 1'b1;
    end else begin
        grp_fu_606_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        input_V_V_blk_n = input_V_V_empty_n;
    end else begin
        input_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        input_V_V_read = 1'b1;
    end else begin
        input_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        last_address0 = tmp_57_fu_956_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter16 == 1'b1))) begin
        last_address0 = tmp_60_reg_1156_pp2_iter15_reg;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        last_address0 = tmp_70_reg_1108;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        last_address0 = tmp_66_fu_758_p1;
    end else begin
        last_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)) | ((ap_enable_reg_pp2_iter16 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        last_ce0 = 1'b1;
    end else begin
        last_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        last_d0 = 32'd0;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        last_d0 = ml_load_reg_1132;
    end else begin
        last_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_55_fu_944_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32)) | ((tmp_68_reg_1059_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        last_we0 = 1'b1;
    end else begin
        last_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        mb_address0 = tmp_69_fu_794_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mb_address0 = tmp_67_reg_1050;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mb_address0 = grp_evaluate_mini_3u_s_fu_573_bb_address0;
    end else begin
        mb_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        mb_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mb_ce0 = grp_evaluate_mini_3u_s_fu_573_bb_ce0;
    end else begin
        mb_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mb_ce1 = grp_evaluate_mini_3u_s_fu_573_bb_ce1;
    end else begin
        mb_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mb_we0 = 1'b1;
    end else begin
        mb_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mb_we1 = grp_evaluate_mini_3u_s_fu_573_bb_we1;
    end else begin
        mb_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        mg_address0 = tmp_69_fu_794_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mg_address0 = tmp_67_reg_1050;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mg_address0 = grp_evaluate_mini_3u_s_fu_573_gg_address0;
    end else begin
        mg_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        mg_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mg_ce0 = grp_evaluate_mini_3u_s_fu_573_gg_ce0;
    end else begin
        mg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mg_ce1 = grp_evaluate_mini_3u_s_fu_573_gg_ce1;
    end else begin
        mg_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mg_we0 = 1'b1;
    end else begin
        mg_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mg_we1 = grp_evaluate_mini_3u_s_fu_573_gg_we1;
    end else begin
        mg_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ml_address0 = tmp_69_fu_794_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ml_address0 = tmp_67_reg_1050;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        ml_address0 = grp_evaluate_mini_3u_s_fu_573_last_address0;
    end else begin
        ml_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        ml_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        ml_ce0 = grp_evaluate_mini_3u_s_fu_573_last_ce0;
    end else begin
        ml_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ml_d0 = reg_639;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        ml_d0 = grp_evaluate_mini_3u_s_fu_573_last_d0;
    end else begin
        ml_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ml_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        ml_we0 = grp_evaluate_mini_3u_s_fu_573_last_we0;
    end else begin
        ml_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        mr_address0 = tmp_69_fu_794_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mr_address0 = tmp_67_reg_1050;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mr_address0 = grp_evaluate_mini_3u_s_fu_573_rr_address0;
    end else begin
        mr_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        mr_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mr_ce0 = grp_evaluate_mini_3u_s_fu_573_rr_ce0;
    end else begin
        mr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mr_ce1 = grp_evaluate_mini_3u_s_fu_573_rr_ce1;
    end else begin
        mr_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mr_we0 = 1'b1;
    end else begin
        mr_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mr_we1 = grp_evaluate_mini_3u_s_fu_573_rr_we1;
    end else begin
        mr_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ms_address0 = tmp_69_fu_794_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ms_address0 = tmp_67_fu_768_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        ms_address0 = grp_evaluate_mini_3u_s_fu_573_stopped_address0;
    end else begin
        ms_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        ms_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        ms_ce0 = grp_evaluate_mini_3u_s_fu_573_stopped_ce0;
    end else begin
        ms_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ms_ce1 = grp_evaluate_mini_3u_s_fu_573_stopped_ce1;
    end else begin
        ms_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ms_we0 = 1'b1;
    end else begin
        ms_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ms_we1 = grp_evaluate_mini_3u_s_fu_573_stopped_we1;
    end else begin
        ms_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        mt_address0 = tmp_69_fu_794_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mt_address0 = tmp_67_reg_1050;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mt_address0 = grp_evaluate_mini_3u_s_fu_573_tt_address0;
    end else begin
        mt_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        mt_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mt_ce0 = grp_evaluate_mini_3u_s_fu_573_tt_ce0;
    end else begin
        mt_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mt_ce1 = grp_evaluate_mini_3u_s_fu_573_tt_ce1;
    end else begin
        mt_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_59_reg_1011_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mt_we0 = 1'b1;
    end else begin
        mt_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mt_we1 = grp_evaluate_mini_3u_s_fu_573_tt_we1;
    end else begin
        mt_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_58_reg_1137_pp2_iter17_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter18 == 1'b1))) begin
        output_V_V_blk_n = output_V_V_full_n;
    end else begin
        output_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_58_reg_1137_pp2_iter17_reg == 1'd0) & (ap_enable_reg_pp2_iter18 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        output_V_V_write = 1'b1;
    end else begin
        output_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter6 == 1'b1))) begin
        rr_address0 = tmp_60_reg_1156_pp2_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        rr_address0 = tmp_66_fu_758_p1;
    end else begin
        rr_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        rr_address1 = tmp_57_fu_956_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        rr_address1 = tmp_70_reg_1108;
    end else begin
        rr_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp2_iter6 == 1'b1) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        rr_ce0 = 1'b1;
    end else begin
        rr_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        rr_ce1 = 1'b1;
    end else begin
        rr_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        rr_d1 = 16'd0;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        rr_d1 = mr_load_reg_1103;
    end else begin
        rr_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_55_fu_944_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32)) | ((tmp_68_reg_1059_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        rr_we1 = 1'b1;
    end else begin
        rr_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        stopped_address0 = tmp_57_fu_956_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        stopped_address0 = tmp_70_fu_804_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        stopped_address0 = tmp_66_fu_758_p1;
    end else begin
        stopped_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        stopped_ce0 = 1'b1;
    end else begin
        stopped_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        stopped_d0 = 1'd0;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        stopped_d0 = ms_q0;
    end else begin
        stopped_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_55_fu_944_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32)) | ((tmp_68_reg_1059 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        stopped_we0 = 1'b1;
    end else begin
        stopped_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        tt_address0 = tmp_60_fu_832_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        tt_address0 = tmp_66_fu_758_p1;
    end else begin
        tt_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        tt_address1 = tmp_57_fu_956_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        tt_address1 = tmp_70_reg_1108;
    end else begin
        tt_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        tt_ce0 = 1'b1;
    end else begin
        tt_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        tt_ce1 = 1'b1;
    end else begin
        tt_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        tt_d1 = 16'd15360;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        tt_d1 = mt_load_reg_1127;
    end else begin
        tt_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_55_fu_944_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32)) | ((tmp_68_reg_1059_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
        tt_we1 = 1'b1;
    end else begin
        tt_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_659_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2) & (tmp_s_fu_665_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else if (((tmp_s_fu_665_p2 == 1'd0) & (tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (tmp_54_fu_671_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((tmp_54_fu_671_p2 == 1'd0) & (tmp_s_fu_665_p2 == 1'd0) & (tmp_fu_659_p2 == 1'd0) & (input_V_V_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (tmp_59_fu_737_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (tmp_59_fu_737_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_evaluate_mini_3u_s_fu_573_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (tmp_68_fu_773_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (tmp_68_fu_773_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((1'b0 == ap_block_pp2_stage0_subdone) & (tmp_58_fu_808_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (ap_enable_reg_pp2_iter1 == 1'b0)) & ~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter18 == 1'b1) & (ap_enable_reg_pp2_iter17 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if ((((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter18 == 1'b1) & (ap_enable_reg_pp2_iter17 == 1'b0)) | ((1'b0 == ap_block_pp2_stage0_subdone) & (tmp_58_fu_808_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (ap_enable_reg_pp2_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state32 : begin
            if (((tmp_55_fu_944_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_01001 = ((tmp_58_reg_1137_pp2_iter17_reg == 1'd0) & (output_V_V_full_n == 1'b0) & (ap_enable_reg_pp2_iter18 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_11001 = ((tmp_58_reg_1137_pp2_iter17_reg == 1'd0) & (output_V_V_full_n == 1'b0) & (ap_enable_reg_pp2_iter18 == 1'b1));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = ((tmp_58_reg_1137_pp2_iter17_reg == 1'd0) & (output_V_V_full_n == 1'b0) & (ap_enable_reg_pp2_iter18 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp2_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp2_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp2_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp2_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp2_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp2_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp2_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp2_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp2_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp2_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp2_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp2_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp2_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp2_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp2_stage0_iter17 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state30_pp2_stage0_iter18 = ((tmp_58_reg_1137_pp2_iter17_reg == 1'd0) & (output_V_V_full_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign bc_fu_733_p1 = p_Result_26_fu_723_p4;

assign bg_fu_719_p1 = p_Result_25_fu_709_p4;

assign br_fu_705_p1 = p_Result_s_fu_695_p4;

assign grp_evaluate_mini_3u_s_fu_573_ap_start = grp_evaluate_mini_3u_s_fu_573_ap_start_reg;

assign k3_cast_fu_749_p1 = ap_phi_mux_k3_phi_fu_532_p4;

assign k5_cast_fu_785_p1 = k5_reg_540;

assign k_1_fu_779_p2 = (k5_reg_540 + 5'd1);

assign k_fu_743_p2 = (ap_phi_mux_k3_phi_fu_532_p4 + 5'd1);

assign output_V_V_din = {{{{{{val_assign_s_fu_910_p2}, {reg_639}}, {p_Val2_8_fu_864_p1}}, {p_Val2_7_fu_861_p1}}, {p_Val2_6_fu_858_p1}}, {p_Val2_5_fu_855_p1}};

assign p_1_fu_950_p2 = (p_reg_562 + 7'd1);

assign p_2_fu_814_p2 = (p1_reg_551 + 7'd1);

assign p_3_fu_753_p2 = (tmp_56_reg_990 + k3_cast_fu_749_p1);

assign p_4_fu_789_p2 = (tmp_56_reg_990 + k5_cast_fu_785_p1);

assign p_Result_25_fu_709_p4 = {{input_V_V_dout[111:96]}};

assign p_Result_26_fu_723_p4 = {{input_V_V_dout[127:112]}};

assign p_Result_i_fu_649_p4 = {{input_V_V_dout[511:510]}};

assign p_Result_s_fu_695_p4 = {{input_V_V_dout[95:80]}};

assign p_Val2_5_fu_855_p1 = v_assign_reg_1214;

assign p_Val2_6_fu_858_p1 = v_assign_1_reg_1219;

assign p_Val2_7_fu_861_p1 = v_assign_2_reg_1224;

assign p_Val2_8_fu_864_p1 = reg_631_pp2_iter17_reg;

assign tile_1_fu_933_p2 = (tile_fu_134 + 32'd1);

assign tmp_54_fu_671_p2 = ((p_Result_i_fu_649_p4 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_55_fu_944_p2 = ((p_reg_562 == 7'd64) ? 1'b1 : 1'b0);

assign tmp_56_fu_687_p3 = {{tmp_5_fu_677_p4}, {4'd0}};

assign tmp_57_fu_956_p1 = p_reg_562;

assign tmp_58_fu_808_p2 = ((p1_reg_551 == 7'd64) ? 1'b1 : 1'b0);

assign tmp_59_fu_737_p2 = ((ap_phi_mux_k3_phi_fu_532_p4 == 5'd16) ? 1'b1 : 1'b0);

assign tmp_5_fu_677_p4 = {{input_V_V_dout[229:228]}};

assign tmp_60_fu_832_p1 = p1_reg_551;

assign tmp_64_fu_878_p2 = (y_fu_868_p5 | 8'd64);

assign tmp_65_fu_888_p4 = {{tmp_64_fu_878_p2[7:4]}};

assign tmp_66_fu_758_p1 = p_3_fu_753_p2;

assign tmp_67_fu_768_p1 = k3_reg_528;

assign tmp_68_fu_773_p2 = ((k5_reg_540 == 5'd16) ? 1'b1 : 1'b0);

assign tmp_69_fu_794_p1 = k5_reg_540;

assign tmp_70_fu_804_p1 = p_4_reg_1068;

assign tmp_72_fu_820_p1 = p1_reg_551[1:0];

assign tmp_75_fu_884_p1 = tile_fu_134[23:0];

assign tmp_fu_659_p2 = ((p_Result_i_fu_649_p4 == 2'd3) ? 1'b1 : 1'b0);

assign tmp_s_fu_665_p2 = ((p_Result_i_fu_649_p4 == 2'd1) ? 1'b1 : 1'b0);

assign val_assign_s_fu_910_p2 = (x_fu_898_p6 | 32'd4);

assign x_fu_898_p6 = {{{{{tmp_75_fu_884_p1}, {tmp_65_fu_888_p4}}, {tmp_73_reg_1151_pp2_iter17_reg}}, {1'd0}}, {tmp_72_reg_1146_pp2_iter17_reg}};

assign y_fu_868_p5 = {{{{tmp_74_reg_1169_pp2_iter17_reg}, {1'd0}}, {tmp_8_reg_1174_pp2_iter17_reg}}, {4'd0}};

always @ (posedge ap_clk) begin
    tmp_56_reg_990[3:0] <= 4'b0000;
    tmp_67_reg_1050[63:5] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    tmp_70_reg_1108[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter1_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter2_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter3_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter4_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter5_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter6_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter7_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter8_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter9_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter10_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter11_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter12_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter13_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter14_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
    tmp_60_reg_1156_pp2_iter15_reg[63:7] <= 57'b000000000000000000000000000000000000000000000000000000000;
end

endmodule //render_lane_3u_s
