// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dispatch (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        a_V_V_din,
        a_V_V_full_n,
        a_V_V_write,
        b_V_V_din,
        b_V_V_full_n,
        b_V_V_write,
        c_V_V_din,
        c_V_V_full_n,
        c_V_V_write,
        d_V_V_din,
        d_V_V_full_n,
        d_V_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [511:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [231:0] a_V_V_din;
input   a_V_V_full_n;
output   a_V_V_write;
output  [231:0] b_V_V_din;
input   b_V_V_full_n;
output   b_V_V_write;
output  [231:0] c_V_V_din;
input   c_V_V_full_n;
output   c_V_V_write;
output  [231:0] d_V_V_din;
input   d_V_V_full_n;
output   d_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg input_V_V_read;
reg a_V_V_write;
reg b_V_V_write;
reg c_V_V_write;
reg d_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    input_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    a_V_V_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] or_cond_reg_228;
reg    b_V_V_blk_n;
reg   [0:0] or_cond1_reg_232;
reg    c_V_V_blk_n;
reg   [0:0] or_cond2_reg_236;
reg    d_V_V_blk_n;
reg   [0:0] or_cond3_reg_240;
wire   [1:0] p_Result_i_fu_102_p4;
reg   [1:0] p_Result_i_reg_218;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [229:0] tmp_299_fu_112_p1;
reg   [229:0] tmp_299_reg_223;
wire   [0:0] or_cond_fu_136_p2;
wire   [0:0] or_cond1_fu_156_p2;
wire   [0:0] or_cond2_fu_176_p2;
wire   [0:0] or_cond3_fu_196_p2;
wire   [0:0] phitmp_fu_202_p2;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
wire   [231:0] p_Result_s_fu_208_p3;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_300_fu_122_p3;
wire   [0:0] tmp_fu_116_p2;
wire   [0:0] rev_fu_130_p2;
wire   [0:0] tmp_301_fu_142_p3;
wire   [0:0] rev4_fu_150_p2;
wire   [0:0] tmp_302_fu_162_p3;
wire   [0:0] rev7_fu_170_p2;
wire   [0:0] tmp_303_fu_182_p3;
wire   [0:0] rev1_fu_190_p2;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (phitmp_fu_202_p2 == 1'd1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        or_cond1_reg_232 <= or_cond1_fu_156_p2;
        or_cond2_reg_236 <= or_cond2_fu_176_p2;
        or_cond3_reg_240 <= or_cond3_fu_196_p2;
        or_cond_reg_228 <= or_cond_fu_136_p2;
        p_Result_i_reg_218 <= {{input_V_V_dout[511:510]}};
        tmp_299_reg_223 <= tmp_299_fu_112_p1;
    end
end

always @ (*) begin
    if (((or_cond_reg_228 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_V_V_blk_n = a_V_V_full_n;
    end else begin
        a_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_reg_228 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        a_V_V_write = 1'b1;
    end else begin
        a_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond1_reg_232 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_V_V_blk_n = b_V_V_full_n;
    end else begin
        b_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond1_reg_232 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_V_V_write = 1'b1;
    end else begin
        b_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond2_reg_236 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_V_V_blk_n = c_V_V_full_n;
    end else begin
        c_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond2_reg_236 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        c_V_V_write = 1'b1;
    end else begin
        c_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond3_reg_240 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_V_V_blk_n = d_V_V_full_n;
    end else begin
        d_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond3_reg_240 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        d_V_V_write = 1'b1;
    end else begin
        d_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_V_V_blk_n = input_V_V_empty_n;
    end else begin
        input_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_V_V_read = 1'b1;
    end else begin
        input_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_V_V_din = p_Result_s_fu_208_p3;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((or_cond3_reg_240 == 1'd0) & (d_V_V_full_n == 1'b0)) | ((or_cond2_reg_236 == 1'd0) & (c_V_V_full_n == 1'b0)) | ((or_cond1_reg_232 == 1'd0) & (b_V_V_full_n == 1'b0)) | ((or_cond_reg_228 == 1'd0) & (1'b0 == a_V_V_full_n)))) | ((input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((or_cond3_reg_240 == 1'd0) & (d_V_V_full_n == 1'b0)) | ((or_cond2_reg_236 == 1'd0) & (c_V_V_full_n == 1'b0)) | ((or_cond1_reg_232 == 1'd0) & (b_V_V_full_n == 1'b0)) | ((or_cond_reg_228 == 1'd0) & (1'b0 == a_V_V_full_n)))) | ((input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((or_cond3_reg_240 == 1'd0) & (d_V_V_full_n == 1'b0)) | ((or_cond2_reg_236 == 1'd0) & (c_V_V_full_n == 1'b0)) | ((or_cond1_reg_232 == 1'd0) & (b_V_V_full_n == 1'b0)) | ((or_cond_reg_228 == 1'd0) & (1'b0 == a_V_V_full_n)))) | ((input_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (input_V_V_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((or_cond3_reg_240 == 1'd0) & (d_V_V_full_n == 1'b0)) | ((or_cond2_reg_236 == 1'd0) & (c_V_V_full_n == 1'b0)) | ((or_cond1_reg_232 == 1'd0) & (b_V_V_full_n == 1'b0)) | ((or_cond_reg_228 == 1'd0) & (1'b0 == a_V_V_full_n)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign b_V_V_din = p_Result_s_fu_208_p3;

assign c_V_V_din = p_Result_s_fu_208_p3;

assign d_V_V_din = p_Result_s_fu_208_p3;

assign or_cond1_fu_156_p2 = (tmp_fu_116_p2 & rev4_fu_150_p2);

assign or_cond2_fu_176_p2 = (tmp_fu_116_p2 & rev7_fu_170_p2);

assign or_cond3_fu_196_p2 = (tmp_fu_116_p2 & rev1_fu_190_p2);

assign or_cond_fu_136_p2 = (tmp_fu_116_p2 & rev_fu_130_p2);

assign p_Result_i_fu_102_p4 = {{input_V_V_dout[511:510]}};

assign p_Result_s_fu_208_p3 = {{p_Result_i_reg_218}, {tmp_299_reg_223}};

assign phitmp_fu_202_p2 = ((p_Result_i_fu_102_p4 == 2'd3) ? 1'b1 : 1'b0);

assign rev1_fu_190_p2 = (tmp_303_fu_182_p3 ^ 1'd1);

assign rev4_fu_150_p2 = (tmp_301_fu_142_p3 ^ 1'd1);

assign rev7_fu_170_p2 = (tmp_302_fu_162_p3 ^ 1'd1);

assign rev_fu_130_p2 = (tmp_300_fu_122_p3 ^ 1'd1);

assign start_out = real_start;

assign tmp_299_fu_112_p1 = input_V_V_dout[229:0];

assign tmp_300_fu_122_p3 = input_V_V_dout[32'd224];

assign tmp_301_fu_142_p3 = input_V_V_dout[32'd225];

assign tmp_302_fu_162_p3 = input_V_V_dout[32'd226];

assign tmp_303_fu_182_p3 = input_V_V_dout[32'd227];

assign tmp_fu_116_p2 = ((p_Result_i_fu_102_p4 == 2'd0) ? 1'b1 : 1'b0);

endmodule //dispatch
