// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="flicker_render_pipeline,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z030ffg676-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.292000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=203,HLS_SYN_DSP=244,HLS_SYN_FF=65163,HLS_SYN_LUT=33947,HLS_VERSION=2018_3}" *)

module flicker_render_pipeline (
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write,
        tiles,
        mode,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [511:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [511:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;
input  [31:0] tiles;
input  [31:0] mode;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    split_U0_ap_start;
wire    split_U0_start_full_n;
wire    split_U0_start_out;
wire    split_U0_start_write;
wire    split_U0_input_V_V_read;
wire   [511:0] split_U0_output_V_V_din;
wire    split_U0_output_V_V_write;
wire   [31:0] split_U0_tiles_out_din;
wire    split_U0_tiles_out_write;
wire   [31:0] split_U0_mode_out_din;
wire    split_U0_mode_out_write;
wire    split_U0_ap_done;
wire    split_U0_ap_ready;
wire    split_U0_ap_idle;
wire    split_U0_ap_continue;
wire    framed_ctu_U0_ap_start;
wire    framed_ctu_U0_start_out;
wire    framed_ctu_U0_start_write;
wire    framed_ctu_U0_input_V_V_read;
wire   [511:0] framed_ctu_U0_output_V_V_din;
wire    framed_ctu_U0_output_V_V_write;
wire    framed_ctu_U0_mode_read;
wire    framed_ctu_U0_ap_done;
wire    framed_ctu_U0_ap_ready;
wire    framed_ctu_U0_ap_idle;
wire    framed_ctu_U0_ap_continue;
wire    dispatch_U0_ap_start;
wire    dispatch_U0_start_full_n;
wire    dispatch_U0_ap_done;
wire    dispatch_U0_ap_continue;
wire    dispatch_U0_ap_idle;
wire    dispatch_U0_ap_ready;
wire    dispatch_U0_start_out;
wire    dispatch_U0_start_write;
wire    dispatch_U0_input_V_V_read;
wire   [231:0] dispatch_U0_a_V_V_din;
wire    dispatch_U0_a_V_V_write;
wire   [231:0] dispatch_U0_b_V_V_din;
wire    dispatch_U0_b_V_V_write;
wire   [231:0] dispatch_U0_c_V_V_din;
wire    dispatch_U0_c_V_V_write;
wire   [231:0] dispatch_U0_d_V_V_din;
wire    dispatch_U0_d_V_V_write;
wire    render_lane_0u_U0_ap_start;
wire    render_lane_0u_U0_ap_done;
wire    render_lane_0u_U0_ap_continue;
wire    render_lane_0u_U0_ap_idle;
wire    render_lane_0u_U0_ap_ready;
wire    render_lane_0u_U0_input_V_V_read;
wire   [127:0] render_lane_0u_U0_output_V_V_din;
wire    render_lane_0u_U0_output_V_V_write;
wire    render_lane_1u_U0_ap_start;
wire    render_lane_1u_U0_ap_done;
wire    render_lane_1u_U0_ap_continue;
wire    render_lane_1u_U0_ap_idle;
wire    render_lane_1u_U0_ap_ready;
wire    render_lane_1u_U0_input_V_V_read;
wire   [127:0] render_lane_1u_U0_output_V_V_din;
wire    render_lane_1u_U0_output_V_V_write;
wire    render_lane_2u_U0_ap_start;
wire    render_lane_2u_U0_ap_done;
wire    render_lane_2u_U0_ap_continue;
wire    render_lane_2u_U0_ap_idle;
wire    render_lane_2u_U0_ap_ready;
wire    render_lane_2u_U0_input_V_V_read;
wire   [127:0] render_lane_2u_U0_output_V_V_din;
wire    render_lane_2u_U0_output_V_V_write;
wire    render_lane_3u_U0_ap_start;
wire    render_lane_3u_U0_ap_done;
wire    render_lane_3u_U0_ap_continue;
wire    render_lane_3u_U0_ap_idle;
wire    render_lane_3u_U0_ap_ready;
wire    render_lane_3u_U0_input_V_V_read;
wire   [127:0] render_lane_3u_U0_output_V_V_din;
wire    render_lane_3u_U0_output_V_V_write;
wire    gather_U0_ap_start;
wire    gather_U0_ap_done;
wire    gather_U0_ap_continue;
wire    gather_U0_ap_idle;
wire    gather_U0_ap_ready;
wire    gather_U0_a_V_V_read;
wire    gather_U0_b_V_V_read;
wire    gather_U0_c_V_V_read;
wire    gather_U0_d_V_V_read;
wire   [511:0] gather_U0_output_V_V_din;
wire    gather_U0_output_V_V_write;
wire    gather_U0_tiles_read;
wire    ap_sync_continue;
wire    subtiles_V_V_full_n;
wire   [511:0] subtiles_V_V_dout;
wire    subtiles_V_V_empty_n;
wire    tiles_c_full_n;
wire   [31:0] tiles_c_dout;
wire    tiles_c_empty_n;
wire    mode_c_full_n;
wire   [31:0] mode_c_dout;
wire    mode_c_empty_n;
wire    masks_V_V_full_n;
wire   [511:0] masks_V_V_dout;
wire    masks_V_V_empty_n;
wire    q0_V_V_full_n;
wire   [231:0] q0_V_V_dout;
wire    q0_V_V_empty_n;
wire    q1_V_V_full_n;
wire   [231:0] q1_V_V_dout;
wire    q1_V_V_empty_n;
wire    q2_V_V_full_n;
wire   [231:0] q2_V_V_dout;
wire    q2_V_V_empty_n;
wire    q3_V_V_full_n;
wire   [231:0] q3_V_V_dout;
wire    q3_V_V_empty_n;
wire    p0_V_V_full_n;
wire   [127:0] p0_V_V_dout;
wire    p0_V_V_empty_n;
wire    p1_V_V_full_n;
wire   [127:0] p1_V_V_dout;
wire    p1_V_V_empty_n;
wire    p2_V_V_full_n;
wire   [127:0] p2_V_V_dout;
wire    p2_V_V_empty_n;
wire    p3_V_V_full_n;
wire   [127:0] p3_V_V_dout;
wire    p3_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_framed_ctu_U0_din;
wire    start_for_framed_ctu_U0_full_n;
wire   [0:0] start_for_framed_ctu_U0_dout;
wire    start_for_framed_ctu_U0_empty_n;
wire   [0:0] start_for_gather_U0_din;
wire    start_for_gather_U0_full_n;
wire   [0:0] start_for_gather_U0_dout;
wire    start_for_gather_U0_empty_n;
wire   [0:0] start_for_dispatch_U0_din;
wire    start_for_dispatch_U0_full_n;
wire   [0:0] start_for_dispatch_U0_dout;
wire    start_for_dispatch_U0_empty_n;
wire   [0:0] start_for_render_lane_0u_U0_din;
wire    start_for_render_lane_0u_U0_full_n;
wire   [0:0] start_for_render_lane_0u_U0_dout;
wire    start_for_render_lane_0u_U0_empty_n;
wire   [0:0] start_for_render_lane_1u_U0_din;
wire    start_for_render_lane_1u_U0_full_n;
wire   [0:0] start_for_render_lane_1u_U0_dout;
wire    start_for_render_lane_1u_U0_empty_n;
wire   [0:0] start_for_render_lane_2u_U0_din;
wire    start_for_render_lane_2u_U0_full_n;
wire   [0:0] start_for_render_lane_2u_U0_dout;
wire    start_for_render_lane_2u_U0_empty_n;
wire   [0:0] start_for_render_lane_3u_U0_din;
wire    start_for_render_lane_3u_U0_full_n;
wire   [0:0] start_for_render_lane_3u_U0_dout;
wire    start_for_render_lane_3u_U0_empty_n;
wire    render_lane_0u_U0_start_full_n;
wire    render_lane_0u_U0_start_write;
wire    render_lane_1u_U0_start_full_n;
wire    render_lane_1u_U0_start_write;
wire    render_lane_2u_U0_start_full_n;
wire    render_lane_2u_U0_start_write;
wire    render_lane_3u_U0_start_full_n;
wire    render_lane_3u_U0_start_write;
wire    gather_U0_start_full_n;
wire    gather_U0_start_write;

split split_U0(
    .ap_start(split_U0_ap_start),
    .start_full_n(split_U0_start_full_n),
    .start_out(split_U0_start_out),
    .start_write(split_U0_start_write),
    .input_V_V_dout(input_V_V_dout),
    .input_V_V_empty_n(input_V_V_empty_n),
    .input_V_V_read(split_U0_input_V_V_read),
    .output_V_V_din(split_U0_output_V_V_din),
    .output_V_V_full_n(subtiles_V_V_full_n),
    .output_V_V_write(split_U0_output_V_V_write),
    .tiles(tiles),
    .mode(mode),
    .tiles_out_din(split_U0_tiles_out_din),
    .tiles_out_full_n(tiles_c_full_n),
    .tiles_out_write(split_U0_tiles_out_write),
    .mode_out_din(split_U0_mode_out_din),
    .mode_out_full_n(mode_c_full_n),
    .mode_out_write(split_U0_mode_out_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .mode_ap_vld(1'b1),
    .tiles_ap_vld(1'b1),
    .ap_done(split_U0_ap_done),
    .ap_ready(split_U0_ap_ready),
    .ap_idle(split_U0_ap_idle),
    .ap_continue(split_U0_ap_continue)
);

framed_ctu framed_ctu_U0(
    .ap_start(framed_ctu_U0_ap_start),
    .start_full_n(start_for_dispatch_U0_full_n),
    .start_out(framed_ctu_U0_start_out),
    .start_write(framed_ctu_U0_start_write),
    .input_V_V_dout(subtiles_V_V_dout),
    .input_V_V_empty_n(subtiles_V_V_empty_n),
    .input_V_V_read(framed_ctu_U0_input_V_V_read),
    .output_V_V_din(framed_ctu_U0_output_V_V_din),
    .output_V_V_full_n(masks_V_V_full_n),
    .output_V_V_write(framed_ctu_U0_output_V_V_write),
    .mode_dout(mode_c_dout),
    .mode_empty_n(mode_c_empty_n),
    .mode_read(framed_ctu_U0_mode_read),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_done(framed_ctu_U0_ap_done),
    .ap_ready(framed_ctu_U0_ap_ready),
    .ap_idle(framed_ctu_U0_ap_idle),
    .ap_continue(framed_ctu_U0_ap_continue)
);

dispatch dispatch_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dispatch_U0_ap_start),
    .start_full_n(dispatch_U0_start_full_n),
    .ap_done(dispatch_U0_ap_done),
    .ap_continue(dispatch_U0_ap_continue),
    .ap_idle(dispatch_U0_ap_idle),
    .ap_ready(dispatch_U0_ap_ready),
    .start_out(dispatch_U0_start_out),
    .start_write(dispatch_U0_start_write),
    .input_V_V_dout(masks_V_V_dout),
    .input_V_V_empty_n(masks_V_V_empty_n),
    .input_V_V_read(dispatch_U0_input_V_V_read),
    .a_V_V_din(dispatch_U0_a_V_V_din),
    .a_V_V_full_n(q0_V_V_full_n),
    .a_V_V_write(dispatch_U0_a_V_V_write),
    .b_V_V_din(dispatch_U0_b_V_V_din),
    .b_V_V_full_n(q1_V_V_full_n),
    .b_V_V_write(dispatch_U0_b_V_V_write),
    .c_V_V_din(dispatch_U0_c_V_V_din),
    .c_V_V_full_n(q2_V_V_full_n),
    .c_V_V_write(dispatch_U0_c_V_V_write),
    .d_V_V_din(dispatch_U0_d_V_V_din),
    .d_V_V_full_n(q3_V_V_full_n),
    .d_V_V_write(dispatch_U0_d_V_V_write)
);

render_lane_0u_s render_lane_0u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(render_lane_0u_U0_ap_start),
    .ap_done(render_lane_0u_U0_ap_done),
    .ap_continue(render_lane_0u_U0_ap_continue),
    .ap_idle(render_lane_0u_U0_ap_idle),
    .ap_ready(render_lane_0u_U0_ap_ready),
    .input_V_V_dout(q0_V_V_dout),
    .input_V_V_empty_n(q0_V_V_empty_n),
    .input_V_V_read(render_lane_0u_U0_input_V_V_read),
    .output_V_V_din(render_lane_0u_U0_output_V_V_din),
    .output_V_V_full_n(p0_V_V_full_n),
    .output_V_V_write(render_lane_0u_U0_output_V_V_write)
);

render_lane_1u_s render_lane_1u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(render_lane_1u_U0_ap_start),
    .ap_done(render_lane_1u_U0_ap_done),
    .ap_continue(render_lane_1u_U0_ap_continue),
    .ap_idle(render_lane_1u_U0_ap_idle),
    .ap_ready(render_lane_1u_U0_ap_ready),
    .input_V_V_dout(q1_V_V_dout),
    .input_V_V_empty_n(q1_V_V_empty_n),
    .input_V_V_read(render_lane_1u_U0_input_V_V_read),
    .output_V_V_din(render_lane_1u_U0_output_V_V_din),
    .output_V_V_full_n(p1_V_V_full_n),
    .output_V_V_write(render_lane_1u_U0_output_V_V_write)
);

render_lane_2u_s render_lane_2u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(render_lane_2u_U0_ap_start),
    .ap_done(render_lane_2u_U0_ap_done),
    .ap_continue(render_lane_2u_U0_ap_continue),
    .ap_idle(render_lane_2u_U0_ap_idle),
    .ap_ready(render_lane_2u_U0_ap_ready),
    .input_V_V_dout(q2_V_V_dout),
    .input_V_V_empty_n(q2_V_V_empty_n),
    .input_V_V_read(render_lane_2u_U0_input_V_V_read),
    .output_V_V_din(render_lane_2u_U0_output_V_V_din),
    .output_V_V_full_n(p2_V_V_full_n),
    .output_V_V_write(render_lane_2u_U0_output_V_V_write)
);

render_lane_3u_s render_lane_3u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(render_lane_3u_U0_ap_start),
    .ap_done(render_lane_3u_U0_ap_done),
    .ap_continue(render_lane_3u_U0_ap_continue),
    .ap_idle(render_lane_3u_U0_ap_idle),
    .ap_ready(render_lane_3u_U0_ap_ready),
    .input_V_V_dout(q3_V_V_dout),
    .input_V_V_empty_n(q3_V_V_empty_n),
    .input_V_V_read(render_lane_3u_U0_input_V_V_read),
    .output_V_V_din(render_lane_3u_U0_output_V_V_din),
    .output_V_V_full_n(p3_V_V_full_n),
    .output_V_V_write(render_lane_3u_U0_output_V_V_write)
);

gather gather_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(gather_U0_ap_start),
    .ap_done(gather_U0_ap_done),
    .ap_continue(gather_U0_ap_continue),
    .ap_idle(gather_U0_ap_idle),
    .ap_ready(gather_U0_ap_ready),
    .a_V_V_dout(p0_V_V_dout),
    .a_V_V_empty_n(p0_V_V_empty_n),
    .a_V_V_read(gather_U0_a_V_V_read),
    .b_V_V_dout(p1_V_V_dout),
    .b_V_V_empty_n(p1_V_V_empty_n),
    .b_V_V_read(gather_U0_b_V_V_read),
    .c_V_V_dout(p2_V_V_dout),
    .c_V_V_empty_n(p2_V_V_empty_n),
    .c_V_V_read(gather_U0_c_V_V_read),
    .d_V_V_dout(p3_V_V_dout),
    .d_V_V_empty_n(p3_V_V_empty_n),
    .d_V_V_read(gather_U0_d_V_V_read),
    .output_V_V_din(gather_U0_output_V_V_din),
    .output_V_V_full_n(output_V_V_full_n),
    .output_V_V_write(gather_U0_output_V_V_write),
    .tiles_dout(tiles_c_dout),
    .tiles_empty_n(tiles_c_empty_n),
    .tiles_read(gather_U0_tiles_read)
);

fifo_w512_d16_S_x subtiles_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(split_U0_output_V_V_din),
    .if_full_n(subtiles_V_V_full_n),
    .if_write(split_U0_output_V_V_write),
    .if_dout(subtiles_V_V_dout),
    .if_empty_n(subtiles_V_V_empty_n),
    .if_read(framed_ctu_U0_input_V_V_read)
);

fifo_w32_d5_A tiles_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(split_U0_tiles_out_din),
    .if_full_n(tiles_c_full_n),
    .if_write(split_U0_tiles_out_write),
    .if_dout(tiles_c_dout),
    .if_empty_n(tiles_c_empty_n),
    .if_read(gather_U0_tiles_read)
);

fifo_w32_d2_A mode_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(split_U0_mode_out_din),
    .if_full_n(mode_c_full_n),
    .if_write(split_U0_mode_out_write),
    .if_dout(mode_c_dout),
    .if_empty_n(mode_c_empty_n),
    .if_read(framed_ctu_U0_mode_read)
);

fifo_w512_d16_S_x masks_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(framed_ctu_U0_output_V_V_din),
    .if_full_n(masks_V_V_full_n),
    .if_write(framed_ctu_U0_output_V_V_write),
    .if_dout(masks_V_V_dout),
    .if_empty_n(masks_V_V_empty_n),
    .if_read(dispatch_U0_input_V_V_read)
);

fifo_w232_d8_S q0_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dispatch_U0_a_V_V_din),
    .if_full_n(q0_V_V_full_n),
    .if_write(dispatch_U0_a_V_V_write),
    .if_dout(q0_V_V_dout),
    .if_empty_n(q0_V_V_empty_n),
    .if_read(render_lane_0u_U0_input_V_V_read)
);

fifo_w232_d8_S q1_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dispatch_U0_b_V_V_din),
    .if_full_n(q1_V_V_full_n),
    .if_write(dispatch_U0_b_V_V_write),
    .if_dout(q1_V_V_dout),
    .if_empty_n(q1_V_V_empty_n),
    .if_read(render_lane_1u_U0_input_V_V_read)
);

fifo_w232_d8_S q2_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dispatch_U0_c_V_V_din),
    .if_full_n(q2_V_V_full_n),
    .if_write(dispatch_U0_c_V_V_write),
    .if_dout(q2_V_V_dout),
    .if_empty_n(q2_V_V_empty_n),
    .if_read(render_lane_2u_U0_input_V_V_read)
);

fifo_w232_d8_S q3_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dispatch_U0_d_V_V_din),
    .if_full_n(q3_V_V_full_n),
    .if_write(dispatch_U0_d_V_V_write),
    .if_dout(q3_V_V_dout),
    .if_empty_n(q3_V_V_empty_n),
    .if_read(render_lane_3u_U0_input_V_V_read)
);

fifo_w128_d8_S p0_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(render_lane_0u_U0_output_V_V_din),
    .if_full_n(p0_V_V_full_n),
    .if_write(render_lane_0u_U0_output_V_V_write),
    .if_dout(p0_V_V_dout),
    .if_empty_n(p0_V_V_empty_n),
    .if_read(gather_U0_a_V_V_read)
);

fifo_w128_d8_S p1_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(render_lane_1u_U0_output_V_V_din),
    .if_full_n(p1_V_V_full_n),
    .if_write(render_lane_1u_U0_output_V_V_write),
    .if_dout(p1_V_V_dout),
    .if_empty_n(p1_V_V_empty_n),
    .if_read(gather_U0_b_V_V_read)
);

fifo_w128_d8_S p2_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(render_lane_2u_U0_output_V_V_din),
    .if_full_n(p2_V_V_full_n),
    .if_write(render_lane_2u_U0_output_V_V_write),
    .if_dout(p2_V_V_dout),
    .if_empty_n(p2_V_V_empty_n),
    .if_read(gather_U0_c_V_V_read)
);

fifo_w128_d8_S p3_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(render_lane_3u_U0_output_V_V_din),
    .if_full_n(p3_V_V_full_n),
    .if_write(render_lane_3u_U0_output_V_V_write),
    .if_dout(p3_V_V_dout),
    .if_empty_n(p3_V_V_empty_n),
    .if_read(gather_U0_d_V_V_read)
);

start_for_framed_Thq start_for_framed_Thq_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_framed_ctu_U0_din),
    .if_full_n(start_for_framed_ctu_U0_full_n),
    .if_write(split_U0_start_write),
    .if_dout(start_for_framed_ctu_U0_dout),
    .if_empty_n(start_for_framed_ctu_U0_empty_n),
    .if_read(framed_ctu_U0_ap_ready)
);

start_for_gather_U0 start_for_gather_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_gather_U0_din),
    .if_full_n(start_for_gather_U0_full_n),
    .if_write(split_U0_start_write),
    .if_dout(start_for_gather_U0_dout),
    .if_empty_n(start_for_gather_U0_empty_n),
    .if_read(gather_U0_ap_ready)
);

start_for_dispatcUhA start_for_dispatcUhA_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dispatch_U0_din),
    .if_full_n(start_for_dispatch_U0_full_n),
    .if_write(framed_ctu_U0_start_write),
    .if_dout(start_for_dispatch_U0_dout),
    .if_empty_n(start_for_dispatch_U0_empty_n),
    .if_read(dispatch_U0_ap_ready)
);

start_for_render_VhK start_for_render_VhK_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_render_lane_0u_U0_din),
    .if_full_n(start_for_render_lane_0u_U0_full_n),
    .if_write(dispatch_U0_start_write),
    .if_dout(start_for_render_lane_0u_U0_dout),
    .if_empty_n(start_for_render_lane_0u_U0_empty_n),
    .if_read(render_lane_0u_U0_ap_ready)
);

start_for_render_WhU start_for_render_WhU_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_render_lane_1u_U0_din),
    .if_full_n(start_for_render_lane_1u_U0_full_n),
    .if_write(dispatch_U0_start_write),
    .if_dout(start_for_render_lane_1u_U0_dout),
    .if_empty_n(start_for_render_lane_1u_U0_empty_n),
    .if_read(render_lane_1u_U0_ap_ready)
);

start_for_render_Xh4 start_for_render_Xh4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_render_lane_2u_U0_din),
    .if_full_n(start_for_render_lane_2u_U0_full_n),
    .if_write(dispatch_U0_start_write),
    .if_dout(start_for_render_lane_2u_U0_dout),
    .if_empty_n(start_for_render_lane_2u_U0_empty_n),
    .if_read(render_lane_2u_U0_ap_ready)
);

start_for_render_Yie start_for_render_Yie_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_render_lane_3u_U0_din),
    .if_full_n(start_for_render_lane_3u_U0_full_n),
    .if_write(dispatch_U0_start_write),
    .if_dout(start_for_render_lane_3u_U0_dout),
    .if_empty_n(start_for_render_lane_3u_U0_empty_n),
    .if_read(render_lane_3u_U0_ap_ready)
);

assign ap_done = gather_U0_ap_done;

assign ap_idle = (split_U0_ap_idle & render_lane_3u_U0_ap_idle & render_lane_2u_U0_ap_idle & render_lane_1u_U0_ap_idle & render_lane_0u_U0_ap_idle & gather_U0_ap_idle & framed_ctu_U0_ap_idle & dispatch_U0_ap_idle);

assign ap_ready = split_U0_ap_ready;

assign ap_sync_continue = 1'b1;

assign ap_sync_done = gather_U0_ap_done;

assign ap_sync_ready = split_U0_ap_ready;

assign dispatch_U0_ap_continue = 1'b1;

assign dispatch_U0_ap_start = start_for_dispatch_U0_empty_n;

assign dispatch_U0_start_full_n = (start_for_render_lane_3u_U0_full_n & start_for_render_lane_2u_U0_full_n & start_for_render_lane_1u_U0_full_n & start_for_render_lane_0u_U0_full_n);

assign framed_ctu_U0_ap_continue = 1'b1;

assign framed_ctu_U0_ap_start = start_for_framed_ctu_U0_empty_n;

assign gather_U0_ap_continue = 1'b1;

assign gather_U0_ap_start = start_for_gather_U0_empty_n;

assign gather_U0_start_full_n = 1'b1;

assign gather_U0_start_write = 1'b0;

assign input_V_V_read = split_U0_input_V_V_read;

assign output_V_V_din = gather_U0_output_V_V_din;

assign output_V_V_write = gather_U0_output_V_V_write;

assign render_lane_0u_U0_ap_continue = 1'b1;

assign render_lane_0u_U0_ap_start = start_for_render_lane_0u_U0_empty_n;

assign render_lane_0u_U0_start_full_n = 1'b1;

assign render_lane_0u_U0_start_write = 1'b0;

assign render_lane_1u_U0_ap_continue = 1'b1;

assign render_lane_1u_U0_ap_start = start_for_render_lane_1u_U0_empty_n;

assign render_lane_1u_U0_start_full_n = 1'b1;

assign render_lane_1u_U0_start_write = 1'b0;

assign render_lane_2u_U0_ap_continue = 1'b1;

assign render_lane_2u_U0_ap_start = start_for_render_lane_2u_U0_empty_n;

assign render_lane_2u_U0_start_full_n = 1'b1;

assign render_lane_2u_U0_start_write = 1'b0;

assign render_lane_3u_U0_ap_continue = 1'b1;

assign render_lane_3u_U0_ap_start = start_for_render_lane_3u_U0_empty_n;

assign render_lane_3u_U0_start_full_n = 1'b1;

assign render_lane_3u_U0_start_write = 1'b0;

assign split_U0_ap_continue = 1'b1;

assign split_U0_ap_start = ap_start;

assign split_U0_start_full_n = (start_for_gather_U0_full_n & start_for_framed_ctu_U0_full_n);

assign start_for_dispatch_U0_din = 1'b1;

assign start_for_framed_ctu_U0_din = 1'b1;

assign start_for_gather_U0_din = 1'b1;

assign start_for_render_lane_0u_U0_din = 1'b1;

assign start_for_render_lane_1u_U0_din = 1'b1;

assign start_for_render_lane_2u_U0_din = 1'b1;

assign start_for_render_lane_3u_U0_din = 1'b1;

endmodule //flicker_render_pipeline
