// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gather (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        a_V_V_dout,
        a_V_V_empty_n,
        a_V_V_read,
        b_V_V_dout,
        b_V_V_empty_n,
        b_V_V_read,
        c_V_V_dout,
        c_V_V_empty_n,
        c_V_V_read,
        d_V_V_dout,
        d_V_V_empty_n,
        d_V_V_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write,
        tiles_dout,
        tiles_empty_n,
        tiles_read
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_pp0_stage0 = 6'd4;
parameter    ap_ST_fsm_state6 = 6'd8;
parameter    ap_ST_fsm_pp1_stage0 = 6'd16;
parameter    ap_ST_fsm_state10 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] a_V_V_dout;
input   a_V_V_empty_n;
output   a_V_V_read;
input  [127:0] b_V_V_dout;
input   b_V_V_empty_n;
output   b_V_V_read;
input  [127:0] c_V_V_dout;
input   c_V_V_empty_n;
output   c_V_V_read;
input  [127:0] d_V_V_dout;
input   d_V_V_empty_n;
output   d_V_V_read;
output  [511:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;
input  [31:0] tiles_dout;
input   tiles_empty_n;
output   tiles_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg a_V_V_read;
reg b_V_V_read;
reg c_V_V_read;
reg d_V_V_read;
reg output_V_V_write;
reg tiles_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    a_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_i_reg_460;
reg    b_V_V_blk_n;
reg    c_V_V_blk_n;
reg    d_V_V_blk_n;
reg    output_V_V_blk_n;
reg    ap_enable_reg_pp1_iter2;
wire    ap_block_pp1_stage0;
reg   [0:0] tmp_245_i_reg_528;
reg   [0:0] tmp_245_i_reg_528_pp1_iter1_reg;
reg    tiles_blk_n;
reg   [6:0] p_i_reg_250;
reg   [6:0] p_i_reg_250_pp0_iter1_reg;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [383:0] r_V_reg_262;
reg   [8:0] p4_i_reg_274;
reg   [31:0] tiles_read_reg_446;
reg    ap_block_state1;
wire   [0:0] exitcond_i_fu_285_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] t_fu_290_p2;
reg   [31:0] t_reg_455;
wire   [0:0] tmp_i_fu_296_p2;
reg   [0:0] tmp_i_reg_460_pp0_iter1_reg;
wire   [6:0] p_fu_302_p2;
reg   [6:0] p_reg_464;
reg    ap_enable_reg_pp0_iter0;
reg   [127:0] tmp_V_reg_469;
reg   [127:0] tmp_V_14_reg_474;
reg   [127:0] tmp_V_15_reg_479;
reg   [127:0] tmp_V_16_reg_484;
wire   [0:0] tmp_236_i_fu_316_p2;
reg   [0:0] tmp_236_i_reg_489;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state7_pp1_stage0_iter0;
wire    ap_block_state8_pp1_stage0_iter1;
reg    ap_block_state9_pp1_stage0_iter2;
reg    ap_block_pp1_stage0_11001;
reg   [0:0] tmp_236_i_reg_489_pp1_iter1_reg;
wire   [8:0] p_9_fu_322_p2;
reg    ap_enable_reg_pp1_iter0;
reg   [0:0] tmp_217_reg_498;
reg   [0:0] tmp_218_reg_503;
wire   [0:0] tmp_245_i_fu_394_p2;
wire   [511:0] p_Result_s_fu_420_p3;
reg   [511:0] p_Result_s_reg_532;
wire   [383:0] phitmp_cast_i_fu_438_p3;
reg   [383:0] phitmp_cast_i_reg_537;
reg    ap_enable_reg_pp1_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter2;
wire    ap_CS_fsm_state6;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state7;
reg   [5:0] pixels_0_V_address0;
reg    pixels_0_V_ce0;
reg    pixels_0_V_we0;
wire   [127:0] pixels_0_V_q0;
reg   [5:0] pixels_1_V_address0;
reg    pixels_1_V_ce0;
reg    pixels_1_V_we0;
wire   [127:0] pixels_1_V_q0;
reg   [5:0] pixels_2_V_address0;
reg    pixels_2_V_ce0;
reg    pixels_2_V_we0;
wire   [127:0] pixels_2_V_q0;
reg   [5:0] pixels_3_V_address0;
reg    pixels_3_V_ce0;
reg    pixels_3_V_we0;
wire   [127:0] pixels_3_V_q0;
reg   [31:0] t_i_reg_239;
wire    ap_CS_fsm_state10;
reg   [6:0] ap_phi_mux_p_i_phi_fu_254_p4;
reg   [383:0] ap_phi_mux_r_V_phi_fu_266_p4;
wire   [63:0] tmp_i_87_fu_308_p1;
wire   [63:0] tmp_244_i_fu_386_p1;
reg    ap_block_pp1_stage0_01001;
wire   [0:0] tmp_220_fu_356_p3;
wire   [0:0] tmp_219_fu_348_p3;
wire   [1:0] tmp_23_fu_364_p4;
wire   [1:0] tmp_fu_328_p1;
wire   [5:0] tmp_243_i_fu_374_p5;
wire   [1:0] tmp_s_fu_406_p5;
wire   [127:0] tmp_s_fu_406_p6;
wire   [255:0] tmp_24_fu_428_p4;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

gather_pixels_0_V #(
    .DataWidth( 128 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pixels_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pixels_0_V_address0),
    .ce0(pixels_0_V_ce0),
    .we0(pixels_0_V_we0),
    .d0(tmp_V_reg_469),
    .q0(pixels_0_V_q0)
);

gather_pixels_0_V #(
    .DataWidth( 128 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pixels_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pixels_1_V_address0),
    .ce0(pixels_1_V_ce0),
    .we0(pixels_1_V_we0),
    .d0(tmp_V_14_reg_474),
    .q0(pixels_1_V_q0)
);

gather_pixels_0_V #(
    .DataWidth( 128 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pixels_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pixels_2_V_address0),
    .ce0(pixels_2_V_ce0),
    .we0(pixels_2_V_we0),
    .d0(tmp_V_15_reg_479),
    .q0(pixels_2_V_q0)
);

gather_pixels_0_V #(
    .DataWidth( 128 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
pixels_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pixels_3_V_address0),
    .ce0(pixels_3_V_ce0),
    .we0(pixels_3_V_we0),
    .d0(tmp_V_16_reg_484),
    .q0(pixels_3_V_q0)
);

flicker_render_piShg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 128 ),
    .din1_WIDTH( 128 ),
    .din2_WIDTH( 128 ),
    .din3_WIDTH( 128 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 128 ))
flicker_render_piShg_U319(
    .din0(pixels_0_V_q0),
    .din1(pixels_1_V_q0),
    .din2(pixels_2_V_q0),
    .din3(pixels_3_V_q0),
    .din4(tmp_s_fu_406_p5),
    .dout(tmp_s_fu_406_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond_i_fu_285_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond_i_fu_285_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((exitcond_i_fu_285_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state7) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state7)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state7);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p4_i_reg_274 <= 9'd0;
    end else if (((tmp_236_i_fu_316_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p4_i_reg_274 <= p_9_fu_322_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_285_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        p_i_reg_250 <= 7'd0;
    end else if (((tmp_i_reg_460 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_i_reg_250 <= p_reg_464;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        r_V_reg_262 <= 384'd0;
    end else if (((tmp_236_i_reg_489_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        r_V_reg_262 <= phitmp_cast_i_reg_537;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        t_i_reg_239 <= t_reg_455;
    end else if ((~((tiles_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_i_reg_239 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_236_i_reg_489 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_Result_s_reg_532 <= p_Result_s_fu_420_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_i_reg_250_pp0_iter1_reg <= p_i_reg_250;
        tmp_i_reg_460 <= tmp_i_fu_296_p2;
        tmp_i_reg_460_pp0_iter1_reg <= tmp_i_reg_460;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_reg_464 <= p_fu_302_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_236_i_reg_489 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        phitmp_cast_i_reg_537 <= phitmp_cast_i_fu_438_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        t_reg_455 <= t_fu_290_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((tiles_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tiles_read_reg_446 <= tiles_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_236_i_fu_316_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_217_reg_498 <= p4_i_reg_274[32'd2];
        tmp_218_reg_503 <= p4_i_reg_274[32'd6];
        tmp_245_i_reg_528 <= tmp_245_i_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_236_i_reg_489 <= tmp_236_i_fu_316_p2;
        tmp_236_i_reg_489_pp1_iter1_reg <= tmp_236_i_reg_489;
        tmp_245_i_reg_528_pp1_iter1_reg <= tmp_245_i_reg_528;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_reg_460 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_V_14_reg_474 <= b_V_V_dout;
        tmp_V_15_reg_479 <= c_V_V_dout;
        tmp_V_16_reg_484 <= d_V_V_dout;
        tmp_V_reg_469 <= a_V_V_dout;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_V_V_blk_n = a_V_V_empty_n;
    end else begin
        a_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        a_V_V_read = 1'b1;
    end else begin
        a_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_i_fu_296_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_236_i_fu_316_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_fu_285_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_p_i_phi_fu_254_p4 = p_reg_464;
    end else begin
        ap_phi_mux_p_i_phi_fu_254_p4 = p_i_reg_250;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_236_i_reg_489_pp1_iter1_reg == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        ap_phi_mux_r_V_phi_fu_266_p4 = phitmp_cast_i_reg_537;
    end else begin
        ap_phi_mux_r_V_phi_fu_266_p4 = r_V_reg_262;
    end
end

always @ (*) begin
    if (((exitcond_i_fu_285_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_V_V_blk_n = b_V_V_empty_n;
    end else begin
        b_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_V_V_read = 1'b1;
    end else begin
        b_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c_V_V_blk_n = c_V_V_empty_n;
    end else begin
        c_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        c_V_V_read = 1'b1;
    end else begin
        c_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        d_V_V_blk_n = d_V_V_empty_n;
    end else begin
        d_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        d_V_V_read = 1'b1;
    end else begin
        d_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_245_i_reg_528_pp1_iter1_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        output_V_V_blk_n = output_V_V_full_n;
    end else begin
        output_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_245_i_reg_528_pp1_iter1_reg == 1'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_V_V_write = 1'b1;
    end else begin
        output_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        pixels_0_V_address0 = tmp_244_i_fu_386_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pixels_0_V_address0 = tmp_i_87_fu_308_p1;
    end else begin
        pixels_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pixels_0_V_ce0 = 1'b1;
    end else begin
        pixels_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_0_V_we0 = 1'b1;
    end else begin
        pixels_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        pixels_1_V_address0 = tmp_244_i_fu_386_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pixels_1_V_address0 = tmp_i_87_fu_308_p1;
    end else begin
        pixels_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pixels_1_V_ce0 = 1'b1;
    end else begin
        pixels_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_1_V_we0 = 1'b1;
    end else begin
        pixels_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        pixels_2_V_address0 = tmp_244_i_fu_386_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pixels_2_V_address0 = tmp_i_87_fu_308_p1;
    end else begin
        pixels_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pixels_2_V_ce0 = 1'b1;
    end else begin
        pixels_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_2_V_we0 = 1'b1;
    end else begin
        pixels_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        pixels_3_V_address0 = tmp_244_i_fu_386_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        pixels_3_V_address0 = tmp_i_87_fu_308_p1;
    end else begin
        pixels_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        pixels_3_V_ce0 = 1'b1;
    end else begin
        pixels_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_reg_460_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_3_V_we0 = 1'b1;
    end else begin
        pixels_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tiles_blk_n = tiles_empty_n;
    end else begin
        tiles_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((tiles_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tiles_read = 1'b1;
    end else begin
        tiles_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((tiles_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_i_fu_285_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((tmp_i_fu_296_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_i_fu_296_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((tmp_236_i_fu_316_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)) & ~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)) | ((tmp_236_i_fu_316_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_i_reg_460 == 1'd0) & (c_V_V_empty_n == 1'b0)) | ((tmp_i_reg_460 == 1'd0) & (b_V_V_empty_n == 1'b0)) | ((tmp_i_reg_460 == 1'd0) & (1'b0 == a_V_V_empty_n)) | ((tmp_i_reg_460 == 1'd0) & (d_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_i_reg_460 == 1'd0) & (c_V_V_empty_n == 1'b0)) | ((tmp_i_reg_460 == 1'd0) & (b_V_V_empty_n == 1'b0)) | ((tmp_i_reg_460 == 1'd0) & (1'b0 == a_V_V_empty_n)) | ((tmp_i_reg_460 == 1'd0) & (d_V_V_empty_n == 1'b0))));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = ((tmp_245_i_reg_528_pp1_iter1_reg == 1'd1) & (output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((tmp_245_i_reg_528_pp1_iter1_reg == 1'd1) & (output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((tmp_245_i_reg_528_pp1_iter1_reg == 1'd1) & (output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((tiles_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((tmp_i_reg_460 == 1'd0) & (c_V_V_empty_n == 1'b0)) | ((tmp_i_reg_460 == 1'd0) & (b_V_V_empty_n == 1'b0)) | ((tmp_i_reg_460 == 1'd0) & (1'b0 == a_V_V_empty_n)) | ((tmp_i_reg_460 == 1'd0) & (d_V_V_empty_n == 1'b0)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp1_stage0_iter2 = ((tmp_245_i_reg_528_pp1_iter1_reg == 1'd1) & (output_V_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign exitcond_i_fu_285_p2 = ((t_i_reg_239 == tiles_read_reg_446) ? 1'b1 : 1'b0);

assign output_V_V_din = p_Result_s_reg_532;

assign p_9_fu_322_p2 = (p4_i_reg_274 + 9'd1);

assign p_Result_s_fu_420_p3 = {{tmp_s_fu_406_p6}, {ap_phi_mux_r_V_phi_fu_266_p4}};

assign p_fu_302_p2 = (ap_phi_mux_p_i_phi_fu_254_p4 + 7'd1);

assign phitmp_cast_i_fu_438_p3 = {{tmp_s_fu_406_p6}, {tmp_24_fu_428_p4}};

assign t_fu_290_p2 = (t_i_reg_239 + 32'd1);

assign tmp_219_fu_348_p3 = p4_i_reg_274[32'd3];

assign tmp_220_fu_356_p3 = p4_i_reg_274[32'd7];

assign tmp_236_i_fu_316_p2 = ((p4_i_reg_274 == 9'd256) ? 1'b1 : 1'b0);

assign tmp_23_fu_364_p4 = {{p4_i_reg_274[5:4]}};

assign tmp_243_i_fu_374_p5 = {{{{tmp_220_fu_356_p3}, {tmp_219_fu_348_p3}}, {tmp_23_fu_364_p4}}, {tmp_fu_328_p1}};

assign tmp_244_i_fu_386_p1 = tmp_243_i_fu_374_p5;

assign tmp_245_i_fu_394_p2 = ((tmp_fu_328_p1 == 2'd3) ? 1'b1 : 1'b0);

assign tmp_24_fu_428_p4 = {{ap_phi_mux_r_V_phi_fu_266_p4[383:128]}};

assign tmp_fu_328_p1 = p4_i_reg_274[1:0];

assign tmp_i_87_fu_308_p1 = p_i_reg_250_pp0_iter1_reg;

assign tmp_i_fu_296_p2 = ((ap_phi_mux_p_i_phi_fu_254_p4 == 7'd64) ? 1'b1 : 1'b0);

assign tmp_s_fu_406_p5 = {{tmp_218_reg_503}, {tmp_217_reg_498}};

endmodule //gather
