// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gather (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        a_V_V_dout,
        a_V_V_empty_n,
        a_V_V_read,
        b_V_V_dout,
        b_V_V_empty_n,
        b_V_V_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write,
        tiles_dout,
        tiles_empty_n,
        tiles_read
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_pp0_stage0 = 6'd4;
parameter    ap_ST_fsm_state5 = 6'd8;
parameter    ap_ST_fsm_pp1_stage0 = 6'd16;
parameter    ap_ST_fsm_state9 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] a_V_V_dout;
input   a_V_V_empty_n;
output   a_V_V_read;
input  [127:0] b_V_V_dout;
input   b_V_V_empty_n;
output   b_V_V_read;
output  [511:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;
input  [31:0] tiles_dout;
input   tiles_empty_n;
output   tiles_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg a_V_V_read;
reg b_V_V_read;
reg output_V_V_write;
reg tiles_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    a_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] tmp_325_i_fu_318_p2;
wire   [0:0] icmp_fu_296_p2;
wire   [0:0] tmp_nbreadreq_fu_114_p3;
reg    b_V_V_blk_n;
wire   [0:0] icmp1_fu_312_p2;
wire   [0:0] tmp_3_nbreadreq_fu_128_p3;
reg    output_V_V_blk_n;
reg    ap_enable_reg_pp1_iter2;
wire    ap_block_pp1_stage0;
reg   [0:0] tmp_337_i_reg_523;
reg   [0:0] tmp_337_i_reg_523_pp1_iter1_reg;
reg    tiles_blk_n;
reg   [31:0] na_i_reg_198;
reg   [31:0] nb_i_reg_210;
reg   [31:0] na_1_i_reg_222;
reg   [31:0] nb_1_i_reg_237;
reg   [383:0] r_V_reg_252;
reg   [8:0] p_i_reg_264;
reg   [31:0] tiles_read_reg_455;
reg    ap_block_state1;
wire   [0:0] exitcond_i_fu_275_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] t_fu_280_p2;
reg   [31:0] t_reg_464;
reg   [0:0] icmp_reg_469;
reg    ap_predicate_op38_read_state3;
reg    ap_predicate_op45_read_state3;
reg    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp1_reg_473;
reg   [0:0] tmp_325_i_reg_477;
reg   [0:0] tmp_reg_481;
reg   [127:0] tmp_V_reg_485;
reg   [0:0] tmp_3_reg_490;
reg   [127:0] tmp_V_31_reg_494;
wire   [0:0] tmp_326_i_fu_348_p2;
reg   [0:0] tmp_326_i_reg_499;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state6_pp1_stage0_iter0;
wire    ap_block_state7_pp1_stage0_iter1;
reg    ap_block_state8_pp1_stage0_iter2;
reg    ap_block_pp1_stage0_11001;
reg   [0:0] tmp_326_i_reg_499_pp1_iter1_reg;
wire   [8:0] p_fu_354_p2;
reg    ap_enable_reg_pp1_iter0;
reg   [0:0] tmp_259_reg_508;
wire   [0:0] tmp_337_i_fu_416_p2;
wire   [511:0] p_Result_s_fu_429_p3;
reg   [511:0] p_Result_s_reg_527;
wire   [383:0] phitmp_cast_i_fu_447_p3;
reg   [383:0] phitmp_cast_i_reg_532;
reg    ap_enable_reg_pp1_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
wire    ap_CS_fsm_state5;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state6;
reg   [6:0] pixels_0_V_address0;
reg    pixels_0_V_ce0;
reg    pixels_0_V_we0;
wire   [127:0] pixels_0_V_q0;
reg   [6:0] pixels_1_V_address0;
reg    pixels_1_V_ce0;
reg    pixels_1_V_we0;
wire   [127:0] pixels_1_V_q0;
reg   [31:0] t_i_reg_187;
wire    ap_CS_fsm_state9;
reg   [31:0] ap_phi_mux_na_i_phi_fu_202_p4;
reg   [31:0] ap_phi_mux_nb_i_phi_fu_214_p4;
wire   [31:0] na_fu_324_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_na_1_i_reg_222;
wire   [31:0] nb_fu_331_p2;
wire   [31:0] ap_phi_reg_pp0_iter0_nb_1_i_reg_237;
reg   [383:0] ap_phi_mux_r_V_phi_fu_256_p4;
wire   [63:0] tmp_336_i_fu_338_p1;
wire   [63:0] tmp_338_i_fu_343_p1;
wire   [63:0] tmp_335_i_fu_402_p1;
reg    ap_block_pp1_stage0_01001;
wire   [24:0] tmp_254_fu_286_p4;
wire   [24:0] tmp_255_fu_302_p4;
wire   [0:0] tmp_258_fu_372_p3;
wire   [0:0] tmp_257_fu_364_p3;
wire   [2:0] tmp_48_fu_380_p4;
wire   [1:0] tmp_256_fu_360_p1;
wire   [6:0] index_fu_390_p5;
wire   [127:0] pixels_V_load_phi_i_fu_422_p3;
wire   [255:0] tmp_49_fu_437_p4;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

gather_pixels_0_V #(
    .DataWidth( 128 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
pixels_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pixels_0_V_address0),
    .ce0(pixels_0_V_ce0),
    .we0(pixels_0_V_we0),
    .d0(tmp_V_reg_485),
    .q0(pixels_0_V_q0)
);

gather_pixels_0_V #(
    .DataWidth( 128 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
pixels_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(pixels_1_V_address0),
    .ce0(pixels_1_V_ce0),
    .we0(pixels_1_V_we0),
    .d0(tmp_V_31_reg_494),
    .q0(pixels_1_V_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond_i_fu_275_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond_i_fu_275_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond_i_fu_275_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state6)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state6);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_nbreadreq_fu_114_p3 == 1'd0) & (icmp_fu_296_p2 == 1'd1) & (tmp_325_i_fu_318_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp_fu_296_p2 == 1'd0) & (tmp_325_i_fu_318_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        na_1_i_reg_222 <= ap_phi_mux_na_i_phi_fu_202_p4;
    end else if (((tmp_nbreadreq_fu_114_p3 == 1'd1) & (icmp_fu_296_p2 == 1'd1) & (tmp_325_i_fu_318_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        na_1_i_reg_222 <= na_fu_324_p2;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        na_1_i_reg_222 <= ap_phi_reg_pp0_iter0_na_1_i_reg_222;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_i_fu_275_p2 == 1'd0))) begin
        na_i_reg_198 <= 32'd0;
    end else if (((tmp_325_i_reg_477 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        na_i_reg_198 <= na_1_i_reg_222;
    end
end

always @ (posedge ap_clk) begin
    if ((((tmp_3_nbreadreq_fu_128_p3 == 1'd0) & (icmp1_fu_312_p2 == 1'd1) & (tmp_325_i_fu_318_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((icmp1_fu_312_p2 == 1'd0) & (tmp_325_i_fu_318_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        nb_1_i_reg_237 <= ap_phi_mux_nb_i_phi_fu_214_p4;
    end else if (((tmp_3_nbreadreq_fu_128_p3 == 1'd1) & (icmp1_fu_312_p2 == 1'd1) & (tmp_325_i_fu_318_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nb_1_i_reg_237 <= nb_fu_331_p2;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nb_1_i_reg_237 <= ap_phi_reg_pp0_iter0_nb_1_i_reg_237;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_i_fu_275_p2 == 1'd0))) begin
        nb_i_reg_210 <= 32'd0;
    end else if (((tmp_325_i_reg_477 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nb_i_reg_210 <= nb_1_i_reg_237;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        p_i_reg_264 <= 9'd0;
    end else if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (tmp_326_i_fu_348_p2 == 1'd0))) begin
        p_i_reg_264 <= p_fu_354_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        r_V_reg_252 <= 384'd0;
    end else if (((ap_enable_reg_pp1_iter2 == 1'b1) & (tmp_326_i_reg_499_pp1_iter1_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        r_V_reg_252 <= phitmp_cast_i_reg_532;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        t_i_reg_187 <= t_reg_464;
    end else if ((~((tiles_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_i_reg_187 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp1_reg_473 <= icmp1_fu_312_p2;
        icmp_reg_469 <= icmp_fu_296_p2;
        tmp_325_i_reg_477 <= tmp_325_i_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (tmp_326_i_reg_499 == 1'd0))) begin
        p_Result_s_reg_527 <= p_Result_s_fu_429_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (tmp_326_i_reg_499 == 1'd0))) begin
        phitmp_cast_i_reg_532 <= phitmp_cast_i_fu_447_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        t_reg_464 <= t_fu_280_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((tiles_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tiles_read_reg_455 <= tiles_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (tmp_326_i_fu_348_p2 == 1'd0))) begin
        tmp_259_reg_508 <= p_i_reg_264[32'd2];
        tmp_337_i_reg_523 <= tmp_337_i_fu_416_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_326_i_reg_499 <= tmp_326_i_fu_348_p2;
        tmp_326_i_reg_499_pp1_iter1_reg <= tmp_326_i_reg_499;
        tmp_337_i_reg_523_pp1_iter1_reg <= tmp_337_i_reg_523;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp1_fu_312_p2 == 1'd1) & (tmp_325_i_fu_318_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_3_reg_490 <= b_V_V_empty_n;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op45_read_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_V_31_reg_494 <= b_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_predicate_op38_read_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_V_reg_485 <= a_V_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_fu_296_p2 == 1'd1) & (tmp_325_i_fu_318_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_reg_481 <= a_V_V_empty_n;
    end
end

always @ (*) begin
    if (((tmp_nbreadreq_fu_114_p3 == 1'd1) & (icmp_fu_296_p2 == 1'd1) & (tmp_325_i_fu_318_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_V_V_blk_n = a_V_V_empty_n;
    end else begin
        a_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op38_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        a_V_V_read = 1'b1;
    end else begin
        a_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_325_i_fu_318_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_326_i_fu_348_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_fu_275_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_325_i_reg_477 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_na_i_phi_fu_202_p4 = na_1_i_reg_222;
    end else begin
        ap_phi_mux_na_i_phi_fu_202_p4 = na_i_reg_198;
    end
end

always @ (*) begin
    if (((tmp_325_i_reg_477 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_nb_i_phi_fu_214_p4 = nb_1_i_reg_237;
    end else begin
        ap_phi_mux_nb_i_phi_fu_214_p4 = nb_i_reg_210;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (tmp_326_i_reg_499_pp1_iter1_reg == 1'd0))) begin
        ap_phi_mux_r_V_phi_fu_256_p4 = phitmp_cast_i_reg_532;
    end else begin
        ap_phi_mux_r_V_phi_fu_256_p4 = r_V_reg_252;
    end
end

always @ (*) begin
    if (((exitcond_i_fu_275_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_3_nbreadreq_fu_128_p3 == 1'd1) & (icmp1_fu_312_p2 == 1'd1) & (tmp_325_i_fu_318_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_V_V_blk_n = b_V_V_empty_n;
    end else begin
        b_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op45_read_state3 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        b_V_V_read = 1'b1;
    end else begin
        b_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_337_i_reg_523_pp1_iter1_reg == 1'd1) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        output_V_V_blk_n = output_V_V_full_n;
    end else begin
        output_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_337_i_reg_523_pp1_iter1_reg == 1'd1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_V_V_write = 1'b1;
    end else begin
        output_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        pixels_0_V_address0 = tmp_335_i_fu_402_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        pixels_0_V_address0 = tmp_336_i_fu_338_p1;
    end else begin
        pixels_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        pixels_0_V_ce0 = 1'b1;
    end else begin
        pixels_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_481 == 1'd1) & (tmp_325_i_reg_477 == 1'd1) & (icmp_reg_469 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_0_V_we0 = 1'b1;
    end else begin
        pixels_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        pixels_1_V_address0 = tmp_335_i_fu_402_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        pixels_1_V_address0 = tmp_338_i_fu_343_p1;
    end else begin
        pixels_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        pixels_1_V_ce0 = 1'b1;
    end else begin
        pixels_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_3_reg_490 == 1'd1) & (tmp_325_i_reg_477 == 1'd1) & (icmp1_reg_473 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        pixels_1_V_we0 = 1'b1;
    end else begin
        pixels_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tiles_blk_n = tiles_empty_n;
    end else begin
        tiles_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((tiles_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tiles_read = 1'b1;
    end else begin
        tiles_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((tiles_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_i_fu_275_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((tmp_325_i_fu_318_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((tmp_325_i_fu_318_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((tmp_326_i_fu_348_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)) & ~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)) | ((tmp_326_i_fu_348_p2 == 1'd1) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((b_V_V_empty_n == 1'b0) & (ap_predicate_op45_read_state3 == 1'b1)) | ((1'b0 == a_V_V_empty_n) & (ap_predicate_op38_read_state3 == 1'b1))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter0 == 1'b1) & (((b_V_V_empty_n == 1'b0) & (ap_predicate_op45_read_state3 == 1'b1)) | ((1'b0 == a_V_V_empty_n) & (ap_predicate_op38_read_state3 == 1'b1))));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = ((tmp_337_i_reg_523_pp1_iter1_reg == 1'd1) & (output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((tmp_337_i_reg_523_pp1_iter1_reg == 1'd1) & (output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((tmp_337_i_reg_523_pp1_iter1_reg == 1'd1) & (output_V_V_full_n == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((tiles_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter0 = (((b_V_V_empty_n == 1'b0) & (ap_predicate_op45_read_state3 == 1'b1)) | ((1'b0 == a_V_V_empty_n) & (ap_predicate_op38_read_state3 == 1'b1)));
end

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp1_stage0_iter2 = ((tmp_337_i_reg_523_pp1_iter1_reg == 1'd1) & (output_V_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_na_1_i_reg_222 = 'bx;

assign ap_phi_reg_pp0_iter0_nb_1_i_reg_237 = 'bx;

always @ (*) begin
    ap_predicate_op38_read_state3 = ((tmp_nbreadreq_fu_114_p3 == 1'd1) & (icmp_fu_296_p2 == 1'd1) & (tmp_325_i_fu_318_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op45_read_state3 = ((tmp_3_nbreadreq_fu_128_p3 == 1'd1) & (icmp1_fu_312_p2 == 1'd1) & (tmp_325_i_fu_318_p2 == 1'd1));
end

assign exitcond_i_fu_275_p2 = ((t_i_reg_187 == tiles_read_reg_455) ? 1'b1 : 1'b0);

assign icmp1_fu_312_p2 = ((tmp_255_fu_302_p4 == 25'd0) ? 1'b1 : 1'b0);

assign icmp_fu_296_p2 = ((tmp_254_fu_286_p4 == 25'd0) ? 1'b1 : 1'b0);

assign index_fu_390_p5 = {{{{tmp_258_fu_372_p3}, {tmp_257_fu_364_p3}}, {tmp_48_fu_380_p4}}, {tmp_256_fu_360_p1}};

assign na_fu_324_p2 = (ap_phi_mux_na_i_phi_fu_202_p4 + 32'd1);

assign nb_fu_331_p2 = (ap_phi_mux_nb_i_phi_fu_214_p4 + 32'd1);

assign output_V_V_din = p_Result_s_reg_527;

assign p_Result_s_fu_429_p3 = {{pixels_V_load_phi_i_fu_422_p3}, {ap_phi_mux_r_V_phi_fu_256_p4}};

assign p_fu_354_p2 = (p_i_reg_264 + 9'd1);

assign phitmp_cast_i_fu_447_p3 = {{pixels_V_load_phi_i_fu_422_p3}, {tmp_49_fu_437_p4}};

assign pixels_V_load_phi_i_fu_422_p3 = ((tmp_259_reg_508[0:0] === 1'b1) ? pixels_1_V_q0 : pixels_0_V_q0);

assign t_fu_280_p2 = (t_i_reg_187 + 32'd1);

assign tmp_254_fu_286_p4 = {{ap_phi_mux_na_i_phi_fu_202_p4[31:7]}};

assign tmp_255_fu_302_p4 = {{ap_phi_mux_nb_i_phi_fu_214_p4[31:7]}};

assign tmp_256_fu_360_p1 = p_i_reg_264[1:0];

assign tmp_257_fu_364_p3 = p_i_reg_264[32'd3];

assign tmp_258_fu_372_p3 = p_i_reg_264[32'd7];

assign tmp_325_i_fu_318_p2 = (icmp_fu_296_p2 | icmp1_fu_312_p2);

assign tmp_326_i_fu_348_p2 = ((p_i_reg_264 == 9'd256) ? 1'b1 : 1'b0);

assign tmp_335_i_fu_402_p1 = index_fu_390_p5;

assign tmp_336_i_fu_338_p1 = na_i_reg_198;

assign tmp_337_i_fu_416_p2 = ((tmp_256_fu_360_p1 == 2'd3) ? 1'b1 : 1'b0);

assign tmp_338_i_fu_343_p1 = nb_i_reg_210;

assign tmp_3_nbreadreq_fu_128_p3 = b_V_V_empty_n;

assign tmp_48_fu_380_p4 = {{p_i_reg_264[6:4]}};

assign tmp_49_fu_437_p4 = {{ap_phi_mux_r_V_phi_fu_256_p4[383:128]}};

assign tmp_nbreadreq_fu_114_p3 = a_V_V_empty_n;

endmodule //gather
