// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module framed_ctu (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write,
        mode_dout,
        mode_empty_n,
        mode_read,
        ap_clk,
        ap_rst,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [511:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [511:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;
input  [31:0] mode_dout;
input   mode_empty_n;
output   mode_read;
input   ap_clk;
input   ap_rst;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    prepare_frames_U0_ap_start;
wire    prepare_frames_U0_ap_done;
wire    prepare_frames_U0_ap_continue;
wire    prepare_frames_U0_ap_idle;
wire    prepare_frames_U0_ap_ready;
wire    prepare_frames_U0_start_out;
wire    prepare_frames_U0_start_write;
wire    prepare_frames_U0_input_V_V_read;
wire   [511:0] prepare_frames_U0_output_V_q_V_din;
wire    prepare_frames_U0_output_V_q_V_write;
wire   [15:0] prepare_frames_U0_output_V_limit_din;
wire    prepare_frames_U0_output_V_limit_write;
wire    prepare_frames_U0_output_V_dense_din;
wire    prepare_frames_U0_output_V_dense_write;
wire    prepare_frames_U0_output_V_bypass_din;
wire    prepare_frames_U0_output_V_bypass_write;
wire    prepare_frames_U0_mode_read;
wire    expand_frames_U0_ap_start;
wire    expand_frames_U0_ap_done;
wire    expand_frames_U0_ap_continue;
wire    expand_frames_U0_ap_idle;
wire    expand_frames_U0_ap_ready;
wire    expand_frames_U0_start_out;
wire    expand_frames_U0_start_write;
wire    expand_frames_U0_input_V_q_V_read;
wire    expand_frames_U0_input_V_limit_read;
wire    expand_frames_U0_input_V_dense_dout;
wire    expand_frames_U0_input_V_dense_read;
wire    expand_frames_U0_input_V_bypass_dout;
wire    expand_frames_U0_input_V_bypass_read;
wire   [511:0] expand_frames_U0_output_V_p_q_V_din;
wire    expand_frames_U0_output_V_p_q_V_write;
wire   [15:0] expand_frames_U0_output_V_p_limit_din;
wire    expand_frames_U0_output_V_p_limit_write;
wire    expand_frames_U0_output_V_p_dense_din;
wire    expand_frames_U0_output_V_p_dense_write;
wire    expand_frames_U0_output_V_p_bypass_din;
wire    expand_frames_U0_output_V_p_bypass_write;
wire    expand_frames_U0_output_V_second_din;
wire    expand_frames_U0_output_V_second_write;
wire    expand_frames_U0_output_V_end_din;
wire    expand_frames_U0_output_V_end_write;
wire    test_frames_U0_ap_start;
wire    test_frames_U0_ap_done;
wire    test_frames_U0_ap_continue;
wire    test_frames_U0_ap_idle;
wire    test_frames_U0_ap_ready;
wire    test_frames_U0_start_out;
wire    test_frames_U0_start_write;
wire    test_frames_U0_input_V_p_q_V_read;
wire    test_frames_U0_input_V_p_limit_read;
wire    test_frames_U0_input_V_p_dense_dout;
wire    test_frames_U0_input_V_p_dense_read;
wire    test_frames_U0_input_V_p_bypass_dout;
wire    test_frames_U0_input_V_p_bypass_read;
wire    test_frames_U0_input_V_second_dout;
wire    test_frames_U0_input_V_second_read;
wire    test_frames_U0_input_V_end_dout;
wire    test_frames_U0_input_V_end_read;
wire   [511:0] test_frames_U0_output_V_q_V_din;
wire    test_frames_U0_output_V_q_V_write;
wire   [3:0] test_frames_U0_output_V_mask_V_din;
wire    test_frames_U0_output_V_mask_V_write;
wire    test_frames_U0_output_V_dense_din;
wire    test_frames_U0_output_V_dense_write;
wire    test_frames_U0_output_V_second_din;
wire    test_frames_U0_output_V_second_write;
wire    test_frames_U0_output_V_end_din;
wire    test_frames_U0_output_V_end_write;
wire    merge_frames_U0_ap_start;
wire    merge_frames_U0_ap_done;
wire    merge_frames_U0_ap_continue;
wire    merge_frames_U0_ap_idle;
wire    merge_frames_U0_ap_ready;
wire    merge_frames_U0_input_V_q_V_read;
wire    merge_frames_U0_input_V_mask_V_read;
wire    merge_frames_U0_input_V_dense_dout;
wire    merge_frames_U0_input_V_dense_read;
wire    merge_frames_U0_input_V_second_dout;
wire    merge_frames_U0_input_V_second_read;
wire    merge_frames_U0_input_V_end_dout;
wire    merge_frames_U0_input_V_end_read;
wire   [511:0] merge_frames_U0_output_V_V_din;
wire    merge_frames_U0_output_V_V_write;
wire    ap_sync_continue;
wire    prepared_V_q_V_full_n;
wire   [511:0] prepared_V_q_V_dout;
wire    prepared_V_q_V_empty_n;
wire    prepared_V_limit_full_n;
wire   [15:0] prepared_V_limit_dout;
wire    prepared_V_limit_empty_n;
wire   [0:0] prepared_V_dense_din;
wire    prepared_V_dense_full_n;
wire   [0:0] prepared_V_dense_dout;
wire    prepared_V_dense_empty_n;
wire   [0:0] prepared_V_bypass_din;
wire    prepared_V_bypass_full_n;
wire   [0:0] prepared_V_bypass_dout;
wire    prepared_V_bypass_empty_n;
wire    requests_V_p_q_V_full_n;
wire   [511:0] requests_V_p_q_V_dout;
wire    requests_V_p_q_V_empty_n;
wire    requests_V_p_limit_full_n;
wire   [15:0] requests_V_p_limit_dout;
wire    requests_V_p_limit_empty_n;
wire   [0:0] requests_V_p_dense_din;
wire    requests_V_p_dense_full_n;
wire   [0:0] requests_V_p_dense_dout;
wire    requests_V_p_dense_empty_n;
wire   [0:0] requests_V_p_bypass_din;
wire    requests_V_p_bypass_full_n;
wire   [0:0] requests_V_p_bypass_dout;
wire    requests_V_p_bypass_empty_n;
wire   [0:0] requests_V_second_din;
wire    requests_V_second_full_n;
wire   [0:0] requests_V_second_dout;
wire    requests_V_second_empty_n;
wire   [0:0] requests_V_end_din;
wire    requests_V_end_full_n;
wire   [0:0] requests_V_end_dout;
wire    requests_V_end_empty_n;
wire    tested_V_q_V_full_n;
wire   [511:0] tested_V_q_V_dout;
wire    tested_V_q_V_empty_n;
wire    tested_V_mask_V_full_n;
wire   [3:0] tested_V_mask_V_dout;
wire    tested_V_mask_V_empty_n;
wire   [0:0] tested_V_dense_din;
wire    tested_V_dense_full_n;
wire   [0:0] tested_V_dense_dout;
wire    tested_V_dense_empty_n;
wire   [0:0] tested_V_second_din;
wire    tested_V_second_full_n;
wire   [0:0] tested_V_second_dout;
wire    tested_V_second_empty_n;
wire   [0:0] tested_V_end_din;
wire    tested_V_end_full_n;
wire   [0:0] tested_V_end_dout;
wire    tested_V_end_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_expand_frames_U0_din;
wire    start_for_expand_frames_U0_full_n;
wire   [0:0] start_for_expand_frames_U0_dout;
wire    start_for_expand_frames_U0_empty_n;
wire   [0:0] start_for_test_frames_U0_din;
wire    start_for_test_frames_U0_full_n;
wire   [0:0] start_for_test_frames_U0_dout;
wire    start_for_test_frames_U0_empty_n;
wire   [0:0] start_for_merge_frames_U0_din;
wire    start_for_merge_frames_U0_full_n;
wire   [0:0] start_for_merge_frames_U0_dout;
wire    start_for_merge_frames_U0_empty_n;
wire    merge_frames_U0_start_full_n;
wire    merge_frames_U0_start_write;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

prepare_frames prepare_frames_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(prepare_frames_U0_ap_start),
    .start_full_n(start_for_expand_frames_U0_full_n),
    .ap_done(prepare_frames_U0_ap_done),
    .ap_continue(prepare_frames_U0_ap_continue),
    .ap_idle(prepare_frames_U0_ap_idle),
    .ap_ready(prepare_frames_U0_ap_ready),
    .start_out(prepare_frames_U0_start_out),
    .start_write(prepare_frames_U0_start_write),
    .input_V_V_dout(input_V_V_dout),
    .input_V_V_empty_n(input_V_V_empty_n),
    .input_V_V_read(prepare_frames_U0_input_V_V_read),
    .output_V_q_V_din(prepare_frames_U0_output_V_q_V_din),
    .output_V_q_V_full_n(prepared_V_q_V_full_n),
    .output_V_q_V_write(prepare_frames_U0_output_V_q_V_write),
    .output_V_limit_din(prepare_frames_U0_output_V_limit_din),
    .output_V_limit_full_n(prepared_V_limit_full_n),
    .output_V_limit_write(prepare_frames_U0_output_V_limit_write),
    .output_V_dense_din(prepare_frames_U0_output_V_dense_din),
    .output_V_dense_full_n(prepared_V_dense_full_n),
    .output_V_dense_write(prepare_frames_U0_output_V_dense_write),
    .output_V_bypass_din(prepare_frames_U0_output_V_bypass_din),
    .output_V_bypass_full_n(prepared_V_bypass_full_n),
    .output_V_bypass_write(prepare_frames_U0_output_V_bypass_write),
    .mode_dout(mode_dout),
    .mode_empty_n(mode_empty_n),
    .mode_read(prepare_frames_U0_mode_read)
);

expand_frames expand_frames_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(expand_frames_U0_ap_start),
    .start_full_n(start_for_test_frames_U0_full_n),
    .ap_done(expand_frames_U0_ap_done),
    .ap_continue(expand_frames_U0_ap_continue),
    .ap_idle(expand_frames_U0_ap_idle),
    .ap_ready(expand_frames_U0_ap_ready),
    .start_out(expand_frames_U0_start_out),
    .start_write(expand_frames_U0_start_write),
    .input_V_q_V_dout(prepared_V_q_V_dout),
    .input_V_q_V_empty_n(prepared_V_q_V_empty_n),
    .input_V_q_V_read(expand_frames_U0_input_V_q_V_read),
    .input_V_limit_dout(prepared_V_limit_dout),
    .input_V_limit_empty_n(prepared_V_limit_empty_n),
    .input_V_limit_read(expand_frames_U0_input_V_limit_read),
    .input_V_dense_dout(expand_frames_U0_input_V_dense_dout),
    .input_V_dense_empty_n(prepared_V_dense_empty_n),
    .input_V_dense_read(expand_frames_U0_input_V_dense_read),
    .input_V_bypass_dout(expand_frames_U0_input_V_bypass_dout),
    .input_V_bypass_empty_n(prepared_V_bypass_empty_n),
    .input_V_bypass_read(expand_frames_U0_input_V_bypass_read),
    .output_V_p_q_V_din(expand_frames_U0_output_V_p_q_V_din),
    .output_V_p_q_V_full_n(requests_V_p_q_V_full_n),
    .output_V_p_q_V_write(expand_frames_U0_output_V_p_q_V_write),
    .output_V_p_limit_din(expand_frames_U0_output_V_p_limit_din),
    .output_V_p_limit_full_n(requests_V_p_limit_full_n),
    .output_V_p_limit_write(expand_frames_U0_output_V_p_limit_write),
    .output_V_p_dense_din(expand_frames_U0_output_V_p_dense_din),
    .output_V_p_dense_full_n(requests_V_p_dense_full_n),
    .output_V_p_dense_write(expand_frames_U0_output_V_p_dense_write),
    .output_V_p_bypass_din(expand_frames_U0_output_V_p_bypass_din),
    .output_V_p_bypass_full_n(requests_V_p_bypass_full_n),
    .output_V_p_bypass_write(expand_frames_U0_output_V_p_bypass_write),
    .output_V_second_din(expand_frames_U0_output_V_second_din),
    .output_V_second_full_n(requests_V_second_full_n),
    .output_V_second_write(expand_frames_U0_output_V_second_write),
    .output_V_end_din(expand_frames_U0_output_V_end_din),
    .output_V_end_full_n(requests_V_end_full_n),
    .output_V_end_write(expand_frames_U0_output_V_end_write)
);

test_frames test_frames_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(test_frames_U0_ap_start),
    .start_full_n(start_for_merge_frames_U0_full_n),
    .ap_done(test_frames_U0_ap_done),
    .ap_continue(test_frames_U0_ap_continue),
    .ap_idle(test_frames_U0_ap_idle),
    .ap_ready(test_frames_U0_ap_ready),
    .start_out(test_frames_U0_start_out),
    .start_write(test_frames_U0_start_write),
    .input_V_p_q_V_dout(requests_V_p_q_V_dout),
    .input_V_p_q_V_empty_n(requests_V_p_q_V_empty_n),
    .input_V_p_q_V_read(test_frames_U0_input_V_p_q_V_read),
    .input_V_p_limit_dout(requests_V_p_limit_dout),
    .input_V_p_limit_empty_n(requests_V_p_limit_empty_n),
    .input_V_p_limit_read(test_frames_U0_input_V_p_limit_read),
    .input_V_p_dense_dout(test_frames_U0_input_V_p_dense_dout),
    .input_V_p_dense_empty_n(requests_V_p_dense_empty_n),
    .input_V_p_dense_read(test_frames_U0_input_V_p_dense_read),
    .input_V_p_bypass_dout(test_frames_U0_input_V_p_bypass_dout),
    .input_V_p_bypass_empty_n(requests_V_p_bypass_empty_n),
    .input_V_p_bypass_read(test_frames_U0_input_V_p_bypass_read),
    .input_V_second_dout(test_frames_U0_input_V_second_dout),
    .input_V_second_empty_n(requests_V_second_empty_n),
    .input_V_second_read(test_frames_U0_input_V_second_read),
    .input_V_end_dout(test_frames_U0_input_V_end_dout),
    .input_V_end_empty_n(requests_V_end_empty_n),
    .input_V_end_read(test_frames_U0_input_V_end_read),
    .output_V_q_V_din(test_frames_U0_output_V_q_V_din),
    .output_V_q_V_full_n(tested_V_q_V_full_n),
    .output_V_q_V_write(test_frames_U0_output_V_q_V_write),
    .output_V_mask_V_din(test_frames_U0_output_V_mask_V_din),
    .output_V_mask_V_full_n(tested_V_mask_V_full_n),
    .output_V_mask_V_write(test_frames_U0_output_V_mask_V_write),
    .output_V_dense_din(test_frames_U0_output_V_dense_din),
    .output_V_dense_full_n(tested_V_dense_full_n),
    .output_V_dense_write(test_frames_U0_output_V_dense_write),
    .output_V_second_din(test_frames_U0_output_V_second_din),
    .output_V_second_full_n(tested_V_second_full_n),
    .output_V_second_write(test_frames_U0_output_V_second_write),
    .output_V_end_din(test_frames_U0_output_V_end_din),
    .output_V_end_full_n(tested_V_end_full_n),
    .output_V_end_write(test_frames_U0_output_V_end_write)
);

merge_frames merge_frames_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(merge_frames_U0_ap_start),
    .ap_done(merge_frames_U0_ap_done),
    .ap_continue(merge_frames_U0_ap_continue),
    .ap_idle(merge_frames_U0_ap_idle),
    .ap_ready(merge_frames_U0_ap_ready),
    .input_V_q_V_dout(tested_V_q_V_dout),
    .input_V_q_V_empty_n(tested_V_q_V_empty_n),
    .input_V_q_V_read(merge_frames_U0_input_V_q_V_read),
    .input_V_mask_V_dout(tested_V_mask_V_dout),
    .input_V_mask_V_empty_n(tested_V_mask_V_empty_n),
    .input_V_mask_V_read(merge_frames_U0_input_V_mask_V_read),
    .input_V_dense_dout(merge_frames_U0_input_V_dense_dout),
    .input_V_dense_empty_n(tested_V_dense_empty_n),
    .input_V_dense_read(merge_frames_U0_input_V_dense_read),
    .input_V_second_dout(merge_frames_U0_input_V_second_dout),
    .input_V_second_empty_n(tested_V_second_empty_n),
    .input_V_second_read(merge_frames_U0_input_V_second_read),
    .input_V_end_dout(merge_frames_U0_input_V_end_dout),
    .input_V_end_empty_n(tested_V_end_empty_n),
    .input_V_end_read(merge_frames_U0_input_V_end_read),
    .output_V_V_din(merge_frames_U0_output_V_V_din),
    .output_V_V_full_n(output_V_V_full_n),
    .output_V_V_write(merge_frames_U0_output_V_V_write)
);

fifo_w512_d16_S prepared_V_q_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(prepare_frames_U0_output_V_q_V_din),
    .if_full_n(prepared_V_q_V_full_n),
    .if_write(prepare_frames_U0_output_V_q_V_write),
    .if_dout(prepared_V_q_V_dout),
    .if_empty_n(prepared_V_q_V_empty_n),
    .if_read(expand_frames_U0_input_V_q_V_read)
);

fifo_w16_d16_S prepared_V_limit_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(prepare_frames_U0_output_V_limit_din),
    .if_full_n(prepared_V_limit_full_n),
    .if_write(prepare_frames_U0_output_V_limit_write),
    .if_dout(prepared_V_limit_dout),
    .if_empty_n(prepared_V_limit_empty_n),
    .if_read(expand_frames_U0_input_V_limit_read)
);

fifo_w1_d16_S prepared_V_dense_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(prepared_V_dense_din),
    .if_full_n(prepared_V_dense_full_n),
    .if_write(prepare_frames_U0_output_V_dense_write),
    .if_dout(prepared_V_dense_dout),
    .if_empty_n(prepared_V_dense_empty_n),
    .if_read(expand_frames_U0_input_V_dense_read)
);

fifo_w1_d16_S prepared_V_bypass_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(prepared_V_bypass_din),
    .if_full_n(prepared_V_bypass_full_n),
    .if_write(prepare_frames_U0_output_V_bypass_write),
    .if_dout(prepared_V_bypass_dout),
    .if_empty_n(prepared_V_bypass_empty_n),
    .if_read(expand_frames_U0_input_V_bypass_read)
);

fifo_w512_d16_S requests_V_p_q_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(expand_frames_U0_output_V_p_q_V_din),
    .if_full_n(requests_V_p_q_V_full_n),
    .if_write(expand_frames_U0_output_V_p_q_V_write),
    .if_dout(requests_V_p_q_V_dout),
    .if_empty_n(requests_V_p_q_V_empty_n),
    .if_read(test_frames_U0_input_V_p_q_V_read)
);

fifo_w16_d16_S requests_V_p_limit_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(expand_frames_U0_output_V_p_limit_din),
    .if_full_n(requests_V_p_limit_full_n),
    .if_write(expand_frames_U0_output_V_p_limit_write),
    .if_dout(requests_V_p_limit_dout),
    .if_empty_n(requests_V_p_limit_empty_n),
    .if_read(test_frames_U0_input_V_p_limit_read)
);

fifo_w1_d16_S requests_V_p_dense_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(requests_V_p_dense_din),
    .if_full_n(requests_V_p_dense_full_n),
    .if_write(expand_frames_U0_output_V_p_dense_write),
    .if_dout(requests_V_p_dense_dout),
    .if_empty_n(requests_V_p_dense_empty_n),
    .if_read(test_frames_U0_input_V_p_dense_read)
);

fifo_w1_d16_S requests_V_p_bypass_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(requests_V_p_bypass_din),
    .if_full_n(requests_V_p_bypass_full_n),
    .if_write(expand_frames_U0_output_V_p_bypass_write),
    .if_dout(requests_V_p_bypass_dout),
    .if_empty_n(requests_V_p_bypass_empty_n),
    .if_read(test_frames_U0_input_V_p_bypass_read)
);

fifo_w1_d16_S requests_V_second_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(requests_V_second_din),
    .if_full_n(requests_V_second_full_n),
    .if_write(expand_frames_U0_output_V_second_write),
    .if_dout(requests_V_second_dout),
    .if_empty_n(requests_V_second_empty_n),
    .if_read(test_frames_U0_input_V_second_read)
);

fifo_w1_d16_S requests_V_end_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(requests_V_end_din),
    .if_full_n(requests_V_end_full_n),
    .if_write(expand_frames_U0_output_V_end_write),
    .if_dout(requests_V_end_dout),
    .if_empty_n(requests_V_end_empty_n),
    .if_read(test_frames_U0_input_V_end_read)
);

fifo_w512_d16_S tested_V_q_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(test_frames_U0_output_V_q_V_din),
    .if_full_n(tested_V_q_V_full_n),
    .if_write(test_frames_U0_output_V_q_V_write),
    .if_dout(tested_V_q_V_dout),
    .if_empty_n(tested_V_q_V_empty_n),
    .if_read(merge_frames_U0_input_V_q_V_read)
);

fifo_w4_d16_S tested_V_mask_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(test_frames_U0_output_V_mask_V_din),
    .if_full_n(tested_V_mask_V_full_n),
    .if_write(test_frames_U0_output_V_mask_V_write),
    .if_dout(tested_V_mask_V_dout),
    .if_empty_n(tested_V_mask_V_empty_n),
    .if_read(merge_frames_U0_input_V_mask_V_read)
);

fifo_w1_d16_S tested_V_dense_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tested_V_dense_din),
    .if_full_n(tested_V_dense_full_n),
    .if_write(test_frames_U0_output_V_dense_write),
    .if_dout(tested_V_dense_dout),
    .if_empty_n(tested_V_dense_empty_n),
    .if_read(merge_frames_U0_input_V_dense_read)
);

fifo_w1_d16_S tested_V_second_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tested_V_second_din),
    .if_full_n(tested_V_second_full_n),
    .if_write(test_frames_U0_output_V_second_write),
    .if_dout(tested_V_second_dout),
    .if_empty_n(tested_V_second_empty_n),
    .if_read(merge_frames_U0_input_V_second_read)
);

fifo_w1_d16_S tested_V_end_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tested_V_end_din),
    .if_full_n(tested_V_end_full_n),
    .if_write(test_frames_U0_output_V_end_write),
    .if_dout(tested_V_end_dout),
    .if_empty_n(tested_V_end_empty_n),
    .if_read(merge_frames_U0_input_V_end_read)
);

start_for_expand_zec start_for_expand_zec_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_expand_frames_U0_din),
    .if_full_n(start_for_expand_frames_U0_full_n),
    .if_write(prepare_frames_U0_start_write),
    .if_dout(start_for_expand_frames_U0_dout),
    .if_empty_n(start_for_expand_frames_U0_empty_n),
    .if_read(expand_frames_U0_ap_ready)
);

start_for_test_frAem start_for_test_frAem_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_test_frames_U0_din),
    .if_full_n(start_for_test_frames_U0_full_n),
    .if_write(expand_frames_U0_start_write),
    .if_dout(start_for_test_frames_U0_dout),
    .if_empty_n(start_for_test_frames_U0_empty_n),
    .if_read(test_frames_U0_ap_ready)
);

start_for_merge_fBew start_for_merge_fBew_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_merge_frames_U0_din),
    .if_full_n(start_for_merge_frames_U0_full_n),
    .if_write(test_frames_U0_start_write),
    .if_dout(start_for_merge_frames_U0_dout),
    .if_empty_n(start_for_merge_frames_U0_empty_n),
    .if_read(merge_frames_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign ap_done = merge_frames_U0_ap_done;

assign ap_idle = (test_frames_U0_ap_idle & prepare_frames_U0_ap_idle & merge_frames_U0_ap_idle & expand_frames_U0_ap_idle);

assign ap_ready = internal_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = merge_frames_U0_ap_done;

assign ap_sync_ready = prepare_frames_U0_ap_ready;

assign expand_frames_U0_ap_continue = 1'b1;

assign expand_frames_U0_ap_start = start_for_expand_frames_U0_empty_n;

assign expand_frames_U0_input_V_bypass_dout = prepared_V_bypass_dout;

assign expand_frames_U0_input_V_dense_dout = prepared_V_dense_dout;

assign input_V_V_read = prepare_frames_U0_input_V_V_read;

assign internal_ap_ready = ap_sync_ready;

assign merge_frames_U0_ap_continue = ap_continue;

assign merge_frames_U0_ap_start = start_for_merge_frames_U0_empty_n;

assign merge_frames_U0_input_V_dense_dout = tested_V_dense_dout;

assign merge_frames_U0_input_V_end_dout = tested_V_end_dout;

assign merge_frames_U0_input_V_second_dout = tested_V_second_dout;

assign merge_frames_U0_start_full_n = 1'b1;

assign merge_frames_U0_start_write = 1'b0;

assign mode_read = prepare_frames_U0_mode_read;

assign output_V_V_din = merge_frames_U0_output_V_V_din;

assign output_V_V_write = merge_frames_U0_output_V_V_write;

assign prepare_frames_U0_ap_continue = 1'b1;

assign prepare_frames_U0_ap_start = real_start;

assign prepared_V_bypass_din = prepare_frames_U0_output_V_bypass_din;

assign prepared_V_dense_din = prepare_frames_U0_output_V_dense_din;

assign requests_V_end_din = expand_frames_U0_output_V_end_din;

assign requests_V_p_bypass_din = expand_frames_U0_output_V_p_bypass_din;

assign requests_V_p_dense_din = expand_frames_U0_output_V_p_dense_din;

assign requests_V_second_din = expand_frames_U0_output_V_second_din;

assign start_for_expand_frames_U0_din = 1'b1;

assign start_for_merge_frames_U0_din = 1'b1;

assign start_for_test_frames_U0_din = 1'b1;

assign start_out = real_start;

assign test_frames_U0_ap_continue = 1'b1;

assign test_frames_U0_ap_start = start_for_test_frames_U0_empty_n;

assign test_frames_U0_input_V_end_dout = requests_V_end_dout;

assign test_frames_U0_input_V_p_bypass_dout = requests_V_p_bypass_dout;

assign test_frames_U0_input_V_p_dense_dout = requests_V_p_dense_dout;

assign test_frames_U0_input_V_second_dout = requests_V_second_dout;

assign tested_V_dense_din = test_frames_U0_output_V_dense_din;

assign tested_V_end_din = test_frames_U0_output_V_end_din;

assign tested_V_second_din = test_frames_U0_output_V_second_din;

endmodule //framed_ctu
