// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module render_lane_hgr_1u_s (
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [231:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [127:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    hgr_packetize_precom_U0_ap_start;
wire    hgr_packetize_precom_U0_ap_done;
wire    hgr_packetize_precom_U0_ap_continue;
wire    hgr_packetize_precom_U0_ap_idle;
wire    hgr_packetize_precom_U0_ap_ready;
wire    hgr_packetize_precom_U0_start_out;
wire    hgr_packetize_precom_U0_start_write;
wire    hgr_packetize_precom_U0_input_V_V_read;
wire    hgr_packetize_precom_U0_feedback_V_V_read;
wire   [89:0] hgr_packetize_precom_U0_metadata_V_V_din;
wire    hgr_packetize_precom_U0_metadata_V_V_write;
wire   [16:0] hgr_packetize_precom_U0_alpha_out_V_V_din;
wire    hgr_packetize_precom_U0_alpha_out_V_V_write;
wire    hgr_composite_1u_U0_ap_start;
wire    hgr_composite_1u_U0_ap_done;
wire    hgr_composite_1u_U0_ap_continue;
wire    hgr_composite_1u_U0_ap_idle;
wire    hgr_composite_1u_U0_ap_ready;
wire    hgr_composite_1u_U0_metadata_V_V_read;
wire    hgr_composite_1u_U0_alpha_in_V_V_read;
wire   [159:0] hgr_composite_1u_U0_feedback_V_V_din;
wire    hgr_composite_1u_U0_feedback_V_V_write;
wire   [127:0] hgr_composite_1u_U0_output_V_V_din;
wire    hgr_composite_1u_U0_output_V_V_write;
wire    ap_sync_continue;
wire    feedback_V_V_full_n;
wire   [159:0] feedback_V_V_dout;
wire    feedback_V_V_empty_n;
wire    metadata_V_V_full_n;
wire   [89:0] metadata_V_V_dout;
wire    metadata_V_V_empty_n;
wire    alpha_V_V_full_n;
wire   [16:0] alpha_V_V_dout;
wire    alpha_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_hgr_composite_1u_U0_din;
wire    start_for_hgr_composite_1u_U0_full_n;
wire   [0:0] start_for_hgr_composite_1u_U0_dout;
wire    start_for_hgr_composite_1u_U0_empty_n;
wire    hgr_composite_1u_U0_start_full_n;
wire    hgr_composite_1u_U0_start_write;

hgr_packetize_precom hgr_packetize_precom_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(hgr_packetize_precom_U0_ap_start),
    .start_full_n(start_for_hgr_composite_1u_U0_full_n),
    .ap_done(hgr_packetize_precom_U0_ap_done),
    .ap_continue(hgr_packetize_precom_U0_ap_continue),
    .ap_idle(hgr_packetize_precom_U0_ap_idle),
    .ap_ready(hgr_packetize_precom_U0_ap_ready),
    .start_out(hgr_packetize_precom_U0_start_out),
    .start_write(hgr_packetize_precom_U0_start_write),
    .input_V_V_dout(input_V_V_dout),
    .input_V_V_empty_n(input_V_V_empty_n),
    .input_V_V_read(hgr_packetize_precom_U0_input_V_V_read),
    .feedback_V_V_dout(feedback_V_V_dout),
    .feedback_V_V_empty_n(feedback_V_V_empty_n),
    .feedback_V_V_read(hgr_packetize_precom_U0_feedback_V_V_read),
    .metadata_V_V_din(hgr_packetize_precom_U0_metadata_V_V_din),
    .metadata_V_V_full_n(metadata_V_V_full_n),
    .metadata_V_V_write(hgr_packetize_precom_U0_metadata_V_V_write),
    .alpha_out_V_V_din(hgr_packetize_precom_U0_alpha_out_V_V_din),
    .alpha_out_V_V_full_n(alpha_V_V_full_n),
    .alpha_out_V_V_write(hgr_packetize_precom_U0_alpha_out_V_V_write)
);

hgr_composite_1u_s hgr_composite_1u_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(hgr_composite_1u_U0_ap_start),
    .ap_done(hgr_composite_1u_U0_ap_done),
    .ap_continue(hgr_composite_1u_U0_ap_continue),
    .ap_idle(hgr_composite_1u_U0_ap_idle),
    .ap_ready(hgr_composite_1u_U0_ap_ready),
    .metadata_V_V_dout(metadata_V_V_dout),
    .metadata_V_V_empty_n(metadata_V_V_empty_n),
    .metadata_V_V_read(hgr_composite_1u_U0_metadata_V_V_read),
    .alpha_in_V_V_dout(alpha_V_V_dout),
    .alpha_in_V_V_empty_n(alpha_V_V_empty_n),
    .alpha_in_V_V_read(hgr_composite_1u_U0_alpha_in_V_V_read),
    .feedback_V_V_din(hgr_composite_1u_U0_feedback_V_V_din),
    .feedback_V_V_full_n(feedback_V_V_full_n),
    .feedback_V_V_write(hgr_composite_1u_U0_feedback_V_V_write),
    .output_V_V_din(hgr_composite_1u_U0_output_V_V_din),
    .output_V_V_full_n(output_V_V_full_n),
    .output_V_V_write(hgr_composite_1u_U0_output_V_V_write)
);

fifo_w160_d2_S_x feedback_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hgr_composite_1u_U0_feedback_V_V_din),
    .if_full_n(feedback_V_V_full_n),
    .if_write(hgr_composite_1u_U0_feedback_V_V_write),
    .if_dout(feedback_V_V_dout),
    .if_empty_n(feedback_V_V_empty_n),
    .if_read(hgr_packetize_precom_U0_feedback_V_V_read)
);

fifo_w90_d2_S_x metadata_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hgr_packetize_precom_U0_metadata_V_V_din),
    .if_full_n(metadata_V_V_full_n),
    .if_write(hgr_packetize_precom_U0_metadata_V_V_write),
    .if_dout(metadata_V_V_dout),
    .if_empty_n(metadata_V_V_empty_n),
    .if_read(hgr_composite_1u_U0_metadata_V_V_read)
);

fifo_w17_d128_S_x alpha_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(hgr_packetize_precom_U0_alpha_out_V_V_din),
    .if_full_n(alpha_V_V_full_n),
    .if_write(hgr_packetize_precom_U0_alpha_out_V_V_write),
    .if_dout(alpha_V_V_dout),
    .if_empty_n(alpha_V_V_empty_n),
    .if_read(hgr_composite_1u_U0_alpha_in_V_V_read)
);

start_for_hgr_comThq start_for_hgr_comThq_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_hgr_composite_1u_U0_din),
    .if_full_n(start_for_hgr_composite_1u_U0_full_n),
    .if_write(hgr_packetize_precom_U0_start_write),
    .if_dout(start_for_hgr_composite_1u_U0_dout),
    .if_empty_n(start_for_hgr_composite_1u_U0_empty_n),
    .if_read(hgr_composite_1u_U0_ap_ready)
);

assign ap_done = hgr_composite_1u_U0_ap_done;

assign ap_idle = (hgr_packetize_precom_U0_ap_idle & hgr_composite_1u_U0_ap_idle);

assign ap_ready = hgr_packetize_precom_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = hgr_composite_1u_U0_ap_done;

assign ap_sync_ready = hgr_packetize_precom_U0_ap_ready;

assign hgr_composite_1u_U0_ap_continue = ap_continue;

assign hgr_composite_1u_U0_ap_start = start_for_hgr_composite_1u_U0_empty_n;

assign hgr_composite_1u_U0_start_full_n = 1'b1;

assign hgr_composite_1u_U0_start_write = 1'b0;

assign hgr_packetize_precom_U0_ap_continue = 1'b1;

assign hgr_packetize_precom_U0_ap_start = ap_start;

assign input_V_V_read = hgr_packetize_precom_U0_input_V_V_read;

assign output_V_V_din = hgr_composite_1u_U0_output_V_V_din;

assign output_V_V_write = hgr_composite_1u_U0_output_V_V_write;

assign start_for_hgr_composite_1u_U0_din = 1'b1;

endmodule //render_lane_hgr_1u_s
