// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module split (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        output_V_V_din,
        output_V_V_full_n,
        output_V_V_write,
        tiles,
        mode,
        tiles_out_din,
        tiles_out_full_n,
        tiles_out_write,
        mode_out_din,
        mode_out_full_n,
        mode_out_write,
        ap_clk,
        ap_rst,
        mode_ap_vld,
        tiles_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [511:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [511:0] output_V_V_din;
input   output_V_V_full_n;
output   output_V_V_write;
input  [31:0] tiles;
input  [31:0] mode;
output  [31:0] tiles_out_din;
input   tiles_out_full_n;
output   tiles_out_write;
output  [31:0] mode_out_din;
input   mode_out_full_n;
output   mode_out_write;
input   ap_clk;
input   ap_rst;
input   mode_ap_vld;
input   tiles_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    frame_gaussians29029_U0_ap_start;
wire    frame_gaussians29029_U0_start_full_n;
wire    frame_gaussians29029_U0_ap_done;
wire    frame_gaussians29029_U0_ap_continue;
wire    frame_gaussians29029_U0_ap_idle;
wire    frame_gaussians29029_U0_ap_ready;
wire    frame_gaussians29029_U0_start_out;
wire    frame_gaussians29029_U0_start_write;
wire   [31:0] frame_gaussians29029_U0_mode_out_din;
wire    frame_gaussians29029_U0_mode_out_write;
wire   [31:0] frame_gaussians29029_U0_tiles_out_din;
wire    frame_gaussians29029_U0_tiles_out_write;
wire    frame_gaussians29029_U0_input_V_V_read;
wire   [511:0] frame_gaussians29029_U0_framed_V_V_i_din;
wire    frame_gaussians29029_U0_framed_V_V_i_write;
wire   [31:0] frame_gaussians29029_U0_mode_c_i_din;
wire    frame_gaussians29029_U0_mode_c_i_write;
wire    ap_sync_continue;
wire    prepare_geometry_U0_ap_start;
wire    prepare_geometry_U0_ap_done;
wire    prepare_geometry_U0_ap_continue;
wire    prepare_geometry_U0_ap_idle;
wire    prepare_geometry_U0_ap_ready;
wire    prepare_geometry_U0_input_V_V_read;
wire   [511:0] prepare_geometry_U0_output_V_V_din;
wire    prepare_geometry_U0_output_V_V_write;
wire    expand_subtiles_U0_ap_start;
wire    expand_subtiles_U0_ap_done;
wire    expand_subtiles_U0_ap_continue;
wire    expand_subtiles_U0_ap_idle;
wire    expand_subtiles_U0_ap_ready;
wire    expand_subtiles_U0_input_V_V_read;
wire   [511:0] expand_subtiles_U0_output_V_V_din;
wire    expand_subtiles_U0_output_V_V_write;
wire    expand_subtiles_U0_mode_read;
wire    framed_V_V_full_n;
wire   [511:0] framed_V_V_dout;
wire    framed_V_V_empty_n;
wire    mode_c_i_full_n;
wire   [31:0] mode_c_i_dout;
wire    mode_c_i_empty_n;
wire    geometry_V_V_full_n;
wire   [511:0] geometry_V_V_dout;
wire    geometry_V_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_prepare_geometry_U0_din;
wire    start_for_prepare_geometry_U0_full_n;
wire   [0:0] start_for_prepare_geometry_U0_dout;
wire    start_for_prepare_geometry_U0_empty_n;
wire   [0:0] start_for_expand_subtiles_U0_din;
wire    start_for_expand_subtiles_U0_full_n;
wire   [0:0] start_for_expand_subtiles_U0_dout;
wire    start_for_expand_subtiles_U0_empty_n;
wire    prepare_geometry_U0_start_full_n;
wire    prepare_geometry_U0_start_write;
wire    expand_subtiles_U0_start_full_n;
wire    expand_subtiles_U0_start_write;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

frame_gaussians29029 frame_gaussians29029_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(frame_gaussians29029_U0_ap_start),
    .start_full_n(frame_gaussians29029_U0_start_full_n),
    .ap_done(frame_gaussians29029_U0_ap_done),
    .ap_continue(frame_gaussians29029_U0_ap_continue),
    .ap_idle(frame_gaussians29029_U0_ap_idle),
    .ap_ready(frame_gaussians29029_U0_ap_ready),
    .start_out(frame_gaussians29029_U0_start_out),
    .start_write(frame_gaussians29029_U0_start_write),
    .mode(mode),
    .mode_out_din(frame_gaussians29029_U0_mode_out_din),
    .mode_out_full_n(mode_out_full_n),
    .mode_out_write(frame_gaussians29029_U0_mode_out_write),
    .tiles(tiles),
    .tiles_out_din(frame_gaussians29029_U0_tiles_out_din),
    .tiles_out_full_n(tiles_out_full_n),
    .tiles_out_write(frame_gaussians29029_U0_tiles_out_write),
    .input_V_V_dout(input_V_V_dout),
    .input_V_V_empty_n(input_V_V_empty_n),
    .input_V_V_read(frame_gaussians29029_U0_input_V_V_read),
    .framed_V_V_i_din(frame_gaussians29029_U0_framed_V_V_i_din),
    .framed_V_V_i_full_n(framed_V_V_full_n),
    .framed_V_V_i_write(frame_gaussians29029_U0_framed_V_V_i_write),
    .tiles1(tiles),
    .mode2(mode),
    .mode_c_i_din(frame_gaussians29029_U0_mode_c_i_din),
    .mode_c_i_full_n(mode_c_i_full_n),
    .mode_c_i_write(frame_gaussians29029_U0_mode_c_i_write)
);

prepare_geometry prepare_geometry_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(prepare_geometry_U0_ap_start),
    .ap_done(prepare_geometry_U0_ap_done),
    .ap_continue(prepare_geometry_U0_ap_continue),
    .ap_idle(prepare_geometry_U0_ap_idle),
    .ap_ready(prepare_geometry_U0_ap_ready),
    .input_V_V_dout(framed_V_V_dout),
    .input_V_V_empty_n(framed_V_V_empty_n),
    .input_V_V_read(prepare_geometry_U0_input_V_V_read),
    .output_V_V_din(prepare_geometry_U0_output_V_V_din),
    .output_V_V_full_n(geometry_V_V_full_n),
    .output_V_V_write(prepare_geometry_U0_output_V_V_write)
);

expand_subtiles expand_subtiles_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(expand_subtiles_U0_ap_start),
    .ap_done(expand_subtiles_U0_ap_done),
    .ap_continue(expand_subtiles_U0_ap_continue),
    .ap_idle(expand_subtiles_U0_ap_idle),
    .ap_ready(expand_subtiles_U0_ap_ready),
    .input_V_V_dout(geometry_V_V_dout),
    .input_V_V_empty_n(geometry_V_V_empty_n),
    .input_V_V_read(expand_subtiles_U0_input_V_V_read),
    .output_V_V_din(expand_subtiles_U0_output_V_V_din),
    .output_V_V_full_n(output_V_V_full_n),
    .output_V_V_write(expand_subtiles_U0_output_V_V_write),
    .mode_dout(mode_c_i_dout),
    .mode_empty_n(mode_c_i_empty_n),
    .mode_read(expand_subtiles_U0_mode_read)
);

fifo_w512_d16_B framed_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(frame_gaussians29029_U0_framed_V_V_i_din),
    .if_full_n(framed_V_V_full_n),
    .if_write(frame_gaussians29029_U0_framed_V_V_i_write),
    .if_dout(framed_V_V_dout),
    .if_empty_n(framed_V_V_empty_n),
    .if_read(prepare_geometry_U0_input_V_V_read)
);

fifo_w32_d3_A mode_c_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(frame_gaussians29029_U0_mode_c_i_din),
    .if_full_n(mode_c_i_full_n),
    .if_write(frame_gaussians29029_U0_mode_c_i_write),
    .if_dout(mode_c_i_dout),
    .if_empty_n(mode_c_i_empty_n),
    .if_read(expand_subtiles_U0_mode_read)
);

fifo_w512_d16_B geometry_V_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(prepare_geometry_U0_output_V_V_din),
    .if_full_n(geometry_V_V_full_n),
    .if_write(prepare_geometry_U0_output_V_V_write),
    .if_dout(geometry_V_V_dout),
    .if_empty_n(geometry_V_V_empty_n),
    .if_read(expand_subtiles_U0_input_V_V_read)
);

start_for_preparejbC start_for_preparejbC_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_prepare_geometry_U0_din),
    .if_full_n(start_for_prepare_geometry_U0_full_n),
    .if_write(frame_gaussians29029_U0_start_write),
    .if_dout(start_for_prepare_geometry_U0_dout),
    .if_empty_n(start_for_prepare_geometry_U0_empty_n),
    .if_read(prepare_geometry_U0_ap_ready)
);

start_for_expand_kbM start_for_expand_kbM_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_expand_subtiles_U0_din),
    .if_full_n(start_for_expand_subtiles_U0_full_n),
    .if_write(frame_gaussians29029_U0_start_write),
    .if_dout(start_for_expand_subtiles_U0_dout),
    .if_empty_n(start_for_expand_subtiles_U0_empty_n),
    .if_read(expand_subtiles_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign ap_done = ap_sync_done;

assign ap_idle = (prepare_geometry_U0_ap_idle & frame_gaussians29029_U0_ap_idle & expand_subtiles_U0_ap_idle);

assign ap_ready = internal_ap_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_done = (frame_gaussians29029_U0_ap_done & expand_subtiles_U0_ap_done);

assign ap_sync_ready = frame_gaussians29029_U0_ap_ready;

assign expand_subtiles_U0_ap_continue = ap_sync_continue;

assign expand_subtiles_U0_ap_start = start_for_expand_subtiles_U0_empty_n;

assign expand_subtiles_U0_start_full_n = 1'b1;

assign expand_subtiles_U0_start_write = 1'b0;

assign frame_gaussians29029_U0_ap_continue = ap_sync_continue;

assign frame_gaussians29029_U0_ap_start = real_start;

assign frame_gaussians29029_U0_start_full_n = (start_for_prepare_geometry_U0_full_n & start_for_expand_subtiles_U0_full_n);

assign input_V_V_read = frame_gaussians29029_U0_input_V_V_read;

assign internal_ap_ready = ap_sync_ready;

assign mode_out_din = frame_gaussians29029_U0_mode_out_din;

assign mode_out_write = frame_gaussians29029_U0_mode_out_write;

assign output_V_V_din = expand_subtiles_U0_output_V_V_din;

assign output_V_V_write = expand_subtiles_U0_output_V_V_write;

assign prepare_geometry_U0_ap_continue = 1'b1;

assign prepare_geometry_U0_ap_start = start_for_prepare_geometry_U0_empty_n;

assign prepare_geometry_U0_start_full_n = 1'b1;

assign prepare_geometry_U0_start_write = 1'b0;

assign start_for_expand_subtiles_U0_din = 1'b1;

assign start_for_prepare_geometry_U0_din = 1'b1;

assign start_out = real_start;

assign tiles_out_din = frame_gaussians29029_U0_tiles_out_din;

assign tiles_out_write = frame_gaussians29029_U0_tiles_out_write;

endmodule //split
