// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module frame_gaussians25726 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        mode,
        mode_out_din,
        mode_out_full_n,
        mode_out_write,
        tiles,
        tiles_out_din,
        tiles_out_full_n,
        tiles_out_write,
        input_V_V_dout,
        input_V_V_empty_n,
        input_V_V_read,
        framed_V_V_i_din,
        framed_V_V_i_full_n,
        framed_V_V_i_write,
        tiles1,
        mode2,
        mode_c_i_din,
        mode_c_i_full_n,
        mode_c_i_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] mode;
output  [31:0] mode_out_din;
input   mode_out_full_n;
output   mode_out_write;
input  [31:0] tiles;
output  [31:0] tiles_out_din;
input   tiles_out_full_n;
output   tiles_out_write;
input  [511:0] input_V_V_dout;
input   input_V_V_empty_n;
output   input_V_V_read;
output  [511:0] framed_V_V_i_din;
input   framed_V_V_i_full_n;
output   framed_V_V_i_write;
input  [31:0] tiles1;
input  [31:0] mode2;
output  [31:0] mode_c_i_din;
input   mode_c_i_full_n;
output   mode_c_i_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg mode_out_write;
reg tiles_out_write;
reg input_V_V_read;
reg[511:0] framed_V_V_i_din;
reg framed_V_V_i_write;
reg mode_c_i_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    mode_out_blk_n;
reg    tiles_out_blk_n;
reg    input_V_V_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond1_i_i_i_fu_182_p2;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_i_i_i_reg_319;
reg    framed_V_V_i_blk_n;
wire    ap_CS_fsm_state5;
reg    mode_c_i_blk_n;
reg   [31:0] j_i_i_i_reg_171;
reg    ap_block_state1;
reg    ap_block_state2;
wire   [31:0] t_fu_187_p2;
reg   [31:0] t_reg_302;
reg   [511:0] tmp_V_21_reg_307;
wire   [31:0] tmp_fu_206_p1;
reg   [31:0] tmp_reg_314;
wire   [0:0] exitcond_i_i_i_fu_210_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] j_fu_215_p2;
reg   [31:0] j_reg_323;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg   [31:0] t_i_i_i_reg_160;
reg   [31:0] ap_phi_mux_j_i_i_i_phi_fu_175_p4;
wire   [511:0] p_Result_s_fu_193_p5;
wire   [511:0] p_Result_82_fu_268_p5;
reg    ap_block_pp0_stage0_01001;
wire   [511:0] p_Result_83_fu_281_p5;
wire   [63:0] tmp_221_fu_221_p1;
wire   [511:0] p_Result_79_fu_224_p5;
wire   [9:0] p_Result_42_i_i_i_fu_236_p4;
wire   [511:0] p_Result_80_fu_245_p5;
wire   [511:0] p_Result_81_fu_257_p5;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_i_i_reg_319 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_i_i_i_reg_171 <= j_reg_323;
    end else if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_i_i_i_reg_171 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((framed_V_V_i_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        t_i_i_i_reg_160 <= t_reg_302;
    end else if ((~((mode_c_i_full_n == 1'b0) | (tiles_out_full_n == 1'b0) | (mode_out_full_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_i_i_i_reg_160 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_i_i_i_reg_319 <= exitcond_i_i_i_fu_210_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_reg_323 <= j_fu_215_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (1'b1 == ap_CS_fsm_state2))) begin
        t_reg_302 <= t_fu_187_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_V_21_reg_307 <= input_V_V_dout;
        tmp_reg_314 <= tmp_fu_206_p1;
    end
end

always @ (*) begin
    if ((exitcond_i_i_i_fu_210_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond_i_i_i_reg_319 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_j_i_i_i_phi_fu_175_p4 = j_reg_323;
    end else begin
        ap_phi_mux_j_i_i_i_phi_fu_175_p4 = j_i_i_i_reg_171;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b0 == ap_block_pp0_stage0) & (exitcond_i_i_i_reg_319 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        framed_V_V_i_blk_n = framed_V_V_i_full_n;
    end else begin
        framed_V_V_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((framed_V_V_i_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        framed_V_V_i_din = p_Result_83_fu_281_p5;
    end else if (((exitcond_i_i_i_reg_319 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001))) begin
        framed_V_V_i_din = p_Result_82_fu_268_p5;
    end else if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        framed_V_V_i_din = 512'd10055855947456947824680518748654384595609524365444295033292671082791323022555160232601405723625177570767523893639864538140315412108959927459825236754563072;
    end else if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        framed_V_V_i_din = p_Result_s_fu_193_p5;
    end else begin
        framed_V_V_i_din = 'bx;
    end
end

always @ (*) begin
    if ((((exitcond_i_i_i_reg_319 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)) | (~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((framed_V_V_i_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5)))) begin
        framed_V_V_i_write = 1'b1;
    end else begin
        framed_V_V_i_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (exitcond_i_i_i_reg_319 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        input_V_V_blk_n = input_V_V_empty_n;
    end else begin
        input_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((exitcond_i_i_i_reg_319 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | (~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        input_V_V_read = 1'b1;
    end else begin
        input_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_c_i_blk_n = mode_c_i_full_n;
    end else begin
        mode_c_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((mode_c_i_full_n == 1'b0) | (tiles_out_full_n == 1'b0) | (mode_out_full_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_c_i_write = 1'b1;
    end else begin
        mode_c_i_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_out_blk_n = mode_out_full_n;
    end else begin
        mode_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((mode_c_i_full_n == 1'b0) | (tiles_out_full_n == 1'b0) | (mode_out_full_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        mode_out_write = 1'b1;
    end else begin
        mode_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tiles_out_blk_n = tiles_out_full_n;
    end else begin
        tiles_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((mode_c_i_full_n == 1'b0) | (tiles_out_full_n == 1'b0) | (mode_out_full_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tiles_out_write = 1'b1;
    end else begin
        tiles_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((mode_c_i_full_n == 1'b0) | (tiles_out_full_n == 1'b0) | (mode_out_full_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~(((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0))) & (exitcond1_i_i_i_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (exitcond_i_i_i_fu_210_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (exitcond_i_i_i_fu_210_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((framed_V_V_i_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i_i_i_reg_319 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond_i_i_i_reg_319 == 1'd0) & (input_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i_i_i_reg_319 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond_i_i_i_reg_319 == 1'd0) & (input_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i_i_i_reg_319 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond_i_i_i_reg_319 == 1'd0) & (input_V_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((mode_c_i_full_n == 1'b0) | (tiles_out_full_n == 1'b0) | (mode_out_full_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = (((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd0) & (input_V_V_empty_n == 1'b0)) | ((exitcond1_i_i_i_fu_182_p2 == 1'd1) & (framed_V_V_i_full_n == 1'b0)));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((exitcond_i_i_i_reg_319 == 1'd0) & (framed_V_V_i_full_n == 1'b0)) | ((exitcond_i_i_i_reg_319 == 1'd0) & (input_V_V_empty_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign exitcond1_i_i_i_fu_182_p2 = ((t_i_i_i_reg_160 == tiles1) ? 1'b1 : 1'b0);

assign exitcond_i_i_i_fu_210_p2 = ((ap_phi_mux_j_i_i_i_phi_fu_175_p4 == tmp_reg_314) ? 1'b1 : 1'b0);

assign j_fu_215_p2 = (ap_phi_mux_j_i_i_i_phi_fu_175_p4 + 32'd1);

assign mode_c_i_din = mode2;

assign mode_out_din = mode;

assign p_Result_42_i_i_i_fu_236_p4 = {{tmp_V_21_reg_307[73:64]}};

assign p_Result_79_fu_224_p5 = {{input_V_V_dout[511:352]}, {tmp_221_fu_221_p1}, {input_V_V_dout[287:0]}};

assign p_Result_80_fu_245_p5 = {{p_Result_79_fu_224_p5[511:362]}, {p_Result_42_i_i_i_fu_236_p4}, {p_Result_79_fu_224_p5[351:0]}};

assign p_Result_81_fu_257_p5 = {{p_Result_80_fu_245_p5[511:416]}, {j_reg_323}, {p_Result_80_fu_245_p5[383:0]}};

assign p_Result_82_fu_268_p5 = {{2'd0}, {p_Result_81_fu_257_p5[509:0]}};

assign p_Result_83_fu_281_p5 = {{2'd2}, {tmp_V_21_reg_307[509:0]}};

assign p_Result_s_fu_193_p5 = {{2'd1}, {input_V_V_dout[509:0]}};

assign start_out = real_start;

assign t_fu_187_p2 = (t_i_i_i_reg_160 + 32'd1);

assign tiles_out_din = tiles;

assign tmp_221_fu_221_p1 = tmp_V_21_reg_307[63:0];

assign tmp_fu_206_p1 = input_V_V_dout[31:0];

endmodule //frame_gaussians25726
